### ISSUE TITLE
zato create server error invalid literal for int() with base 10: None

### ISSUE THREAD

**Issue by amin1994** [zatosource/zato#1000]
Hi , 

I run this command :
zato create server ~/tmpforzato postgresql localhost 6379 quickstart-315862 server3 --verbose 

and got this error:
File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/zato_command.py", line 408, in main
    return run_command(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 380, in run_command
    command_class[args.command](args).run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 656, in run
    return_code = self.execute(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/create_server.py", line 618, in execute
    engine = self._get_engine(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 572, in _get_engine
    return sqlalchemy.create_engine(get_engine_url(args), connect_args=connect_args)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 50, in create
    u = url.make_url(name_or_url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 211, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 267, in _parse_rfc1738_args
    return URL(name, **components)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 60, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: 'None'

2019-11-11 17:46:23,146 - ERROR - 7164:MainThread - Create:668 - File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/zato_command.py", line 408, in main
    return run_command(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 380, in run_command
    command_class[args.command](args).run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 656, in run
    return_code = self.execute(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/create_server.py", line 618, in execute
    engine = self._get_engine(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 572, in _get_engine
    return sqlalchemy.create_engine(get_engine_url(args), connect_args=connect_args)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 50, in create
    u = url.make_url(name_or_url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 211, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 267, in _parse_rfc1738_args
    return URL(name, **components)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 60, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: 'None'

**Comment by fenist19** [comment]
please try to use command from config/ change zato path to you path and add you setting.
I think what you not set one of ports.
`/opt/zato_dir/zato/code/bin/zato from-config /opt/zato_dir/zato_server.config --verbose`
# zato create server config
cluster_name=Test
command=create_server
kvdb_host=redis
kvdb_port=6379
kvdb_password=
odb_db_name=zato3
odb_host=postgres
odb_password=zato3
odb_port=5432
odb_type=postgresql
odb_user=zato3
lb_host=balancer
lb_port=11223
lb_agent_port=20151
store_config=False
tech_account_name=admin
admin_invoke_password=password
path=/opt/zato_dir/env/server/
server_name=server1
secret_key=

**Comment by kadam-SoftServe** [comment]
I had this issue. You must have no empty secret_key, then will not problem. Also secret key should be correct pattern.
