### ISSUE TITLE
Cannot create/edit REST outgoing connection

### ISSUE THREAD

**Issue by mciancio** [zatosource/zato#1007]
When I try to create a new outgoing REST connection or edit an existing one I get the following error:

Object could not be created, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/http_soap.py", line 254, in create
    response = req.zato.client.invoke('zato.http-soap.create', _get_edit_create_message(req.POST))
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/http_soap.py", line 73, in _get_edit_create_message
    'http_accept': params[prefix + 'http_accept'],
  File "/opt/zato/3.1.0/code/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in _getitem_
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'http_accept'"

And nothing is edited/created.
I'm using RHEL, Python 2.7.5

**Comment by dsuch** [comment]
Can you provide your Zato version? ```zato --version```

Also, in what way you are creating or editing the connections? Using web-admin?

**Comment by mciancio** [comment]
The exact versions are:

- zato 3.1+rev544100e-py2.7.5
- Rhel 7.7 
- Python 2.7.5  

I'm using web-admin.
Thanks

**Comment by dsuch** [comment]
You need to follow all the steps in the installation instructions here, including the installation of updates:

https://zato.io/docs/admin/guide/install/py27/rhel.html

**Comment by mciancio** [comment]
I repeated it twice...
My first hypothesis was a wrong install but it was the same after
reinstallation.
Thanks

Il gio 19 dic 2019, 16:57 Dariusz Suchojad <notifications@github.com> ha
scritto:

**Comment by DimShadoWWW** [comment]
@mciancio can you provide some other information?
- full output of `zato --version`
- full output of `lsb_release -a`
- can you [download](https://zato.io/docs/admin/guide/install/update.html) the latest updates and try again?

**Comment by mciancio** [comment]
$ zato --version
Zato 3.1+rev.544100e-py2.7.5

lsb_release is not present, but follows some info:

NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"

Thanks

Il giorno ven 20 dic 2019 alle ore 06:35 DimShadoWWW <
notifications@github.com> ha scritto:

**Comment by mciancio** [comment]
Sorry, I forgot about downloading new updates... I did it two days ago: is updating necessary now? (it's a bit complicated for me in this moment...)?

**Comment by DimShadoWWW** [comment]
@mciancio you Zato is outdated https://github.com/zatosource/zato/commit/544100ee343fa25a581325c70bc082520f6fe581 (commit from June 12)

Can you try to update it? If the system is offline you can try a Git's offline workflows (there are at least two or three) to update Zato. 

I did some tests and I couldn't reproduce your error:
```
$ zato --version
Zato 3.1+rev.84f446d-py2.7.5
$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```

**Comment by mciancio** [comment]
Thank you.
It's strange... I installed it following your instructions and then
upgrading. No error. I'll try again but I've to wait the end of
Christmastime. I've no direct access to the server.
Thank you very much. I'll let you know. Bye.

Il sab 21 dic 2019, 16:33 DimShadoWWW <notifications@github.com> ha scritto:

**Comment by dsuch** [comment]
No activity, I am closing the ticket.
