### ISSUE TITLE
Again 2 problems with TLS client keys and certificates AND CA certificates

### ISSUE THREAD

**Issue by kadam-SoftServe** [zatosource/zato#1023]
First issue, after upload certificate by form in admin GUI, we have succesfull uploaded cert  .. but, a description of cert in admin GUI is strange, it's look like string was written like bytecodes

```
b'C'=b'No'; b'CN'=b'Test'; b'L'=b'Test'; b'O'=b'Test'; b'OU'=b'Test'; b'ST'=b'Test'; b'emailAddress'=b'test@example.com'
```
Similar issue was in past [https://github.com/zatosource/zato/issues/972](https://github.com/zatosource/zato/issues/972)

Seccond issue - TLS client keys and certificates

After upload cert with key we have exception:
```
Traceback (most recent call last):
  File "/opt/zato/zato/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 503, in __call__
    response = self.req.zato.client.invoke(self.service_name, self.input_dict)
  File "/opt/zato/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 2cf0c0062d9743e3227838c9
Details: Traceback (most recent call last):
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 713, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in set_response_data
    response = response.getvalue(serialize=kwargs['serialize'])
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 532, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 476, in _getvalue
    raise ZatoException(self.zato_cid, msg)
zato.common.ZatoException: <ZatoException at 0x7f3c7012f228 cid:`2cf0c0062d9743e3227838c9`, msg:`Expected elem:`name` not found in item:`{'info': '', 'name': '', 'id': '', 'opaque1': '', 'password_type': '', 'auth_data': '', 'username': ''}``>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 356, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 627, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 735, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 683, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 570, in _invoke
    service.handle()
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 815, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 791, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 730, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 683, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 570, in _invoke
    service.handle()
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/meta.py", line 381, in handle_impl
    attrs.instance_hook(self, input, instance, attrs)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/security/tls/key_cert.py", line 52, in instance_hook
    full_path = store_tls(self.server.tls_dir, decrypted, True)
  File "/opt/zato/zato/code/zato-common/src/zato/common/util/__init__.py", line 1169, in store_tls
    pem_file.write(payload)
TypeError: write() argument must be str, not bytes
```
Somewhere is miss encode('utf-8'), or is too much encode or write file is wrong by mode 'w', maybe it should be 'wb'

Please fix this issues. I localized file - it's probably in zato-common/uitils/__init__.py

**Comment by kadam-SoftServe** [comment]
@dsuch Hello, could you confirm that my notification problems about connections with CA TLS cert are still present in the code of Zato ?
I ran Zato by source code, but this problems are also in docker image.
Could you tell me when we might get fixtures for issues above ?

Thx.

**Comment by krzysztof-adamski** [comment]
Somebody has got these same problems ? When can we expect a response or correction?
