### ISSUE TITLE
 ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11223): Max retries

### ISSUE THREAD

**Issue by krzysztof-adamski** [zatosource/zato#1028]
```
, line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11223): Max retries exceeded with url: /zato/admin/invoke (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))
```
```
ceback (most recent call last):
  File "/home/kadamski/projects/Zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/kadamski/projects/Zato/zato/code/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/kadamski/projects/Zato/zato/code/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kadamski/projects/Zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/kadamski/projects/Zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/kadamski/projects/Zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/kadamski/projects/Zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: 
```

git diff main branch_few_days_ago

zato-server/src/zat/server/connection/queue.py
```
branch: main

class _Connection(object):
    """ Meant to be used as a part of a 'with' block - returns a connection from its queue each time 'with' is entered
    assuming the queue isn't empty.
    """
    def __init__(self, client_queue, conn_name, should_block=False, block_timeout=None):
        # type: (Queue, str, bool, int)
        self.queue = client_queue
        self.conn_name = conn_name
        self.should_block = should_block
        self.block_timeout = block_timeout
        self.client = None # type: object

    def __enter__(self):
        try:
            self.client = self.queue.get(self.should_block, self.block_timeout)
        except Empty:
            self.client = None
            msg = 'No free connections to `{}`'.format(self.conn_name)
            logger.error(msg)
            raise Exception(msg)
        else:
            return self.client

    def __exit__(self, type, value, traceback):
        if self.client:
            self.queue.put(self.client)

class ConnectionQueue(object):
    """ Holds connections to resources. Each time it's called a connection is fetched from its underlying queue
    assuming any connection is still available.
    """
    def __init__(self, pool_size, queue_build_cap, conn_name, conn_type, address, add_client_func):

        self.queue = Queue(pool_size)
        self.queue_build_cap = queue_build_cap
        self.conn_name = conn_name
        self.conn_type = conn_type
        self.address = address
        self.add_client_func = add_client_func
        self.keep_connecting = True
        self.is_building_conn_queue = False
        self.queue_building_stopped = False
        self.lock = RLock()

        # How many add_client_func instances are running currently,
        # must be updated with self.lock held.
        self.in_progress_count = 0

        self.logger = logging.getLogger(self.__class__.__name__)

    def __call__(self, should_block=False, block_timeout=None):
        # type: (bool, int) -> _Connection
        return _Connection(self.queue, self.conn_name, should_block, block_timeout)

working branch:

class _Connection(object):
    """ Meant to be used as a part of a 'with' block - returns a connection from its queue each time 'with' is entered
    assuming the queue isn't empty.
    """
    def __init__(self, client_queue, conn_name):
        self.queue = client_queue
        self.conn_name = conn_name
        self.client = None

    def __enter__(self):
        try:
            self.client = self.queue.get(block=False)
        except Empty:
            self.client = None
            msg = 'No free connections to `{}`'.format(self.conn_name)
            logger.error(msg)
            raise Exception(msg)
        else:
            return self.client

    def __exit__(self, type, value, traceback):
        if self.client:
            self.queue.put(self.client)

class ConnectionQueue(object):
    """ Holds connections to resources. Each time it's called a connection is fetched from its underlying queue
    assuming any connection is still available.
    """
    def __init__(self, pool_size, queue_build_cap, conn_name, conn_type, address, add_client_func):

        self.queue = Queue(pool_size)
        self.queue_build_cap = queue_build_cap
        self.conn_name = conn_name
        self.conn_type = conn_type
        self.address = address
        self.add_client_func = add_client_func
        self.keep_connecting = True
        self.is_building_conn_queue = False
        self.queue_building_stopped = False
        self.lock = RLock()

        # How many add_client_func instances are running currently,
        # must be updated with self.lock held.
        self.in_progress_count = 0

        self.logger = logging.getLogger(self.__class__.__name__)

    def __call__(self):
        return _Connection(self.queue, self.conn_name)

```

**Comment by krzysztof-adamski** [comment]
Is somebody got this errors, when the Zato is started on main branch. ?

**Comment by krzysztof-adamski** [comment]
Very strange bug. After stopped Zato You cannot start again, because we see warnings that pid related only with load-balancer is used already. But it is no true, there so any process. You can run server after remove pid file. 
Second - pid filename load-balancer have different name than others : scheduler, server etc.

**Comment by krzysztof-adamski** [comment]
I found sollution temporary :)

My problem was with runing load-balancer. I did't know reasons why he crash after start.
I running HP with --fg param then I saw exception like the bottom:

```
Exception: Failed to start HAProxy. command:[['haproxy', '-D', '-f', '/home/kadamski/projects/zato/clusters/quickstart/load-balancer/config/repo/zato.config', '-p', '/home/kadamski/projects/zato/clusters/quickstart/load-balancer/pidfile']], return code:[1], stdout:[b''], stderr:[b'[ALERT] 069/111009 (30978) : Starting frontend GLOBAL: cannot switch final and temporary UNIX sockets [/home/kadamski/projects/zato/clus\n'] 
`, kw:`{'async': False}`
```
Then I checked config `load-balancer/config/repo/zato.config` and I had got line:

```
stats socket /home/kadamski/projects/zato/clusters/quickstart/load-balancer/haproxy-stat.sock # ZATO global:stats_socket
```
I chanched this line for line
```
stats socket /run/haproxy/haproxy-stat.sock # ZATO global:stats_socket
```
So if Zato is installed and run not like user Zato we could have some problems, maybe haproxy should have access write for directory of my project.
Strange, because when I started journey with Zato a month ago I hadn't problems with haproxy after create cluster in own selected directory.
