### ISSUE TITLE
Issues while trying to start created server (using Quickstart)

### ISSUE THREAD

**Issue by Xorso** [zatosource/zato#1046]
After running `zato quickstart` with the necessary parameters and then trying to start the server I get the following error message:

```
2020-05-04 08:44:19,629 - INFO - 22235:MainThread - zato.server.service.store:0 - Deploying cached internal services (server1)
/opt/zato/dbsa.test/server1/config/repo/internal-cache.dat
2020-05-04 08:44:19,632 - ERROR - 22235:MainThread - zato:0 - Exception in worker process
Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/ext/zunicorn/arbiter.py", line 616, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 1022, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 575, in start_server
    is_first, locally_deployed = self._after_init_common(server)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 430, in _after_init_common
    is_first, locally_deployed = self.maybe_on_first_worker(server, self.kvdb.conn)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 360, in maybe_on_first_worker
    locally_deployed = import_initial_services_jobs(is_first)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 317, in import_initial_services_jobs
    internal_service_modules, self.base_dir, self.sync_internal, is_first))
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/store.py", line 577, in import_internal_services
    dill_items = dill_load(f)
  File "/opt/zato/current/lib/python3.6/site-packages/dill/dill.py", line 250, in load
    obj = pik.load()
  File "/usr/lib64/python3.6/pickle.py", line 1048, in load
    raise EOFError
EOFError
```

I don't know if this is an internal-cache.dat problem but the file does exist:
```[(test) zato@zato01.test.ostk.com ~]$ ls -l /opt/zato/dbsa.test/server1/config/repo/internal-cache.dat
-rw-rw-r-- 1 zato zato 0 May  4 07:56 /opt/zato/dbsa.test/server1/config/repo/internal-cache.dat
```

And the necessary entry in the database:
```
postgres@[local]zato=# select * from cache_builtin;
 cache_id | max_size | max_item_size | extend_expiry_on_get | extend_expiry_on_set |  sync_method  | persistent_storage
----------+----------+---------------+----------------------+----------------------+---------------+--------------------
        1 |    10000 |         10000 | t                    | t                    | in-background | sql
(1 row
```

Not sure what I am missing here.

**Comment by dsuch** [comment]
Hello @Xorso - can you please delete the internal-cache.dat file and retry? If it helps then I will know how to delete with it permanently. Thank you.

**Comment by Xorso** [comment]
Deleted and tried starting again and got a whole lot of this:

```
[(test) zato@zato01.test.ostk.com ~]$ rm env/dbsa.test/server1/config/repo/internal-cache.dat
[(test) zato@zato01.test.ostk.com ~]$ zato start env/dbsa.test/server1/ --fg --verbose
2020-05-04 13:00:38,269 - INFO - 17010:MainThread - zato:0 - Starting Zato 3.1+rev.2aeb8a3-py3.6.8
2020-05-04 13:00:38,276 - INFO - 17010:MainThread - zato:0 - Listening at: http://0.0.0.0:17010 (17010)
2020-05-04 13:00:38,277 - INFO - 17010:MainThread - zato:0 - Using worker: gevent
2020-05-04 13:00:38,282 - INFO - 17036:MainThread - zato:0 - Booting worker with pid: 17036
2020-05-04 13:00:38,835 - INFO - 17036:MainThread - zato.server.base.parallel:0 - Preferred address of `server1@quickstart-114301` (pid: 17036) is `http://10.18.35.50:17010`
2020-05-04 13:00:40,352 - INFO - 17036:MainThread - zato.server.service.store:0 - Deploying and caching internal services (server1)
2020-05-04 13:00:42,532 - ERROR - 17036:MainThread - zato:0 - Exception in worker process
Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/ext/zunicorn/arbiter.py", line 616, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 1022, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 575, in start_server
    is_first, locally_deployed = self._after_init_common(server)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 430, in _after_init_common
    is_first, locally_deployed = self.maybe_on_first_worker(server, self.kvdb.conn)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 360, in maybe_on_first_worker
    locally_deployed = import_initial_services_jobs(is_first)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 317, in import_initial_services_jobs
    internal_service_modules, self.base_dir, self.sync_internal, is_first))
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/store.py", line 562, in import_internal_services
    f.write(dill_dumps(internal_cache))
  File "/opt/zato/current/lib/python3.6/site-packages/dill/dill.py", line 243, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/opt/zato/current/lib/python3.6/site-packages/dill/dill.py", line 236, in dump
    pik.dump(obj)
  File "/usr/lib64/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/zato/current/lib/python3.6/site-packages/dill/dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.6/pickle.py", line 852, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "/usr/lib64/python3.6/pickle.py", line 805, in _batch_appends
    save(x)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/zato/current/lib/python3.6/site-packages/dill/dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/zato/current/lib/python3.6/site-packages/dill/dill.py", line 1168, in save_module
    state=_main_dict)
  File "/usr/lib64/python3.6/pickle.py", line 634, in save_reduce
    save(state)
```

Finishing with this:
```
TypeError: can't pickle sqlalchemy.cprocessors.UnicodeResultProcessor objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/ext/zunicorn/arbiter.py", line 630, in spawn_worker
    sys.exit(self.WORKER_BOOT_ERROR)
SystemExit: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/ext/zunicorn/arbiter.py", line 636, in spawn_worker
    self.cfg.worker_exit(self, worker)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 1040, in worker_exit
    worker.app.zato_wsgi_app.cleanup_on_stop()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 1098, in cleanup_on_stop
    self.cleanup_wsx(True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 1050, in cleanup_wsx
    self.invoke(wsx_service, {'needs_pid': needs_pid})
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 931, in invoke
    *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1502, in invoke
    }, channel, None, needs_response=True, serialize=serialize)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1563, in on_message_invoke_service
    service, is_active = self.server.service_store.new_instance_by_name(msg['service'])
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/store.py", line 493, in new_instance_by_name
    return self.new_instance(impl_name, *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/store.py", line 481, in new_instance
    return _info['service_class'](*args, **kwargs), _info['is_active']
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/__init__.py", line 78, in __init__
    super(AdminService, self).__init__()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 403, in __init__
    self._worker_store.sql_pool_store,
AttributeError: 'WorkerStore' object has no attribute 'sql_pool_store'
```

**Comment by dsuch** [comment]
I am not sure what you mean by "Finishing with this:" - is that not the whole traceback? Have you shortened it?

**Comment by Xorso** [comment]
Correct the first batch just repeats over and over again (more than several times and then that last part is the bottom of the stack trace.

**Comment by dsuch** [comment]
Alright, please do not shorten any such tracebacks when submitting them here. Can you also tell me what operating system and Python version it is exactly?

**Comment by Xorso** [comment]
```

**Comment by Xorso** [comment]
I should mention that it recreates the file and I go back to getting the same error.

**Comment by DimShadoWWW** [comment]
Hello @Xorso I could not recreate your issue. I installed Centos7 and Zato two times, created a quickstart environment and it worked OK.
Please, can you tell me how to reproduce it step by step? Thank you

**Comment by Xorso** [comment]
I think it was a problem with the RPM install. Once I did an install from the source I was able to get it working. Not sure of our Centos7 image strips out something that is needed but I am going to close this out.
