### ISSUE TITLE
self.patterns.invoke_retry.invoke TypeError: '>=' not supported between instances of 'Exception' and 'int'

### ISSUE THREAD

**Issue by aixi88** [zatosource/zato#1048]
thanks!
```
import json
from zato.server.service.internal.helpers import Service

class InvokeRetryTest(Service):
    name = 'invoke.retry.test'

    def handle(self):
        target = 'invoke.retry.test.target'
        config = {
            'repeats': 3,
            'seconds': 1,
        }
        cid = self.patterns.invoke_retry.invoke(target, **config)
        self.response.payload =cid

class InvokeRetryTestTarget(Service):
    name = 'invoke.retry.test.target'

    def handle(self):
        self.logger.info('target payload %r',json.dumps(self.request.payload))
        raise Exception('target Exception')
```

```
Could not invoke the service. name:`invoke.retry.test`, cluster_id:`1`, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/service.py", line 555, in invoke
    response = req.zato.client.invoke(name, **input_dict)
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: defdfe4f8115dba046e4a8c5
Details: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pattern/invoke_retry.py", line 155, in invoke
    result = self.invoking_service.invoke(target, *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 792, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 768, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/work/hot-deploy/current/invoke_retry_test.py", line 26, in handle
    raise Exception('target Exception')
Exception: target Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pattern/invoke_retry.py", line 178, in invoke
    result = self.invoking_service.invoke(target, *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 792, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 768, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/work/hot-deploy/current/invoke_retry_test.py", line 26, in handle
    raise Exception('target Exception')
Exception: target Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 792, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 768, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/work/hot-deploy/current/invoke_retry_test.py", line 18, in handle
    cid = self.patterns.invoke_retry.invoke(target, **config)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pattern/invoke_retry.py", line 181, in invoke
    (retry_repeats-remaining)+1, retry_repeats, target, retry_seconds, self.invoking_service.cid, e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pattern/invoke_retry.py", line 32, in retry_failed_msg
    so_far, retry_repeats, service_name, retry_seconds, orig_cid, format_exc(e))
  File "/usr/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib/python3.6/traceback.py", line 498, in __init__
    _seen=_seen)
  File "/usr/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'Exception' and 'int'
```

**Comment by aixi88** [comment]
and after add async_fallback, the servie 'invoke.retry.test.callback' have not be invoked

```
import json
from zato.server.service.internal.helpers import Service

class InvokeRetryTest(Service):
    name = 'invoke.retry.test'

    def handle(self):
        target = 'invoke.retry.test.target'
        config = {
            'repeats': 3,
            'seconds': 1,
            'async_fallback': True,
            'callback': 'invoke.retry.test.callback',
            'context': {'hi': 'there'},
        }
        cid = self.patterns.invoke_retry.invoke(target, **config)
        self.response.payload =cid

class InvokeRetryTestTarget(Service):
    name = 'invoke.retry.test.target'

    def handle(self):
        self.logger.info('target payload %r',json.dumps(self.request.payload))
        raise Exception('target Exception')


class InvokeRetryTestCallback(Service):
    name = 'invoke.retry.test.callback'

    def handle(self):
        self.logger.info('callback payload %r', json.dumps(self.request.payload))
```

**Comment by dsuch** [comment]
Hi @aixi88,

is it possible to get in touch with you directly? My email is dsuch at zato.io.

Regards.

**Comment by aixi88** [comment]
I'm sorry, I'm only seeing your reply now, thank you very much for your help, my email is aixi88@163.com

Thank you!
