### ISSUE TITLE
Cannot start Zato

### ISSUE THREAD

**Issue by rashmireddy2719** [zatosource/zato#1064]
I followed all the steps to install zato on ubuntu from 
https://zato.io/docs/tutorial/01.html  and created an empty directory env/qs-1 and executed
zato quickstart create ~/env/qs-1 sqlite localhost 6379 \
  --kvdb_password 'mypassword' --verbose

It shows:
File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/zato_command.py", line 424, in main
    return run_command(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/_init_.py", line 382, in run_command
    command_class[args.command](args).run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/_init_.py", line 658, in run
    return_code = self.execute(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/quickstart.py", line 297, in execute
    os.mkdir(ca_path)
PermissionError: [Errno 13] Permission denied: '/opt/zato/env/qs-1/ca'

Can anyone help me to solve this error?

**Comment by dsuch** [comment]
Hello @rashmireddy2719,

this is a permission denied error - raised by the operating system, not Zato. I am not sure what is not clear here?

Regards.

**Comment by rashmireddy2719** [comment]
Thanks, @dsuch ,

It's my bad, got that error resolved.
