### ISSUE TITLE
Cannot deploy the service to zato

### ISSUE THREAD

**Issue by rashmireddy2719** [zatosource/zato#1067]
I created a service and tried to deploy it to server using command line, say:

cp schedule_tour.py /opt/zato/tour_env/qs-1/server1/pickup/incoming/services

and my service "schedule_tour.py" has the following basic code:

from zato.server.service import Service

class GetTourScheduleDetails(Service):
    def handle(self):
        self.log_input()

and my server.log shows:

2020-07-17 10:07:01,847 - ^[[1;37mINFO^[[0m - 3779:MainThread - zato:0 - Starting Zato 3.1+rev.fbc0ac851-py3.6.8
2020-07-17 10:07:01,852 - ^[[1;37mINFO^[[0m - 3779:MainThread - zato:0 - Listening at: http://0.0.0.0:17010 (3779)
2020-07-17 10:07:01,852 - ^[[1;37mINFO^[[0m - 3779:MainThread - zato:0 - Using worker: gevent
2020-07-17 10:07:01,855 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato:0 - Booting worker with pid: 3807
2020-07-17 10:07:02,355 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato.server.base.parallel:0 - Preferred address of `server1@quickstart-670645` (pid: 3807) is `http://10.0.2.15:17010`
2020-07-17 10:07:03,878 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato.server.service.store:0 - Deploying and caching internal services (server1)
2020-07-17 10:07:05,283 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato.server.service.store:0 - Deployed and cached 545 internal services (6.5 MB) (server1)
2020-07-17 10:07:05,283 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato.server.base.parallel:0 - Deploying user-defined services (server1)
2020-07-17 10:07:05,313 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato.server.base.parallel:0 - Deployed 0 user-defined services  (server1)
2020-07-17 10:07:05,785 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato.server.base.parallel:0 - First worker of `server1` is 3807
2020-07-17 10:07:05,787 - ^[[1;37mINFO^[[0m - 3807:DummyThread-16 - zato:0 - Set sk_server for sub_key `zpsk.rest.f60f7f` (wsx/srv:0/0) - `server1:3807`, current sk_servers:
+--------+-----------------+----------+--------+-------------------+-----------------------------------------------------------------------------+
|   #    |     created     |   name   |  pid   |   channel_name    |                                   sub_key                                   |
+========+=================+==========+========+===================+=============================================================================+
|   1    |   2020-07-17    | server1  |  3807  |        ---        |                              zpsk.rest.f60f7f                               |
|        | 14:07:05.786543 |          |        |                   |                                                                             |
+--------+-----------------+----------+--------+-------------------+-----------------------------------------------------------------------------+
2020-07-17 10:07:05,795 - ^[[1;37mINFO^[[0m - 3807:DummyThread-17 - zato.helpers.input-logger:0 - {'request.payload': 'Sample payload for a startup service (first worker)', 'channel': 'startup-service', 'cid': '987aef12ab83cc96fc3fcff3', 'data_format': None, 'environ': {}, 'impl_name': 'zato.server.service.internal.helpers.InputLogger', 'invocation_time': datetime.datetime(2020, 7, 17, 14, 7, 5, 795041), 'job_type': None, 'name': 'zato.helpers.input-logger', 'slow_threshold': None, 'usage': 30, 'wsgi_environ': {'zato.request_ctx.async_msg': Bunch(action='101802', channel='startup-service', cid='987aef12ab83cc96fc3fcff3', msg_type='0001', payload='Sample payload for a startup service (first worker)', service='zato.helpers.input-logger'), 'zato.request_ctx.in_reply_to': None, 'zato.request_ctx.fanout_cid': None, 'zato.request_ctx.parallel_exec_cid': None}}
2020-07-17 10:07:05,803 - ^[[1;37mINFO^[[0m - 3807:DummyThread-32 - zato.common.ipc.subscriber.Subscriber:0 - Established sub/bind to ipc:///tmp/zato-ipc-quickstart_670645_server1_3807 (self.pid: 3807)
2020-07-17 10:07:05,814 - ^[[1;37mINFO^[[0m - 3807:DummyThread-33 - pub.zato.channel.web-socket.cleanup-wsx:0 - Cleaning up old WSX connections; now:`2020-07-17T14:07:05.814123`, md:`7200`, ma:`2020-07-17 12:07:05.814123`
2020-07-17 10:07:06,003 - ^[[1;37mINFO^[[0m - 3807:MainThread - zato.server.base.parallel:0 - Started `server1@quickstart-670645` (pid: 3807)
2020-07-17 10:07:08,984 - ^[[1;37mINFO^[[0m - 3807:DummyThread-35 - pub.zato.channel.web-socket.cleanup-wsx:0 - Cleaning up old WSX connections; now:`2020-07-17T14:07:08.984017`, md:`7200`, ma:`2020-07-17 12:07:08.984017`
2020-07-17 10:08:55,018 - ^[[1;37mINFO^[[0m - 3807:DummyThread-36 - zato.hot-deploy.create:0 - Creating tar archive
2020-07-17 10:08:55,019 - ^[[1;37mINFO^[[0m - 3807:DummyThread-36 - zato.hot-deploy.create:0 - Creating tar archive
2020-07-17 10:08:55,028 - ^[[1;31mERROR^[[0m - 3807:DummyThread-36 - zato.server.service.store:0 - Could not load source, file_name:`/opt/zato/tour_env/qs-1/server1/work/hot-deploy/current/schedule_tour.py`, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/store.py", line 936, in import_services_from_file
    mod_info = import_module_from_path(file_name, base_dir)
  File "/opt/zato/3.1.0/code/zato-common/src/zato/common/util/__init__.py", line 610, in import_module_from_path
    return ModuleInfo(file_name, imp.load_source(mod_name, file_name))
  File "/opt/zato/3.1.0/code/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
"server.log" 270 lines, 23986 characters

Zato  Version - 3.1
Python version- 3.6
OS- ubuntu 18.04 under virtual box

Can anyone help me resolving this issue?

**Comment by dsuch** [comment]
Is that the whole of the server.log file?

**Comment by rashmireddy2719** [comment]
File "<frozen importlib._bootstrap>", line 684, in _load
This is the only extra line I could see in server.log file

**Comment by rashmireddy2719** [comment]
No,
The rest is here.

File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/zato/tour_env/qs-1/server1/work/hot-deploy/current/schedule_tour.py", line 6
    self.log_input()
                   ^
TabError: inconsistent use of tabs and spaces in indentation
`
2020-07-17 10:08:55,061 - ^[[1;33mWARNING^[[0m - 3807:DummyThread-36 - zato.hot-deploy.create:0 - No services were deployed from module `schedule_tour.py`
2020-07-17 10:08:55,062 - ^[[1;33mWARNING^[[0m - 3807:DummyThread-36 - zato.server.service:0 - Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 551, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 270, in handle
    for service_id in services_deployed:
TypeError: 'NoneType' object is not iterable

2020-07-17 10:08:55,062 - ^[[1;31mERROR^[[0m - 3807:DummyThread-36 - zato:0 - Could not handle broker msg:`Bunch(action='102200', cid='4e359773bf4095d0f6d73ae6', msg_type='0002', package_id=1, payload={'package_id': 1}, service='zato.hot-deploy.create')`, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-broker/src/zato/broker/__init__.py", line 52, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1813, in on_broker_msg_HOT_DEPLOY_CREATE_SERVICE
    serialize=False, needs_response=True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1804, in on_broker_msg_hot_deploy
    return self.on_message_invoke_service(msg, 'hot-deploy', 'HOT_DEPLOY_{}'.format(action), args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1576, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 551, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 270, in handle
    for service_id in services_deployed:
TypeError: 'NoneType' object is not iterable

**Comment by dsuch** [comment]
Here is the error, the code that you are deploying is not formatted directly.

```
    self.log_input()
                   ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by dsuch** [comment]
Also, I understand that your are new to GitHub - please read more about opening tickets, how to format code correctly, how to provide error details etc. This will be useful to you and to everyone else working with you via GitHub.

**Comment by rashmireddy2719** [comment]
Thank you for your suggestion. Will definitely follow it. I am very new to zato and also to gituhub. Facing many issues with it.

**Comment by dsuch** [comment]
I will be happy to help you out with Zato and if it is more about usage than actual issues that I recommend to use the forum over at https://forum.zato.io which will let other members of the community to assist you.

As for GitHub and Open-Source, I suggest to search for blog posts or articles under keywords such as "How to participate in GitHub", "How to contribute to open-source projects" and similar.

You just need to understand that other people mostly help you out in their free time and in turn they expect for you to be prepared to act accordingly, that is, by valuing highly that random people across the Internet spend their time with you.
