### ISSUE TITLE
Exception in SFTP ping

### ISSUE THREAD

**Issue by hanif40** [zatosource/zato#1100]
HI!
this error occurs when pinging the docker version, I couldn't find a solution..

Could not ping SFTP connection, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 605, in id_only_service
    result = req.zato.client.invoke(service, request)
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 6fad8fd713a79cc11edbc963
Details: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 690, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 511, in set_response_data
    response = response.getvalue(serialize=kwargs['serialize'])
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 473, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 421, in _getvalue
    raise ZatoException(self.zato_cid, msg)
zato.common.ZatoException: <ZatoException at 0x7f85971f2828 cid:`6fad8fd713a79cc11edbc963`, msg:`Expected elem:`info` not found in item:`{'info': ''}``>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 792, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 768, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 707, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/generic/connection.py", line 242, in handle
    ping_func(self.request.input.id)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/subprocess_/sftp.py", line 51, in ping_sftp
    return self.ping(*args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 171, in ping
    'id': id
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 200, in invoke_connector
    raise Exception(response.text)
Exception: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/base.py", line 447, in on_definition_ping
    self.connections[msg.id].ping()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/sftp.py", line 241, in ping
    return self.execute('ping-{}'.format(_utcnow().isoformat()), self.ping_command)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/sftp.py", line 212, in execute
    self.encode_out(out)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/sftp.py", line 219, in encode_out
    out.command = [elem.decode('utf8') for elem in out.command[:]]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/base.py", line 356, in on_wsgi_request
    response = self.handle_http_request(environ['PATH_INFO'], data)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/base.py", line 319, in handle_http_request
    return handler(msg)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/sftp.py", line 257, in _on_OUTGOING_SFTP_PING
    return super(SFTPConnectionContainer, self).on_definition_ping(msg)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/base.py", line 449, in on_definition_ping
    return Response(_http_503, str(e.message), 'text/plain')
AttributeError: 'TypeError' object has no attribute 'message'

**Comment by dsuch** [comment]
Hello @hanif40,

I have a request - please use the backtiks (```) for proper code formatting in GitHub when you post any code, tracebacks etc. This makes it easy to read it all. Otherwise, they are simply unreadable - just have a look at the message that you posted.

Also, in your Zato environment, there will be a file called sftp.log - it may have more information, can you please check it?

Thanks.

**Comment by hanif40** [comment]
Hi!
I attach the files

**Comment by dsuch** [comment]
I have pushed a commit to deal with it - can you please install the latest updates?

https://zato.io/docs/admin/guide/install/update.html

Thanks.

**Comment by hanif40** [comment]
now I try it and let you know!

**Comment by hanif40** [comment]
```File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/sftp.py", line 234

    def connect(self):

      ^

SyntaxError: invalid syntax

`, kw:`{'async': True}```

**Comment by dsuch** [comment]
Please try again now.

**Comment by hanif40** [comment]
Of course! try again, thank you

**Comment by hanif40** [comment]
Now it works correctly, but, some operations of this link fail https://zato.io/blog/posts/sftp.html  some operations of this link  https://zato.io/blog/posts/sftp.html fail with the same error:

        #conn.create_directory('./upload/file.txt') good
        #conn.upload('/opt/share/pepe.txt', '/upload/pepe.txt') good
        #conn.download('/upload/pepe.txt', '/opt/share/') good
        #conn.create_directory('/upload/House') good
        #out = conn.read('./upload') error
        #out = conn.read('./upload/') error
        #out = conn.read('/upload/') error
        #out = conn.read('/upload') error
        # conn.delete_directory('/upload/House') error
        #data = 'My data'
        #conn.write(data, './upload/pepe.txt') error
        my_script = 'ls /upload'
        conn.execute(my_script)  TypeError: '>' not supported between instances of 'str' and 'int'


```Could not invoke the service. name:`con-rsa.servicio`, cluster_id:`1`, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/service.py", line 555, in invoke
    response = req.zato.client.invoke(name, **input_dict)
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 1da09b1c501ed98cff8b314b
Details: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 792, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 768, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/server2/work/hot-deploy/current/con_rsa.py", line 12, in handle
    conn.upload('/opt/share/pepe.txt', '/upload/')
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 610, in upload
    self._overwrite_if_needed(remote_path, overwrite, log_level)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 595, in _overwrite_if_needed
    info = self.get_info(remote_path, log_level, raise_on_error=False)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 419, in get_info
    out = self._get_info(remote_path, log_level, raise_on_error=raise_on_error)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 413, in _get_info
    out = self._parse_ls_output(out.stdout) # type: List[SFTPInfo]
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 399, in _parse_ls_output
    parsed = self._parse_ls_line(line)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 345, in _parse_ls_line
    name = line[1].strip()
IndexError: list index out of range´´´

**Comment by dsuch** [comment]
Please reformat your code and tracebacks. Also, please upload the SFTP log files.

**Comment by hanif40** [comment]
append sftp.log and supervisord.log

[logs.zip](https://github.com/zatosource/zato/files/5600321/logs.zip)

**Comment by hanif40** [comment]
I realized that if I run the command like this it works but when I have nothing inside the folder, examples:

items = conn.list('/upload/folder-empty') no error but is empty

items = conn.list('/upload/folder-full') error is not empty  IndexError: list index out of range

**Comment by dsuch** [comment]
Once more, I ask you to format your code and tracebacks correctly - do you know how to do it?

**Comment by hanif40** [comment]
Sorry!
 before I attach the logs, do you need anything else?
when I execute the read method I see that it takes a file but breaks when wanting to execute line 245 of sftp.py

**Comment by hanif40** [comment]
sorry again , line 347 of de sftp.py

**Comment by dsuch** [comment]
Can you please install the latest updates and try again? Thank you.

https://zato.io/docs/admin/guide/install/update.html

**Comment by hanif40** [comment]
ok!
try this!

**Comment by hanif40** [comment]
Excellent, I tried the methods that failed and now everything is correct.
thank you
