### ISSUE TITLE
Ubuntu version Exception in SFTP ping

### ISSUE THREAD

**Issue by hanif40** [zatosource/zato#1107]
Hi! as in the docker version the same thing happens here, i use Zato 3.1+rev.c0bbca64c-py3.6.8

Exception in SFTP ping #1100 (solved)

```
Could not ping SFTP connection, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 605, in id_only_service
    result = req.zato.client.invoke(service, request)
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: cb0fa57f5c476717c2e4bca9
Details: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 690, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 511, in set_response_data
    response = response.getvalue(serialize=kwargs['serialize'])
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 473, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 421, in _getvalue
    raise ZatoException(self.zato_cid, msg)
zato.common.ZatoException: <ZatoException at 0x7f648c01b8e8 cid:`cb0fa57f5c476717c2e4bca9`, msg:`Expected elem:`info` not found in item:`{'info': ''}``>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 792, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 768, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 707, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 382, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/urllib3/util/url.py", line 199, in parse_url
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: 127.0.0.1:None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/generic/connection.py", line 242, in handle
    ping_func(self.request.input.id)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/subprocess_/sftp.py", line 51, in ping_sftp
    return self.ping(*args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 171, in ping
    'id': id
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 196, in invoke_connector
    response = post(address, data=dumps(msg), auth=self.get_credentials())
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: 127.0.0.1:None
´´´

**Comment by dsuch** [comment]
Could you please have a look at this ticket and check if the traceback is formatted correctly? I mean, please just open it in your browser, is it as it should be?

**Comment by hanif40** [comment]
![image](https://user-images.githubusercontent.com/21147328/102027234-8a949180-3d81-11eb-83a1-c7d4e960a8b6.png)

**Comment by hanif40** [comment]
Excuse me, I know that he always repeats that to me but I see it well, it is not my intention to generate discomfort
PS: I use a translator in case there is any misunderstanding jaja or haha

**Comment by dsuch** [comment]
Thanks, as you can see, it is not formatted correctly and I cannot understand what it says.

I ask you to create a test repository in your account and just test out how to use GitHub Markdown, how to format code, tracebacks, how to make things bold, underlined etc.

Otherwise, it will make communication difficult and I would like to avoid it. Thanks.

**Comment by dsuch** [comment]
No worries, everything is good - just please try to send code and open some tickets in a test repository - in this way you will get some practice first.

This is simply how GitHub works, when you paste code it appears to be formatted correctly. But then for readers it is difficult to read it unless you use ``` characters.

**Comment by hanif40** [comment]
Dariusz, there I could make it work using docker sources, replace /opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/outgoing/sftp.py
and it works perfect.

**Comment by DimShadoWWW** [comment]
Hola, @hanif40 
El problema con el formateado del código es que después de las primeras tres comillas izquierdas (```), al comenzar el código,  debes dar ENTER para que cambie de línea. El tener el código bien formateado ayuda a ver mejor la información. Gracias

**Comment by hanif40** [comment]
gracias,  lo tengo en cuenta, pasa que yo lo veía bien no se que como lo ven del otro lado o como lo ven.ç

**Comment by DimShadoWWW** [comment]
Por favor, puedes editar el primer mensaje y adicionar el cambio de línea al final de las primeras tres comillas izquierdas (```)?
![image](https://user-images.githubusercontent.com/25516/102033315-22e24480-3d89-11eb-892a-ef3b0a9d28f9.png)

Luego de eso, puedes brindarnos información de qué pasos seguir para reproducir tu problema?

Así nos es más fácil saber qué sucedió y cómo ayudarte.

**Comment by hanif40** [comment]
listo, lo que hice al final es reemplazar este archivo /opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/outgoing/sftp.py  pasa que lo necesitaba de urgencia para mañana.

**Comment by DimShadoWWW** [comment]
Por favor, puedes darme más información sobre:
- ¿En qué condiciones te sucede este nuevo error?
- ¿Cómo estás ejecutando Zato?
- ¿Tienes [actualizado](https://zato.io/docs/admin/guide/install/update.html) Zato desde Github?

gracias

**Comment by hanif40** [comment]
claro,
1) hice la instalación en un ubuntu server 18.04 lts , solo para zato (instalación limpia) 
2)Instale redis 
3)instale postgres
4) seguí los pasos de https://zato.io/docs/admin/guide/install/py3/ubuntu.html
5)zato quickstart create --odb_host localhost --odb_port 5432 --odb_user zato --odb_db_name zato --odb_password '' --kvdb_password '' /opt/zato/env/qs-1/ postgresql
6) por las dudas  en su momento hice también https://zato.io/docs/admin/guide/install/update.html

te comento que con la versión de ubuntu 20.04 LTS hay problemas de librerías de python y por eso desistí y fui con la versión 18.04

algo q me llamo la atención es instalar pero desde solo los source pero no tuve suerte e hice la instalación como comento mas arriba.

**Comment by DimShadoWWW** [comment]
Muchas gracias,

Podrías los revisar el directorio /tmp/ y buscar archivos en los que el nombre termina en "-zato-start-server.txt" y adicionarlos acá junto al archivo  /opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/outgoing/sftp.py? 

muchas gracias

**Comment by hanif40** [comment]
[zato.zip](https://github.com/zatosource/zato/files/5686201/zato.zip)

**Comment by hanif40** [comment]
te hago una consulta, se usa mucho lo del sftp? la verdad que hace tiempo veíamos ese error pero al no tener soporte por ahora no lo reportamos hasta que me comento Dariusz que le habra un issue por acá, me llamo la atencion no encontrar reclamos.

**Comment by DimShadoWWW** [comment]
Muchas gracias por la información, sin reportes no podríamos saber cómo está funcionando, además de nuestras pruebas.

Lo revisaremos y te avisaremos por acá.

**Comment by dsuch** [comment]
I cannot reproduce this situation, everything works correctly in my tests.

The next time if it happens again, I ask you to:

* Delete all log files from /tmp
* Start the environment
* Make a .zip archive of all the files from /tmp
* Make a .zip archive of all the log files for each server in its directory
* Send all the .zip archives here

Simply, first delete all log files and then send them all here as a .zip.

**Comment by fenist19** [comment]
@dsuch  I saw this problem. Please try next steps.

1. Create new zato cluster without sftp. 
2. Create new sftp out connetion.
3. Call ping or call out connetion in service.
4. Sftp raise this error.
 
 But if you restart server  sftp conntions must work correctly.
 This problmem exists because zato server register port  in server start script , one or more sftp connetions exists.
 This problem also with first ibmmq out conentions.

**Comment by dsuch** [comment]
Thanks @fenist19 - just to confirm it, this happens only with a completely new cluster and never occurs again later on? Is that reproducible on each new cluster each time?

**Comment by fenist19** [comment]
1. start server without sftp conn. (main target - no sftp out conn in database)
2. create new sftp conn
3. call this connetion.

The problem is related with server start process. server reserved ports for sftp and ibmmq only if one ore more out connetions exists.

**Comment by dsuch** [comment]
I am not really sure if I understand it correctly - do you mean that there needs to be one another IBM MQ or SFTP connection first? And the second one will fail?

First you said that a new cluster is needed so it is not clear to me if a new cluster is needed or not.

**Comment by fenist19** [comment]
@dsuch 
Error will raised if server start without sftp connections, and you create new sftp connections. 
Until reboot server  all new sftp connections will raise error.  After restart server all connections will works.

If on start of server one or more sftp connections exists , then all connections must work corectly.

**Comment by hanif40** [comment]
HI!
it fails again, but if I run outside tho command, work good.   

/usr/bin/sftp -B 32768 -l 80000 -p -P 1022 -i /zato/integrador-ecommerce/share/starmeup/id_rsa_generico  foo@172.16.45.54

```
Caught an exception, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/outgoing/sftp.py", line 144, in command_shell_action
    'log_level': req.POST['log_level'],
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 430c6a5b9c763c2c2661682b
Details: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 792, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 768, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/outgoing/sftp.py", line 40, in handle
    response = conn.execute(self.request.input.data, self.request.input.log_level)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 224, in execute
    return self._execute(data, log_level, raise_on_error)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/sftp.py", line 212, in _execute
    raise ValueError(response)
ValueError: {'is_ok': False, 'cid': None, 'command': None, 'command_no': 2, 'stdout': None, 'stderr': None, 'details': 'Traceback (most recent call last):\n  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/sftp.py", line 197, in execute\n    result = self.command(*args)\n  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 1427, in __call__\n    return RunningCommand(cmd, call_args, stdin, stdout, stderr)\n  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 774, in __init__\n    self.wait()\n  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 792, in wait\n    self.handle_command_exit_code(exit_code)\n  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code\n    raise exc\nsh.ErrorReturnCode_255: \n\n  RAN: /usr/bin/sftp -B 32768 -l 80000 -p -P 1022 -i /zato/integrador-ecommerce/share/starmeup/id_rsa_generico -b /tmp/tmp_kdh1rnk-zato-sftp.txt foo@172.16.45.54\n\n  STDOUT:\n\n\n  STDERR:\nHost key verification failed.\r\nConnection closed\r\n\n', 'response_time': '0:00:00.100114'
```

**Comment by hanif40** [comment]
this configuration

![image](https://user-images.githubusercontent.com/21147328/103061671-d5d15000-458a-11eb-8696-e67ff0c4110c.png)

**Comment by dsuch** [comment]
Please check the error message, it says "STDERR:\nHost key verification failed.\r\nConnection closed" - this is an issue with SSH configuration.

**Comment by hanif40** [comment]
the confusing thing is that it works without zato

![image](https://user-images.githubusercontent.com/21147328/103061949-82133680-458b-11eb-9b08-2d95df878f25.png)

**Comment by dsuch** [comment]
Yes, I agree, but without access to that system, there is not much really that I can do. Have you tried to look up that message on the Internet? What do people say about it?

**Comment by hanif40** [comment]
![image](https://user-images.githubusercontent.com/21147328/103062041-d74f4800-458b-11eb-96f1-320481686ca0.png)

**Comment by dsuch** [comment]
Also, one thing, you run this command as user root but Zato, I assume, runs as user zato. Is that not the difference?

**Comment by dsuch** [comment]
I am not sure what you mean by "run out of zato before"?

**Comment by hanif40** [comment]
run through the console the connection to sftp first and then from zato the command ls worked.
but I'm going to check the root user too, thanks

**Comment by dsuch** [comment]
I have found the root cause of this situation.

This is related to the fact that you have a server with more than one subprocess, I believe it is two subprocesses that you have. This is fine as long as you do not use SFTP or IBM MQ connections because they are also based on subprocesses and that may cause conflicts that you have seen.

This means that I recommend, instead of using a single process with two processes, to start two servers, each with one process.

To reduce the number of subprocesses used, find file server.conf (e.g. ~/env/qs-1/server/config/repo/server.conf) and make sure that it reads as below:

```ini
[main]
...
gunicorn_workers=1
```

Next, restart  the server.

You probably have it set to 2 instead of 1 (and this is what Docker uses by default in v3.1) so when you change it to 1, the situation will be resolved.

The documentation will be updated accordingly too. Note also that in Zato 3.2 the quickstart Dockerfile already contains "gunicorn_workers=1" so you need to change it only in version 3.1.

This also explains why I was not able to reproduce the situation - in my environments, that value was already set to 1.

**Comment by dsuch** [comment]
Also, let me add that in soon-to-be-released Zato 3.2 it will be possible to use SFTP with multiple subproceses - this is already done. However, for Zato 3.1, this will have to be one subprocess.

This also means that I suggest that you start to use Zato 3.2 as soon as possible.
