### ISSUE TITLE
Error on "zato create user"

### ISSUE THREAD

**Issue by x011** [zatosource/zato#1120]
```
[zato@static ~]$ zato create user /opt/zato/lob/web-admin --verbose
File "/opt/zato/current/bin/zato", line 16, in <module>
    sys.exit(main())
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/zato_command.py", line 569, in main
    return run_command(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 394, in run_command
    return instance.run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 761, in run
    self.before_execute(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/web_admin_auth.py", line 80, in before_execute
    self._prepare(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/web_admin_auth.py", line 29, in _prepare
    config = loads(open(os.path.join(base_dir, '.', 'config/repo/web-admin.conf')).read())
FileNotFoundError: [Errno 2] No such file or directory: '/opt/zato/lob/web-admin/./config/repo/web-admin.conf'

```

seems that "zato create user"  adds a dot (relative path) after the specific path '/opt/zato/lob/web-admin/HERE-->./config/repo/web-admin.conf'

**Comment by dsuch** [comment]
Hi @x011,

the dot looks to be harmless although you are right that it does not need to be displayed. Please consider the case below:

```bash
$ cd /./tmp/./
```

This is the same as plain "cd /tmp" despite the dots. That makes me wonder, does the /opt/zato/lob directory truly exist?

Regards.

**Comment by x011** [comment]
Yes, it does exists:

```
[root@static lob]# pwd
/opt/zato/lob
```

**Comment by dsuch** [comment]
Which part of this path does not exist in this case? '/opt/zato/lob/web-admin/./config/repo/web-admin.conf'

**Comment by x011** [comment]
I'm following the example provided on  [https://zato.io/docs/web-admin/security.html](https://zato.io/docs/web-admin/security.html)
As a first time ZATO user , I've been founding to many errors and probably won't continue using ZATO. 
Thank you anyway.
