### ISSUE TITLE
ModuleNotFoundError: No module named 'dacite'

### ISSUE THREAD

**Issue by bbqi** [zatosource/zato#1129]
Error:
```
2021-02-15 03:21:02,878 DEBG 'server1' stderr output:
Stderr received from program `/opt/zato/3.2.0/code/bin/py -m zato.server.main /opt/zato/env/qs-1/server1 fg=TrueZATO_ZATO_ZATOsync_internal=FalseZATO_ZATO_ZATOsecret_key=ZATO_ZATO_ZATOstderr_path=None  2> /tmp/tmple5svirr-zato-start-server.txt` e:`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/main.py", line 65, in <module>
    from zato.server.base.parallel import ParallelServer
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 49, in <module>
    from zato.server.base.worker import WorkerStore
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 55, in <module>
    from zato.common.model.amqp_ import AMQPConnectorConfig
  File "/opt/zato/3.2.0/code/zato-common/src/zato/common/model/amqp_.py", line 13, in <module>
    from zato.common.typing_ import dataclass, from_dict
  File "/opt/zato/3.2.0/code/zato-common/src/zato/common/typing_.py", line 17, in <module>
    from dacite import from_dict
ModuleNotFoundError: No module named 'dacite'
`, kw:`{'async_': False}`

2021-02-15 03:21:03,050 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 140060865494128 for <Subprocess at 140060864824224 with name server1 in state RUNNING> (stdout)>
2021-02-15 03:21:03,052 DEBG fd 11 closed, stopped monitoring <POutputDispatcher at 140060865494464 for <Subprocess at 140060864824224 with name server1 in state RUNNING> (stderr)>
2021-02-15 03:21:03,055 INFO exited: server1 (exit status 18; not expected)
2021-02-15 03:21:03,057 DEBG received SIGCHLD indicating a child quit
```

Used:
`docker run -it --rm -p 22022:22 -p 8183:8183 -p 11223:11223 --name zato registry.gitlab.com/zatosource/docker-registry/quickstart:3.2`

**Comment by dsuch** [comment]
Thanks for opening the ticket, this will be corrected soon. I will let you know.

**Comment by DimShadoWWW** [comment]
Hello @bbqi ,

Please, can you pull an update of the Docker image and try again? thanks

**Comment by bbqi** [comment]
When Docker is started, it is automatically updated. 
Updating ce34032..ec3efde

```
remote: Enumerating objects: 3658, done.
remote: Counting objects: 100% (2174/2174), done.
remote: Compressing objects: 100% (618/618), done.
remote: Total 1401 (delta 849), reused 1313 (delta 777), pack-reused 0
Receiving objects: 100% (1401/1401), 204.43 KiB | 156.00 KiB/s, done.
Resolving deltas: 100% (849/849), completed with 237 local objects.
From https://github.com/zatosource/zato
   ce34032..ec3efde  support/3.2                            -> origin/support/3.2
 * [new branch]      dependabot/pip/code/cryptography-3.3.2 -> origin/dependabot/pip/code/cryptography-3.3.2
 * [new branch]      dependabot/pip/code/httplib2-0.19.0    -> origin/dependabot/pip/code/httplib2-0.19.0
 + cf2d029...a79bd9e dependabot/pip/code/lxml-4.6.2         -> origin/dependabot/pip/code/lxml-4.6.2  (forced update)
 * [new branch]      dsuch-f-gh1122-mq-logs                 -> origin/dsuch-f-gh1122-mq-logs
 * [new branch]      dsuch-f-gh678-memtrack                 -> origin/dsuch-f-gh678-memtrack
   082c6b8..7ba52d5  main                                   -> origin/main
   c0bbca6..c143e37  support/3.1                            -> origin/support/3.1
   c8f3c9a..42e0c16  support/3.1-v2                         -> origin/support/3.1-v2
Updating ce34032..ec3efde
Fast-forward
...
```

**Comment by DimShadoWWW** [comment]
Than you @bbqi ,

And the container worked without issues?

**Comment by dsuch** [comment]
I believe everything is fine now and the ticket can be closed. Thanks again for opening it, @bbqi.
