### ISSUE TITLE
Hot-deployment Error (VS Code)

### ISSUE THREAD

**Issue by AndreiPanasuk** [zatosource/zato#1138]
I got an error after hot deployment from VS Code :
````log
2021-03-13 18:14:44,685 - WARNING - 12477:DummyThread-32 - zato.ide-deploy.create:0 - Could not invoke zato.service.upload-package, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/ide_deploy/__init__.py", line 43, in handle
    self.invoke('zato.service.upload-package', dumps(new_payload), data_format=DATA_FORMAT.JSON)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 826, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 804, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 635, in update_handle
    payload = payload_from_request(server.json_parser, cid, raw_request, data_format, transport, channel_item)
  File "/opt/zato/3.2.0/code/zato-common/src/zato/common/util/api.py", line 484, in payload_from_request
    payload = json_parser.parse(request)
TypeError: parse(): incompatible function arguments. The following argument types are supported:
    1. (self: csimdjson.Parser, s: buffer, recursive: bool = False) -> object
````
The error can be cured by adding conversion to bytes before parsing request (module 
**code/zato-common/src/zato/common/util/api.py** line **479**)
````python
                    if isinstance(request, str):
                        request = bytes(request, 'utf-8')
````

**Comment by dsuch** [comment]
Per ticket #1137 - I refuse to look at tickets that do not even say what your Zato version is.

**Comment by AndreiPanasuk** [comment]
OS: Linux x64 5.8.0-44-generic snap: Ubuntu 20.04 (WMware VM)
Zato: ver. 3.2+rev.d054ba7-py3.8.5 ( install a Zato package with tutorial: https://zato.io/docs/tutorial/01.html)
VS Code: Version: 1.54.2
Node.js: 12.18.3
Zato for Visual Studio Code v1.0.8
