### ISSUE TITLE
Error while creating the outgoing Zero MQ connection

### ISSUE THREAD

**Issue by AndreiPanasuk** [zatosource/zato#1139]
Hi,

I got an Error while creating from Web admin the outgoing Zero MQ connection (Socket type:  Push, Socket method: Connect)

OS: Ubuntu 20.04 (VMware VM)
Zato 3.2+rev.d054ba7-py3.8.5 ( install a Zato package with tutorial: https://zato.io/docs/tutorial/01.html)

````log
2021-03-15 10:26:51,264 - ERROR - 3831:DummyThread-28 - zato:0 - Could not handle broker message: (OUTGOING_ZMQ_CREATE:100808) `Bunch(action='100808', address='tcp://192.168.124.130:112234', cluster_id=1, id=1, is_active=True, msg_source='', msg_type='0002', name='psimReq', parallel_server=None, socket_method='connect', socket_type='PUSH')`, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/lib/python3.8/site-packages/bunch/__init__.py", line 123, in __getattr__
    return object.__getattribute__(self, k)
AttributeError: 'Bunch' object has no attribute 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/lib/python3.8/site-packages/bunch/__init__.py", line 126, in __getattr__
    return self[k]
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-broker/src/zato/broker/__init__.py", line 52, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 2475, in on_broker_msg_OUTGOING_ZMQ_CREATE
    self.zmq_out_api.create(msg.name, msg)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 330, in create
    self._create(name, config, on_message_callback, auth_func, channels, outconns, needs_start)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 319, in _create
    connector = self.connector_class(
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 97, in __init__
    self.service = config.service_name
  File "/opt/zato/3.2.0/code/lib/python3.8/site-packages/bunch/__init__.py", line 128, in __getattr__
    raise AttributeError(k)
AttributeError: service_name
````

**Comment by dsuch** [comment]
Hello,

Zato 3.2 has a new, changed tutorial. Please find it here:

https://zato.io/docs/3.2/tutorial/01.html

Regards.

**Comment by AndreiPanasuk** [comment]
Thank, didn't find any difference between
https://zato.io/docs/tutorial/01.html
and 
https://zato.io/docs/3.2/tutorial/01.html

**Comment by dsuch** [comment]
Ah, yes, you are right - I mistakenly though the default one was for 3.1. But in that case, can you tell me where you found references to ZeroMQ?

**Comment by AndreiPanasuk** [comment]
google search for "python ESB"
