### ISSUE TITLE
Ubuntu and Docker Tutorial builds fail on quickstart create

### ISSUE THREAD

**Issue by Stew-rt** [zatosource/zato#1140]
Tested both Docker and Ubuntu (20.04.2 LTS) native builds, and both have failures on `zato quickstart create` as followed in the tutoiral.

```
zato@oh:~$ zato quickstart create ~/env/qs-1 sqlite localhost 6379 --verbose
[1/8] Certificate authority created
[2/8] ODB schema created
[3/8] ODB initial data created
[4/8] server1 created
File "/opt/zato/current/bin/zato", line 16, in <module>
    sys.exit(main())
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/zato_command.py", line 569, in main
    return run_command(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 394, in run_command
    return instance.run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 769, in run
    return_code = self.execute(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/quickstart.py", line 408, in execute
    create_lb.Create(create_lb_args).execute(create_lb_args, True, servers_port, False)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/create_lb.py", line 130, in execute
    open(os.path.join(repo_dir, 'lb-agent.conf'), 'w').write(config) # noqa
NameError: name 'config' is not defined
```

Docker:
....
```
[4/8] server1 created
NameError: ("name 'config' is not defined",) (Hint: re-run with --verbose for full traceback)
```
...

**Comment by dsuch** [comment]
My apologies for that - can you, please, install the latest updates and retry it?

https://zato.io/docs/3.2/admin/guide/install/update.html

**Comment by Stew-rt** [comment]
Wonderful. That was quick!

**Comment by dsuch** [comment]
Thanks again for opening the ticket.
