### ISSUE TITLE
zato 3.2.0 pub/sub problem

### ISSUE THREAD

**Issue by libigfat** [zatosource/zato#1144]
Hello
I have a problem, I created a topic named /food/new, and created an endpoint of type rest, and created a subscription
<img width="942" alt="微信图片_20210325142004" src="https://user-images.githubusercontent.com/40198012/112428224-cf16cc80-8d75-11eb-8fff-ce23f32f236d.png">
<img width="937" alt="微信截图_20210325142240" src="https://user-images.githubusercontent.com/40198012/112428254-d9d16180-8d75-11eb-9837-07716e3ccc2b.png">
<img width="946" alt="微信截图_20210325142319" src="https://user-images.githubusercontent.com/40198012/112428266-de961580-8d75-11eb-8770-398c839318cf.png">
when I use the REST API ,POST method to access    /zato/pubsub/topic//food/new?sub_key=zpsk.rest.d166d7      to try to get messages from queues, it returns the error
```
2021-03-25 14:16:07,689 - [1;31mERROR[0m - 44387:DummyThread-33 - zato.server.service:0 - Can't run hook `<bound method AdminService.after_handle of <zato.server.service.internal.pubsub.endpoint.GetDeliveryMessages object at 0x7fb4ff171910>>`, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 181, in call_hook_no_service
    hook()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/__init__.py", line 132, in after_handle
    self.name, replace_private_key(get_response_value(self.response)), self.cid)
  File "/opt/zato/3.2.0/code/zato-common/src/zato/common/util/api.py", line 1649, in get_response_value
    return (response.payload.getvalue() if hasattr(response.payload, 'getvalue') else response.payload) or ''
  File "src/zato/cy/reqresp/payload.py", line 201, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
  File "src/zato/cy/reqresp/payload.py", line 229, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
  File "src/zato/cy/simpleio.py", line 2187, in zato.simpleio.CySimpleIO.get_output
  File "src/zato/cy/simpleio.py", line 2110, in zato.simpleio.CySimpleIO._convert_to_dicts
  File "src/zato/cy/simpleio.py", line 2028, in _yield_data_dicts
AttributeError: 'NoneType' object has no attribute 'get'

2021-03-25 14:16:07,691 - [1;31mERROR[0m - 44387:DummyThread-33 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`24d62342dcbfd57c3af832b3`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 809, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 756, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 630, in _invoke
    service.http_method_handlers[service.request.http.method](service)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 167, in handle_POST
    response = dumps(self._get_messages(endpoint_id))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 155, in _get_messages
    return self.pubsub.get_messages(self.request.input.topic_name, sub_key)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1748, in get_messages
    }, serialize=False).response
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1440, in invoke_service
    return self.server.invoke(name, msg, *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 916, in invoke
    *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1699, in invoke
    }, channel, None, needs_response=True, serialize=serialize)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1770, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 805, in update_handle
    raise resp_e
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 784, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 598, in set_response_data
    response = response.getvalue(serialize=False)
  File "src/zato/cy/reqresp/payload.py", line 201, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
  File "src/zato/cy/reqresp/payload.py", line 229, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
  File "src/zato/cy/simpleio.py", line 2187, in zato.simpleio.CySimpleIO.get_output
  File "src/zato/cy/simpleio.py", line 2110, in zato.simpleio.CySimpleIO._convert_to_dicts
  File "src/zato/cy/simpleio.py", line 2028, in _yield_data_dicts
AttributeError: 'NoneType' object has no attribute 'get'
```
I hope this can be answered, thank you very much!

**Comment by libigfat** [comment]
my zato version Zato 3.2+rev.a5b618f-py3.7.8

**Comment by dsuch** [comment]
Hello @libigfat - please have a look at the traceback that you posted, it is impossible to read it. Please format it correctly so that it displays just like in server logs. Thanks.

**Comment by libigfat** [comment]
When I add a rest subscription using web-admin, I get an error

**Comment by libigfat** [comment]
Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 582, in __call__
    response = self.req.zato.client.invoke(self.service_name, self.input_dict)
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/middleware.py", line 76, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(json_data.get('cid'), json_data.get('details')))
Exception: CID: 97e61bbfe2b88bedae4d86b9
Details: Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 753, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 635, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/service.py", line 374, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 887, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 863, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 753, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 635, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 554, in handle
    self.response.payload = self.invoke(sub_service, sub_request)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 887, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 863, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    wmq_ctx=kwargs.get('wmq_ctx'), channel_info=kwargs.get('channel_info'), channel_item=channel_item)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 1299, in update
    service._init(channel_type in _wsgi_channels)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/__init__.py", line 86, in _init
    super(AdminService, self)._init(is_http)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 585, in _init
    self.server.encrypt)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 228, in init
    parsed = sio.parse_input(self.payload or {}, data_format, extra=self.channel_params)
  File "src/zato/cy/simpleio.py", line 1976, in zato.simpleio.CySimpleIO.parse_input
  File "src/zato/cy/simpleio.py", line 1913, in zato.simpleio.CySimpleIO._parse_input_elem
ValueError: <class 'zato.server.service.internal.pubsub.subscription.SubscribeREST'>; No such input elem `is_internal` among `dict_keys(['cluster_id', 'endpoint_id', 'is_active', 'server_id', 'has_gd', 'endpoint_type', 'active_status', 'delivery_method', 'delivery_data_format', 'delivery_batch_size', 'wrap_one_msg_in_list', 'delivery_max_retry', 'delivery_err_should_block', 'wait_sock_err', 'wait_non_sock_err', 'out_amqp_id', 'amqp_exchange', 'amqp_routing_key', 'files_directory_list', 'ftp_directory_list', 'out_rest_http_soap_id', 'rest_delivery_endpoint', 'service_id', 'sms_twilio_from', 'sms_twilio_to_list', 'smtp_is_html', 'smtp_subject', 'smtp_from', 'smtp_to_list', 'smtp_body', 'out_soap_http_soap_id', 'soap_delivery_endpoint', 'out_http_method', 'sub_pattern_matched', 'topic_name'])` in `{'cluster_id': '1', 'endpoint_id': '4', 'is_active': 'on', 'server_id': '1', 'has_gd': None, 'endpoint_type': 'rest', 'active_status': None, 'delivery_method': 'pull', 'delivery_data_format': None, 'delivery_batch_size': '500', 'wrap_one_msg_in_list': 'on', 'delivery_max_retry': '123456789', 'delivery_err_should_block': None, 'wait_sock_err': '10', 'wait_non_sock_err': '3', 'out_amqp_id': None, 'amqp_exchange': None, 'amqp_routing_key': None, 'files_directory_list': None, 'ftp_directory_list': None, 'out_rest_http_soap_id': None, 'rest_delivery_endpoint': None, 'service_id': None, 'sms_twilio_from': None, 'sms_twilio_to_list': None, 'smtp_is_html': 'on', 'smtp_subject': None, 'smtp_from': None, 'smtp_to_list': None, 'smtp_body': None, 'out_soap_http_soap_id': None, 'soap_delivery_endpoint': None, 'out_http_method': 'POST', 'sub_pattern_matched': 'sub=/food/new', 'topic_name': '/food/new'}`

**Comment by libigfat** [comment]
When I use the rest interface to get the subscription message, I get an error

**Comment by libigfat** [comment]
2021-03-29 09:37:29,954 - [1;31mERROR[0m - 16602:DummyThread-55 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`2ac857b7e97fa87d3e0e29e`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    &emsp;&emsp;payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
  &emsp;&emsp;params_priority=channel_item.params_pri)
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
   &emsp;&emsp;raise e if isinstance(e, Exception) else Exception(e)
 &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 753, in update_handle
   &emsp;&emsp;self._invoke(service, channel)
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 627, in _invoke
    &emsp;&emsp;service.http_method_handlers[service.request.http.method](service)
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 155, in handle_POST
  &emsp;&emsp;response = dumps(self._get_messages(endpoint_id))
 &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 144, in _get_messages
    &emsp;&emsp;return self.pubsub.get_messages(self.request.input.topic_name, sub_key)
 &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1766, in get_messages
    &emsp;&emsp;}, serialize=False).response
 &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1452, in invoke_service
   &emsp;&emsp;return self.server.invoke(name, msg, *args, **kwargs)
 &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 916, in invoke
  &emsp;&emsp;*args, **kwargs)
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1693, in invoke
   &emsp;&emsp;}, channel, None, needs_response=True, serialize=serialize)
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1764, in on_message_invoke_service
   &emsp;&emsp;environ=msg.get('environ'))
 &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 802, in update_handle
  &emsp;&emsp;raise resp_e
 &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 781, in update_handle
  &emsp;&emsp;response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  &emsp;File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 597, in set_response_data
    &emsp;&emsp;response = response.getvalue(serialize=kwargs.get('serialize'))
  &emsp;File "src/zato/cy/reqresp/payload.py", line 201, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
  &emsp;File "src/zato/cy/reqresp/payload.py", line 229, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
 &emsp;File "src/zato/cy/simpleio.py", line 2187, in zato.simpleio.CySimpleIO.get_output
 &emsp;File "src/zato/cy/simpleio.py", line 2110, in zato.simpleio.CySimpleIO._convert_to_dicts
  &emsp;File "src/zato/cy/simpleio.py", line 2028, in _yield_data_dicts
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by libigfat** [comment]
The logs are copied directly, I didn't pay attention to the format, sorry

**Comment by dsuch** [comment]
Hello @libigfat - if you have something new to report, please open a new ticket, providing all the details for it.

I ask you to do pay attention to formatting. In particular, wrap all the text in ``` markers. Please read more about how to format code in GitHub.

Please also delete the latest comments, the ones unrelated to the situation that you originally reported.

**Comment by libigfat** [comment]
Hello @dsuch I have formatted the log. :)

**Comment by dsuch** [comment]
Thanks, I can reproduce it now. I will work on it soon.

**Comment by dsuch** [comment]
This is done, can you please install the latest updates and try it? Thank you.

https://zato.io/docs/admin/guide/install/update.html

**Comment by libigfat** [comment]
Hello @dsuch After I published a message, I didn't report an error by using the interface, but it was always an empty list and I couldn't receive the published message.
<img width="942" alt="1" src="https://user-images.githubusercontent.com/40198012/113265979-4e247b80-9307-11eb-8db1-c164c4f17dce.png">
<img width="917" alt="2" src="https://user-images.githubusercontent.com/40198012/113265995-52e92f80-9307-11eb-9dbe-9ea3a66b958b.png">
<img width="949" alt="3" src="https://user-images.githubusercontent.com/40198012/113265996-541a5c80-9307-11eb-811e-a34287db027f.png">
<img width="949" alt="4" src="https://user-images.githubusercontent.com/40198012/113265999-54b2f300-9307-11eb-89ff-d92541a22092.png">
<img width="953" alt="5" src="https://user-images.githubusercontent.com/40198012/113266002-554b8980-9307-11eb-96c7-7295b5937fab.png">
<img width="649" alt="6" src="https://user-images.githubusercontent.com/40198012/113266007-55e42000-9307-11eb-857a-fb92d3ec8f12.png">

**Comment by dsuch** [comment]
Thanks. What if the message that you publish has guaranteed delivery (GD) enabled?

**Comment by libigfat** [comment]
I tested again using GD mode and still can't get new messages. And the same operation is fine under version 3.1, it can get the new message correctly. I have a feeling that there is something wrong.

**Comment by dsuch** [comment]
I cannot reproduce it but there may be a way for to progress with it - please contact me your using your business email on dsuch.crm.support at zato.io to discuss the details. Thank you.
