### ISSUE TITLE
`No such input elem 'is_internal'` exception while subscribing via REST API.

### ISSUE THREAD

**Issue by Byloth** [zatosource/zato#1162]
Hi.  
I'm experiencing this problem while following the official documentation and trying to implement some sort of Pub/Sub behaviour.

---

When I execute this command from my console:

```bash
curl -XPOST http://pubsub:pubsub00@localhost:11223/zato/pubsub/subscribe/topic//customer/new
```

... I get this error traceback in Zato console:

```log
2021-06-25 08:45:28,949 DEBG 'server1' stdout output:
2021-06-25 08:45:28,948 - ERROR - 141:DummyThread-116 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`9150ad92e8235ab457cdae05`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 381, in dispatch
    response = self.request_handler.handle(cid, url_match, channel_item, wsgi_environ,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 684, in handle
    response = service.update_handle(self._set_response_data, service, raw_request,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 748, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 622, in _invoke
    service.http_method_handlers[service.request.http.method](service)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 198, in handle_POST
    response = self.invoke('zato.pubsub.subscription.subscribe-rest', {
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 885, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 868, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 689, in update_handle
    service.update(service, channel, server, broker_client,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 1297, in update
    service._init(channel_type in _wsgi_channels)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/__init__.py", line 86, in _init
    super(AdminService, self)._init(is_http)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 579, in _init
    self.request.init(True, self.cid, self._sio, self.data_format, self.transport, self.wsgi_environ,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 230, in init
    parsed = sio.parse_input(self.payload or {}, data_format, extra=self.channel_params)
  File "src/zato/cy/simpleio.py", line 1977, in zato.simpleio.CySimpleIO.parse_input
  File "src/zato/cy/simpleio.py", line 1914, in zato.simpleio.CySimpleIO._parse_input_elem
ValueError: <class 'zato.server.service.internal.pubsub.subscription.SubscribeREST'>; No such input elem `is_internal` among `dict_keys(['topic_name', 'endpoint_id', 'delivery_batch_size', 'delivery_method', 'server_id'])` in `{'topic_name': '/customer/new', 'endpoint_id': 6, 'delivery_batch_size': 500, 'delivery_method': 'pull', 'server_id': 2}`
```

---

It's probably my fault, but... I can't find anything online about this.  

What am I doing wrong?

**Comment by dsuch** [comment]
Hello Matteo,

can you please send the output from this command?

$ zato --version

Thanks.

**Comment by Byloth** [comment]
Hi, @dsuch! 🙃

I'm using Docker with `registry.gitlab.com/zatosource/docker-registry/quickstart:3.2` image.

**Comment by dsuch** [comment]
This is good but I would like to confirm the version nevertheless. There are several options:

* Log in via SSH and run the command
* Check in the container's logs - there will be an entry such as "INFO - ... - Starting Zato 3.2+rev.8a1cd30a4-py3.6.9-ubuntu.18.04-bionic"
* Look the version up in web-admin at http://localhost:8183. Press Ctrl-U to get the HTML source code of a page and you will have this tag ``<meta name="generator" content="Zato 3.2+rev.8a1cd30a4-py3.6.9-ubuntu.18.04-bionic" />``

**Comment by Byloth** [comment]
Oh, ok... Thank you!

Here you are: `Zato 3.2+rev.db703832-py3.8.5-ubuntu.20.04-focal`

**Comment by dsuch** [comment]
Great, thanks.

This confirms that you are using the latest version, including all the updates. In this case, I will investigate it further on my end.

I will let you know as soon as possible although I cannot guarantee that it will be today.

Thanks for your understanding.

**Comment by dsuch** [comment]
Hello again,

I have just pushed a commit to deal with this situation.

The Docker image on GitLab is being rebuilt. Please wait until it is done or create a new container. When you create a new container, it automatically installs latest updates and this will include the one that I pushed.

Thank you.

**Comment by dsuch** [comment]
Good day, Mateo,

can you please tell me if that answers your question or if you need anything else?

Thanks.

**Comment by dsuch** [comment]
It appears that nothing else is needed, I am going to close the ticket. Feel free to reopen if required.
