### ISSUE TITLE
Zato doesn't restart

### ISSUE THREAD

**Issue by gevpaulson** [zatosource/zato#1164]
I tried to restart zato, and it doesn't work

I use quickstart with Docker, just I deployed 2 services and run /env/qs-1/zato-qs-restart.sh and it's all...

zato@eae88d60ed4c:~/env/qs-1$ ./zato-qs-restart.sh
Stopping Zato cluster quickstart-308918
Load-balancer `/opt/zato/env/qs-1/load-balancer` shutting down
2021-08-17 11:00:00,895 - INFO - 1256:MainThread - Stop:50 - Load-balancer `/opt/zato/env/qs-1/load-balancer` shutting down
[1/5] Load-balancer stopped
Server `/opt/zato/env/qs-1/server1` shutting down
2021-08-17 11:00:02,433 - INFO - 1281:MainThread - Stop:50 - Server `/opt/zato/env/qs-1/server1` shutting down
[2/5] server1 stopped
Server `/opt/zato/env/qs-1/server2` shutting down
2021-08-17 11:00:04,172 - INFO - 1307:MainThread - Stop:50 - Server `/opt/zato/env/qs-1/server2` shutting down
[3/5] server2 stopped
Web admin `/opt/zato/env/qs-1/web-admin` shutting down
2021-08-17 11:00:06,230 - INFO - 1336:MainThread - Stop:50 - Web admin `/opt/zato/env/qs-1/web-admin` shutting down
[4/5] Web admin stopped
Scheduler `/opt/zato/env/qs-1/scheduler` shutting down
2021-08-17 11:00:08,527 - INFO - 1380:MainThread - Stop:50 - Scheduler `/opt/zato/env/qs-1/scheduler` shutting down
[5/5] Scheduler stopped
Zato cluster quickstart-308918 stopped
Starting Zato cluster quickstart-308918
Checking configuration
[1/8] Redis connection OK
[2/8] SQL ODB connection OK
[3/8] Checking TCP ports availability
Port taken 20151 (Load-balancer's agent)
Port taken 17010 (server1)
Port taken 17011 (server2)
File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/zato_command.py", line 424, in main
    return run_command(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 382, in run_command
    command_class[args.command](args).run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 658, in run
    return_code = self.execute(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 940, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/start.py", line 123, in _on_lb
    self.run_check_config()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/start.py", line 67, in run_check_config
    'secret_key': self.args.secret_key,
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 940, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/check_config.py", line 257, in _on_lb
    self.ensure_json_config_port_free('Load balancer\'s agent', None, lba_conf)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/check_config.py", line 62, in ensure_json_config_port_free
    self.ensure_port_free(prefix, conf['port'], address)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/check_config.py", line 55, in ensure_port_free
    raise Exception('{} check failed. Address `{}` already taken.'.format(prefix, address))
Exception: Load balancer's agent check failed. Address `localhost:20151` already taken.

2021-08-17 11:00:46,539 - ERROR - 1652:MainThread - Start:670 - File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/zato_command.py", line 424, in main
    return run_command(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 382, in run_command
    command_class[args.command](args).run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 658, in run
    return_code = self.execute(args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 940, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/start.py", line 123, in _on_lb
    self.run_check_config()
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/start.py", line 67, in run_check_config
    'secret_key': self.args.secret_key,
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/__init__.py", line 940, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/check_config.py", line 257, in _on_lb
    self.ensure_json_config_port_free('Load balancer\'s agent', None, lba_conf)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/check_config.py", line 62, in ensure_json_config_port_free
    self.ensure_port_free(prefix, conf['port'], address)
  File "/opt/zato/3.1.0/code/zato-cli/src/zato/cli/check_config.py", line 55, in ensure_port_free
    raise Exception('{} check failed. Address `{}` already taken.'.format(prefix, address))
Exception: Load balancer's agent check failed. Address `localhost:20151` already taken.

**Comment by dsuch** [comment]
Hello @gevpaulson,

please use Zato 3.2, there will be no more support for 3.1 because 3.2 is almost 100% ready.

I am closing this ticket, please feel free to open a new one in case the same happens with Zato 3.2. Should that happen, make sure to post the output from "zato --version" too.

**Comment by gevpaulson** [comment]
Thanks, i'll try
