### ISSUE TITLE
Zato 3.2 doesn't restart 

### ISSUE THREAD

**Issue by gevpaulson** [zatosource/zato#1165]
The same problem with 3.2
I don't know why it happens

Docker quickstart 

Just try to deploy 2 services and restart and it's all, it doesn't work=(

zato@9c2e86627b19:~/env/qs-1$ ./zato-qs-restart.sh
Stopping Zato cluster quickstart-551540
Load-balancer `/opt/zato/env/qs-1/load-balancer` shutting down
[1/4] Load-balancer stopped
Server `/opt/zato/env/qs-1/server1` shutting down
[2/4] server1 stopped
Web admin `/opt/zato/env/qs-1/web-admin` shutting down
[4/4] Web admin stopped
Scheduler `/opt/zato/env/qs-1/scheduler` shutting down
[4/4] Scheduler stopped
Zato cluster quickstart-551540 stopped
Starting Zato cluster quickstart-551540
Checking configuration
[1/7] Redis connection OK
[2/7] SQL ODB connection OK
[3/7] Checking TCP ports availability
Port taken 20151 (Load-balancer's agent)
File "/opt/zato/current/bin/zato", line 16, in <module>
    sys.exit(main())
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/zato_command.py", line 568, in main
    return run_command(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 394, in run_command
    return instance.run(args)
  Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 767, in run
    return_code = self.execute(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 1082, in execute
    handler(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/start.py", line 149, in _on_lb
    self.run_check_config()
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/start.py", line 61, in run_check_config
    cc.execute(Bunch({
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/__init__.py", line 1082, in execute
    handler(args)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/check_config.py", line 297, in _on_lb
    self.ensure_json_config_port_free('Load balancer\'s agent', None, lba_conf)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/check_config.py", line 46, in ensure_json_config_port_free
    self.ensure_port_free(prefix, conf['port'], address)
  File "/opt/zato/3.2.0/code/zato-cli/src/zato/cli/check_config.py", line 39, in ensure_port_free
    raise Exception('{} check failed. Address `{}` already taken.'.format(prefix, address))
Exception: Load balancer's agent check failed. Address `localhost:20151` already taken.

**Comment by dsuch** [comment]
What is the output of "zato --version"?

**Comment by gevpaulson** [comment]
Zato 3.2+rev.70482181-py3.8.5-ubuntu.20.04-focal

**Comment by dsuch** [comment]
As a workaround, does "zato stop", waiting a moment and running "zato start" help?

**Comment by gevpaulson** [comment]
no, it doesn't work

**Comment by gevpaulson** [comment]
Sorry about it
But i thought docker gets you enough information about my situation
Did you try to restart zato in docker container?

**Comment by dsuch** [comment]
I have not had an opportunity to check it yet, I will let you know when I have.

**Comment by dsuch** [comment]
Good day @gevpaulson,

I have not checked it yet in the context of your question but there is a new Docker quickstart image for Zato 3.2, can you check if that resolves your situation?

https://zato.io/docs/admin/guide/install/docker.html

Thank you.

**Comment by gevpaulson** [comment]
Good day @dsuch! I'll try, thanks

**Comment by dsuch** [comment]
Hello @gevpaulson - have you had an opportunity to check the new image?

**Comment by gevpaulson** [comment]
Hello @dsuch
Yes, I tried it, but the problem was not fixed
And you? Did you try to reproduce the error?

**Comment by dsuch** [comment]
Hello @gevpaulson,

there is a new quickstart image, can you please try it out?

If anything does not work, please post the exact of what it is, the exact commands that you use, the whole output and your full Zato version as reported by zato --version.

Thank you.
