### ISSUE TITLE
pubsub>task>delivery error on Zato 3.2.0

### ISSUE THREAD

**Issue by libigfat** [zatosource/zato#1167]
My zato version Zato 3.2+rev.adb591b-py3.6.8-centos.7-core
When I click zato3.2.0 WEB-ADMIN pubsub>task>delivery.
![1](https://user-images.githubusercontent.com/40198012/134460414-b5f19049-0843-4e33-b0b0-23ba87c687fa.png)
There is a problem.
![2](https://user-images.githubusercontent.com/40198012/134460506-5abee41a-a2e0-4420-8a5a-5c21df5ddf21.png)
**Logs error**
```
2021-09-23 13:49:32,879 - [1;31mERROR[0m - 17618:DummyThread-136 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`da679629f6ba14c17c54b936`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 801, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 743, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 624, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/service.py", line 478, in handle
    serialize=True)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 897, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 880, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 801, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 743, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 624, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/task/delivery/server.py", line 193, in handle
    self.response.payload[:] = self.get_data()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/task/delivery/server.py", line 168, in get_data
    pid_response = bunchify(self.server.rpc[server_name].invoke(GetDetails.get_name(), pid=pid))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/server/rpc/invoker.py", line 189, in invoke
    return self._invoke(self.invoker.invoke, *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/server/rpc/invoker.py", line 171, in _invoke
    per_pid_data = pid_data['pid_data']
TypeError: string indices must be integers
```
Thank you very much.

**Comment by dsuch** [comment]
Thanks but what is this commit adb591b? How did you build or install Zato? Have you modified anything?

**Comment by libigfat** [comment]
Because I am in China, the network of cloning code from GitHub is unstable. Therefore, I downloaded the latest code and uploaded it to the local gitlab for source code compilation and installation. So commit is different.

**Comment by dsuch** [comment]
Hello again @libigfat -  we talked about it a few weeks ago. I am not able to reproduce your ticket, please contact me using your business email on dsuch@zato.io and we can discuss how to proceed directly. Thank you.
