### ISSUE TITLE
hot deploy error

### ISSUE THREAD

**Issue by penfree** [zatosource/zato#1182]
i meet this error when i upload  a service file from the webadmin UI or hot deploy from vscode plugin.

```
2022-01-18 06:15:02,495 - ERROR - 80:DummyThread-30063 - zato:0 - Could not handle broker message: (HOT_DEPLOY_CREATE_SERVICE:102200) `Bunch(action='102200', cid='d1b0c5f0b529cc2b797e6886', package_id=6, payload={'package_id': 6}, service='zato.hot-deploy.create')`, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-broker/src/zato/broker/__init__.py", line 48, in on_broker_msg
    func(msg)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1956, in on_broker_msg_HOT_DEPLOY_CREATE_SERVICE
    response = self.on_broker_msg_hot_deploy(
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1949, in on_broker_msg_hot_deploy
    return self.on_message_invoke_service(msg, 'hot-deploy', 'HOT_DEPLOY_{}'.format(action), args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1675, in on_message_invoke_service
    response = service.update_handle(service.set_response_data, service, payload,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 889, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 831, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 716, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 378, in handle
    services_deployed = self.deploy_package(self.request.input.package_id, session) or []
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 326, in deploy_package
    return self._deploy_package(session, package_id, dp.payload_name, dp.payload,
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 268, in _deploy_package
    ctx = self._deploy_file(work_dir, payload, file_name, should_deploy_in_place)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 241, in _deploy_file
    model_name_list = self._deploy_models(current_work_dir, file_name)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 170, in _deploy_models
    if isinstance(item, type):
ReferenceError: weakly-referenced object no longer exists
`
2022-01-18 06:15:02,497 - DEBUG - 80:DummyThread-30061 - zato.client:0 - request:[{"name": "zato.service.rpc-service-invoker", "payload": "eyJhY3Rpb24iOiAiMTAyMjAwIiwgInBhY2thZ2VfaWQiOiA2fQ==", "channel": "invoke", "data_format": "json", "transport": null, "is_async": false, "expiration": 15, "pid": null, "all_pids": true, "timeout": null, "skip_response_elem": true}]
response_class:[<class 'zato.client.ServiceInvokeResponse'>]
is_async:[False]
headers:[{}]
 text:[{"response":"eyI4MCI6eyJpc19vayI6dHJ1ZSwicGlkIjo4MCwicGlkX2RhdGEiOiIiLCJlcnJvcl9pbmZvIjoiIn19","zato_env":{"result":"ZATO_OK","cid":"65deb3ccaf4ee391988eec2b","details":""}}]
data:[{'80': {'is_ok': True, 'pid': 80, 'pid_data': '', 'error_info': ''}}]
```

**Comment by dsuch** [comment]
Hello,

make sure that you use the latest version https://zato.io/docs/admin/guide/install/update.html. If you use Docker Quickstart, make sure that it is the latest image.

Also, whenever you submit a ticket in GitHub, please always provide output from `zato --version` - otherwise it is impossible to know what your version is.

Regards.

**Comment by penfree** [comment]
> Hello,
> 
> make sure that you use the latest version https://zato.io/docs/admin/guide/install/update.html. If you use Docker Quickstart, make sure that it is the latest image.
> 
> Also, whenever you submit a ticket in GitHub, please always provide output from `zato --version` - otherwise it is impossible to know what your version is.
> 
> Regards.

thank you for your quick response. the version is below.
root@server-67fdcb6568-l8smg:/opt/zato/3.2.0/code# ./bin/zato --version
Zato 3.2+rev.6f6a120a-py3.8.10-ubuntu.20.04-focal

i'm using the helm chart to deploy, but i meet so many error. the official docker image has many bug and i think noone has test it.
