### ISSUE TITLE
Zato Error Connections/Outgoing/Soap

### ISSUE THREAD

**Issue by mangrovex** [zatosource/zato#1209]
Going through the tutorial to invoke a SOAP service, https://zato.io/docs/dev/examples/soap.html.

Looking at the zato log we see that the channel cannot be created. Please your suggestions
server.log
2022-11-16 13:38:51,555 - ERROR - 23379:Dummy-49 - zato:0 - Could not handle broker message: (OUTGOING_HTTP_SOAP_CREATE_EDIT:100815) `Bunch(action='100815', cache_expiry=None, cache_id=None, cluster_id=1, connection='outgoing', content_encoding=None, content_type='', data_encoding='utf-8', data_format='json', has_rbac=False, hl7_version='hl7-v2', host='http://www.thomas-bayer.com', http_accept=None, id=85, is_active=True, is_audit_log_received_active=False, is_audit_log_sent_active=False, is_internal=False, is_rate_limit_active=False, json_path='', match_slash=False, max_bytes_per_message_received=500, max_bytes_per_message_sent=500, max_len_messages_received=50, max_len_messages_sent=50, merge_url_params_req=False, method=None, name='BLZ', old_http_accept=None, old_http_method=None, old_name='demo', old_soap_action='', old_url_path='/axis2/services/BLZService?wsdl', params_pri='channel-params-over-msg', ping_method='HEAD', pool_size=20, rate_limit_check_parent_def=False, rate_limit_def=None, rate_limit_type=None, sec_tls_ca_cert_id=None, sec_tls_ca_cert_verify_strategy=True, sec_type=None, sec_use_rbac=False, security_id=None, security_name=None, serialization_type='suds', service=None, service_whitelist='', should_parse_on_input=False, should_return_errors=False, should_validate=False, soap_action='', soap_version='1.1', timeout='10', tls_verify='', transport='soap', url_params_pri='qs-over-path', url_path='/axis2/services/BLZService?wsdl')`, e:`Traceback (most recent call last):
  File "/home/mevu/zato/code/zato-broker/src/zato/broker/__init__.py", line 48, in on_broker_msg
    func(msg)
  File "/home/mevu/zato/code/zato-server/src/zato/server/base/worker/__init__.py", line 1934, in on_broker_msg_OUTGOING_HTTP_SOAP_CREATE_EDIT
    wrapper = self._http_soap_wrapper_from_config(msg, False)
  File "/home/mevu/zato/code/zato-server/src/zato/server/base/worker/__init__.py", line 571, in _http_soap_wrapper_from_config
    wrapper = SudsSOAPWrapper(wrapper_config)
  File "/home/mevu/zato/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 566, in __init__
    self.client = ConnectionQueue(
TypeError: ConnectionQueue.__init__() missing 1 required positional argument: 'add_client_func'
`

**Comment by dsuch** [comment]
Hello @mangrovex - I sent you a message on LinkedIn.
