### ISSUE TITLE
Quickstart error when using sqlite: unable to open database

### ISSUE THREAD

**Issue by csala** [zatosource/zato#296]
When creating a new cluster using sqlite with the quickstart command, the process fails while creating the web-admin because of some db connection error.

I was able to reproduce the error in two different machines running Ubuntu Server 14.04, completely up-to-date, one virtual and the other physical.

Here's the history of commands, as well as the error stack trace (I skipped all the non relevant output and commands)
```
$ git clone https://github.com/zatosource/zato.git
# ...
$ cd zato
$ git rev-parse HEAD
08c768c16383181113f0b70b279367cdb8917c4a
$ cd code
$ ./install.sh
# ...
$ echo 'export PATH=$PATH:/opt/zato/zato/code/bin' >> ~/.profile
# ... logout and login
$ zato --version
zato@trigh01:~/zato$ zato --version
Zato 2.0.0pre0.rev-08c768c1
$ mkdir test
$ zato quickstart create test sqlite localhost 6379 --verbose

Key/value database password (will not be echoed): 
Enter the kvdb_password again (will not be echoed): 
[1/8] Certificate authority created
[2/8] ODB schema created
[3/8] ODB initial data created
[4/8] server1 created
[5/8] server2 created
[6/8] Load-balancer created
Traceback (most recent call last):
  File "/opt/zato/zato/code/bin/zato", line 175, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/zato/code/zato-cli/src/zato/cli/zato_command.py", line 254, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 222, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 431, in run
    sys.exit(self.execute(args)) # noqa
  File "/opt/zato/zato/code/zato-cli/src/zato/cli/quickstart.py", line 333, in execute
    create_web_admin_args, False, password, True)
  File "/opt/zato/zato/code/zato-cli/src/zato/cli/create_web_admin.py", line 143, in execute
    call_command('syncdb', interactive=False, verbosity=0)
  File "/opt/zato/zato/code/eggs/Django-1.3.7-py2.7.egg/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(*args, **defaults)
  File "/opt/zato/zato/code/eggs/Django-1.3.7-py2.7.egg/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/opt/zato/zato/code/eggs/Django-1.3.7-py2.7.egg/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/opt/zato/zato/code/eggs/Django-1.3.7-py2.7.egg/django/core/management/commands/syncdb.py", line 56, in handle_noargs
    cursor = connection.cursor()
  File "/opt/zato/zato/code/eggs/Django-1.3.7-py2.7.egg/django/db/backends/__init__.py", line 250, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/opt/zato/zato/code/eggs/Django-1.3.7-py2.7.egg/django/db/backends/sqlite3/base.py", line 207, in _cursor
    self.connection = Database.connect(**kwargs)
sqlite3.OperationalError: unable to open database file
```

Looking at some SO posts reporting similar issues I would point at a wrong path specification, but I haven't gone deep enough into the code to find out where the path is defined, so it's just a guess.

**Comment by dsuch** [comment]
Thanks @csala - closing then.
