### ISSUE TITLE
Zato 2: LockTimeout: Timeout while waiting for lock

### ISSUE THREAD

**Issue by wbar** [zatosource/zato#375]
After boot, when trying do `curl -d{} zato-lb:11223/zato/ping` I'm receiving:
````
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
````

And in server log I can find:

````
Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 837, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 812, in start_server
    is_first = parallel_server._after_init_common(server, zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 328, in _after_init_common
    is_first = self.maybe_on_first_worker(server, self.kvdb.conn, deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 227, in maybe_on_first_worker
    with Lock(lock_name, self.deployment_lock_expires, self.deployment_lock_timeout, redis_conn):
  File "/opt/zato/2.0.1/eggs/retools-0.3-py2.7.egg/retools/lock.py", line 73, in __enter__
    raise LockTimeout("Timeout while waiting for lock")
LockTimeout: Timeout while waiting for lock
````

**Comment by dsuch** [comment]
> After boot

Hi @wbar - what do you mean by the 'boot' here?

**Comment by wbar** [comment]
````
zato start <zato-server>
zato start <zato-lb>
````

**Comment by dsuch** [comment]
Does executing this command and starting the servers help?

```
$ redis-cli KEYS "zato:lock:*" | xargs redis-cli DEL
```

**Comment by wbar** [comment]
not quite..
after removing all keys and restarting server I can see:
````
KEYS "zato:lock:*"
1) "zato:lock:server:starting:917328ee85be43eb872a919125d54e35:b14ffe53ca834abeaf85cc609451c70a"
2) "zato:lock:server:already-deployed:917328ee85be43eb872a919125d54e35:b14ffe53ca834abeaf85cc609451c70a"
````
and in server.log:
````
2015-02-25 20:08:34,030 - INFO - 22186:Dummy-1 - gunicorn.main:22 - Starting gunicorn 18.0
2015-02-25 20:08:34,034 - INFO - 22186:Dummy-1 - gunicorn.main:22 - Listening at: http://172.28.128.3:17010 (22186)
2015-02-25 20:08:34,034 - INFO - 22186:Dummy-1 - gunicorn.main:22 - Using worker: gevent
2015-02-25 20:08:34,038 - INFO - 22193:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 22193
2015-02-25 20:08:34,142 - INFO - 22194:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 22194
2015-02-25 20:08:56,308 - INFO - 22193:Dummy-3 - zato.broker.client:22 - Starting broker client, host:[core.falcon], port:[6379], name:[parallel-K067R3W8CRS830SY9Y1ZEVY48NGK], topics:[['/zato/to-parallel/all', '/zato/to-parallel/any', '/zato/to-singleton']]
2015-02-25 20:08:59,164 - INFO - 22201:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 22201
2015-02-25 20:09:26,263 - INFO - 22213:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 22213
````

after sending `curl -d {} core.falcon:11223/zato/ping`:
```` 
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
````

and after some long time server stops listening on port 17010 and in log I can see new lines:
```` 
2015-02-25 20:12:04,834 - ERROR - 22201:Dummy-1 - gunicorn.main:22 - Exception in worker process:
Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 837, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 812, in start_server
    is_first = parallel_server._after_init_common(server, zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 328, in _after_init_common
    is_first = self.maybe_on_first_worker(server, self.kvdb.conn, deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 227, in maybe_on_first_worker
    with Lock(lock_name, self.deployment_lock_expires, self.deployment_lock_timeout, redis_conn):
  File "/opt/zato/2.0.1/eggs/retools-0.3-py2.7.egg/retools/lock.py", line 73, in __enter__
    raise LockTimeout("Timeout while waiting for lock")
LockTimeout: Timeout while waiting for lock
Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 837, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 812, in start_server
    is_first = parallel_server._after_init_common(server, zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 328, in _after_init_common
    is_first = self.maybe_on_first_worker(server, self.kvdb.conn, deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 227, in maybe_on_first_worker
    with Lock(lock_name, self.deployment_lock_expires, self.deployment_lock_timeout, redis_conn):
  File "/opt/zato/2.0.1/eggs/retools-0.3-py2.7.egg/retools/lock.py", line 73, in __enter__
    raise LockTimeout("Timeout while waiting for lock")
LockTimeout: Timeout while waiting for lock
2015-02-25 20:12:04,836 - INFO - 22201:Dummy-1 - gunicorn.main:22 - Worker exiting (pid: 22201)
2015-02-25 20:12:28,025 - ERROR - 22213:Dummy-1 - gunicorn.main:22 - Exception in worker process:
Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 837, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 812, in start_server
    is_first = parallel_server._after_init_common(server, zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 328, in _after_init_common
    is_first = self.maybe_on_first_worker(server, self.kvdb.conn, deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 227, in maybe_on_first_worker
    with Lock(lock_name, self.deployment_lock_expires, self.deployment_lock_timeout, redis_conn):
  File "/opt/zato/2.0.1/eggs/retools-0.3-py2.7.egg/retools/lock.py", line 73, in __enter__
    raise LockTimeout("Timeout while waiting for lock")
LockTimeout: Timeout while waiting for lock
Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 837, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 812, in start_server
    is_first = parallel_server._after_init_common(server, zato_deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 328, in _after_init_common
    is_first = self.maybe_on_first_worker(server, self.kvdb.conn, deployment_key)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/base/parallel.py", line 227, in maybe_on_first_worker
    with Lock(lock_name, self.deployment_lock_expires, self.deployment_lock_timeout, redis_conn):
  File "/opt/zato/2.0.1/eggs/retools-0.3-py2.7.egg/retools/lock.py", line 73, in __enter__
    raise LockTimeout("Timeout while waiting for lock")
LockTimeout: Timeout while waiting for lock
2015-02-25 20:12:28,027 - INFO - 22213:Dummy-1 - gunicorn.main:22 - Worker exiting (pid: 22213)
2015-02-25 20:12:28,564 - INFO - 22186:Dummy-1 - gunicorn.main:22 - Shutting down: Master
2015-02-25 20:12:28,567 - INFO - 22186:Dummy-1 - gunicorn.main:22 - Reason: Worker failed to boot.
````

**Comment by wbar** [comment]
**TIP**: I'm trying to bind server on `eth1`

**Comment by dsuch** [comment]
Is it possible that it's an OS with very slow I/O - like a VM under a VM? That would explain why the initial deployment takes so long?

**Comment by wbar** [comment]
It's Vagrant VM (with VirtualBox provider) but after Your hint I've checked memory and increased it up to 1024 MB (from 512 which was to low)
