### ISSUE TITLE
apitest suite errors and documentation

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#380]
This is using the 2.0.1 Ubuntu-packaged release under Ubuntu 14.04

~~~
zato@cfprov:~/2.0.1$ ./run-tests.py apitests
Traceback (most recent call last):
  File "./bin/py", line 195, in <module>
    execfile(__file__)
  File "./run-tests.py", line 67, in <module>
    main()
  File "/opt/zato/2.0.1/eggs/click-1.1-py2.7.egg/click/core.py", line 384, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zato/2.0.1/eggs/click-1.1-py2.7.egg/click/core.py", line 370, in main
    self.invoke(ctx)
  File "/opt/zato/2.0.1/eggs/click-1.1-py2.7.egg/click/core.py", line 614, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/opt/zato/2.0.1/eggs/click-1.1-py2.7.egg/click/core.py", line 623, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/opt/zato/2.0.1/eggs/click-1.1-py2.7.egg/click/core.py", line 524, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/opt/zato/2.0.1/eggs/click-1.1-py2.7.egg/click/core.py", line 236, in invoke
    return callback(*args, **kwargs)
  File "./run-tests.py", line 51, in apitests
    _apitests()
  File "./run-tests.py", line 47, in _apitests
    run('{} run {}'.format(apitest_cmd, tests_dir))
  File "/opt/zato/2.0.1/eggs/sarge-0.1.3-py2.7.egg/sarge/__init__.py", line 1366, in run
    p.run(input=input, async=async)
  File "/opt/zato/2.0.1/eggs/sarge-0.1.3-py2.7.egg/sarge/__init__.py", line 997, in run
    self.run_node(self.tree, input=input, async=async)
  File "/opt/zato/2.0.1/eggs/sarge-0.1.3-py2.7.egg/sarge/__init__.py", line 1085, in run_node
    result = getattr(self, method)(node, input, async)
  File "/opt/zato/2.0.1/eggs/sarge-0.1.3-py2.7.egg/sarge/__init__.py", line 1231, in run_command_node
    node.cmd.run(input=input, async=async)
  File "/opt/zato/2.0.1/eggs/sarge-0.1.3-py2.7.egg/sarge/__init__.py", line 623, in run
    self.process = p = Popen(self.args, **self.kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/zato/2.0.1/eggs/sarge-0.1.3-py2.7.egg/sarge/__init__.py", line 538, in _execute_child
    super(Popen, self)._execute_child(args, executable, preexec, *rest)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
~~~

Sadly, it doesn't say what file it was trying to open :-(

After digging through strace -f output, I notice this:

~~~
[pid 10441] execve("/opt/zato/2.0.1/bin/apitest", ["apitest", "run", "/opt/zato/2.0.1/apitest"], [/*
 18 vars */]) = -1 ENOENT (No such file or directory)
[pid 10441] execve("/usr/local/sbin/apitest", ["apitest", "run", "/opt/zato/2.0.1/apitest"], [/* 18
vars */]) = -1 ENOENT (No such file or directory)
[pid 10441] execve("/usr/local/bin/apitest", ["apitest", "run", "/opt/zato/2.0.1/apitest"], [/* 18 v
ars */]) = -1 ENOENT (No such file or directory)
[pid 10441] execve("/usr/sbin/apitest", ["apitest", "run", "/opt/zato/2.0.1/apitest"], [/* 18 vars *
/]) = -1 ENOENT (No such file or directory)
[pid 10441] execve("/usr/bin/apitest", ["apitest", "run", "/opt/zato/2.0.1/apitest"], [/* 18 vars */
]) = -1 ENOENT (No such file or directory)
[pid 10441] execve("/sbin/apitest", ["apitest", "run", "/opt/zato/2.0.1/apitest"], [/* 18 vars */])
= -1 ENOENT (No such file or directory)
[pid 10441] execve("/bin/apitest", ["apitest", "run", "/opt/zato/2.0.1/apitest"], [/* 18 vars */]) =
 -1 ENOENT (No such file or directory)

... skip reading of /usr/lib/python2.7/subprocess.py and /opt/zato/2.0.1/lib/python2.7/os.py

[pid 10441] stat("/opt/zato/2.0.1/lib/python2.7/os.py", {st_mode=S_IFREG|0644, st_size=25769, ...}) = 0
[pid 10441] write(4, "cexceptions\nOSError\np0\n(I2\nS'No such file or directory'\np1\ntp2\nRp3\n(dp4\nS'child_traceback'\np5\nS'Traceback (most recent call last):\\n  File \"/usr/lib/python2.7/subprocess.py\", line 1282, in _execute_child\\n    os.execvp(executable, args)\\n  File \"/opt/zato/2.0.1/lib/python2.7/os.py\", line 344, in execvp\\n    _execvpe(file, args)\\n  File \"/opt/zato/2.0.1/lib/python2.7/os.py\", line 380, in _execvpe\\n"..., 484 <unfinished ...>
~~~

Indeed, there is no such "apitest" binary. There is `local/apitest` but it symlinks to the apitest *directory*

Solution is to install zato-apitest as per [its own docs](https://github.com/zatosource/zato-apitest#download-and-install)

~~~
$ sudo apt-get install -y libpq-dev libxml2-dev libxslt1-dev python-dev libyaml-dev
$ sudo pip install zato-apitest
~~~

However I think this error could be reported in a way which would make it much easier to diagnose.

Additionally: installing zato-apitest in this way using "pip" installs a whole bunch of dependencies which are already under `/opt/zato/<version>`, like lxml, which seems wasteful and adds pollution which zato itself takes pains to avoid.

After this, 56 tests fail with KeyError on `$ZATO_API_TEST_SERVER`

Therefore it looks like a bunch of environment variables need to be set:

~~~
$ grep -R '\$' apitest/features/ | ruby -ne 'puts $_.scan(/(\$\w+)/).join("\n")' | sort -u
$ZATO_API_TEST_CLUSTER_ID
$ZATO_API_TEST_PUBAPI_PASSWORD
$ZATO_API_TEST_PUBAPI_USER
$ZATO_API_TEST_SERVER
~~~

but I cannot find any documentation on how to prepare and run the apitest suite.

**Comment by candlerb** [comment]
After some reverse-engineering:

~~~
export ZATO_API_TEST_SERVER="http://127.0.0.1:11223"
export ZATO_API_TEST_CLUSTER_ID="quickstart-XXXXXX"
export ZATO_API_TEST_PUBAPI_USER="pubapi"
export ZATO_API_TEST_PUBAPI_PASSWORD="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
~~~

where the cluster ID comes from the web interface, and the password from

~~~
sqlite3> select password from sec_base where username='pubapi';
~~~

However there are still 46 errors (down from 56). 

The first error is this one:

~~~
Feature: zato.ping2

  Scenario: Invoke zato.ping2 to check if zato is up
    Given address "$ZATO_API_TEST_SERVER"
    Given URL path "/zato/ping2"
    Given format "JSON"
    Given request is "{}"
    When the URL is invoked
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/steps/common.py", line 87, in when_the_url_is_invoked
          ctx.zato.response.data_impl = json.loads(ctx.zato.response.data.text)
        File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
          return _default_decoder.decode(s)
        File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
          raise ValueError("No JSON object could be decoded")
      ValueError: No JSON object could be decoded

      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1

    Then JSON Pointer "/zato_ping2_response/pong" is "zato"
~~~

The service is invokable from the CLI:

~~~
$ zato service invoke ../env/qs-1/server1 zato.ping2
{u'pong': u'zato'}
~~~

but not using curl:

~~~
$ curl http://localhost:11223/zato/ping2 -d '{}'; echo
[K059WP13E4QQT3V1XMNP1RDX8H0K] Unknown URL:[/zato/ping2] or SOAP action:[]
~~~

(In the GUI I cannot find a channel for /zato/ping2; but then I can't find one for /zato/ping either and that works)

The next error is this one:

~~~
Feature: scheduler.job.interval_based.type

  Scenario: Log in to Zato Public API and create a job
    Given address "$ZATO_API_TEST_SERVER"
    Given Basic Auth "$ZATO_API_TEST_PUBAPI_USER" "$ZATO_API_TEST_PUBAPI_PASSWORD"
    Given URL path "/zato/json/zato.scheduler.job.create"
    Given format "JSON"
    Given request is "{}"
    Given JSON Pointer "/cluster_id" in request is "$ZATO_API_TEST_CLUSTER_ID"
    Given JSON Pointer "/name" in request is a random string
    Given JSON Pointer "/is_active" in request is "true"
    Given JSON Pointer "/job_type" in request is "interval_based"
    Given JSON Pointer "/service" in request is "zato.stats.aggregate-by-day"
    Given JSON Pointer "/start_date" in request is UTC now "default"
    Given JSON Pointer "/weeks" in request is a random integer
    When the URL is invoked
    Then status is "200"
      Assertion Failed: Status expected `200`, received `500`
      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1

    And JSON Pointer "/zato_env/result" is "ZATO_OK"
    And JSON Pointer "/zato_scheduler_job_create_response/id" isn't empty
    And JSON Pointer "/zato_scheduler_job_create_response/name" isn't empty
    And JSON Pointer "/zato_scheduler_job_create_response/cron_definition" is empty
    And I store "/zato_scheduler_job_create_response/name" from response under "job_name"
    And I store "/zato_scheduler_job_create_response/id" from response under "job_id"
~~~

(It would be very useful if the actual received reply would be shown, as otherwise there is little indication of what went wrong)

As far as I can see, the scenarios in zato-apitest don't setup and teardown between each one - they depend on the state set in previous tests.  Since it doesn't get as far as storing job_name, the next scenario necessarily fails:

~~~
  Scenario: Get the job by name
    Given address "$ZATO_API_TEST_SERVER"
    Given Basic Auth "$ZATO_API_TEST_PUBAPI_USER" "$ZATO_API_TEST_PUBAPI_PASSWORD"
    Given URL path "/zato/json/zato.scheduler.job.get-by-name"
    Given format "JSON"
    Given request is "{}"
    Given JSON Pointer "/cluster_id" in request is "$ZATO_API_TEST_CLUSTER_ID"
    Given JSON Pointer "/name" in request is "#job_name"
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/util.py", line 70, in inner
          kwargs[kwarg] = config_func(ctx, value[1:])
        File "/usr/local/lib/python2.7/dist-packages/zato/apitest/util.py", line 50, in get_value_from_ctx
          return ctx.zato.user_ctx[name]
      KeyError: u'job_name'
~~~

**Comment by dsuch** [comment]
Made it way easier to run API tests - in current master all that is required is a server running on localhost:17010 which will be auto-discovered and used to run the tests against.
