### ISSUE TITLE
nosetest suite errors displayed

### ISSUE THREAD

**Issue by candlerb** [zatosource/zato#381]
`./runtests.py nosetests` apparently succeeds. It shows that 459 tests were run. It doesn't actually say there are zero failures, but if I intentionally break a test, I can see it fail.

However there are some greenlet / invoke_retry exceptions displayed. It's not clear if these are errors or just expected debug output.

The test suite run then finishes with an `Unhandled exception in thread started by <bound method TLSServer.__bootstrap` which may just be shutdown noise?

~~~
$ ./run-tests.py nosetests
.....................127.0.0.1 - - [26/Feb/2015 09:02:28] "GET / HTTP/1.1" 200 -
..127.0.0.1 - - [26/Feb/2015 09:02:29] "GET / HTTP/1.1" 200 -
..127.0.0.1 - - [26/Feb/2015 09:02:30] "GET / HTTP/1.1" 200 -
..127.0.0.1 - - [26/Feb/2015 09:02:32] "GET / HTTP/1.1" 200 -
.............................................................................................................................................................................................Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gevent-1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/service/internal/pattern/invoke_retry.py", line 42, in _retry
    raise RetryFailed(remaining-1, e)
RetryFailed
<Greenlet at 0x7f96c85b9690: <bound method InvokeRetry._retry of <zato.server.service.internal.pattern.invoke_retry.InvokeRetry object at 0x7f96b9cf17d0>>(4)> failed with RetryFailed

Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gevent-1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/service/internal/pattern/invoke_retry.py", line 42, in _retry
    raise RetryFailed(remaining-1, e)
RetryFailed
<Greenlet at 0x7f96c85b9f50: <bound method InvokeRetry._retry of <zato.server.service.internal.pattern.invoke_retry.InvokeRetry object at 0x7f96b9cf17d0>>(3)> failed with RetryFailed

Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gevent-1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/service/internal/pattern/invoke_retry.py", line 42, in _retry
    raise RetryFailed(remaining-1, e)
RetryFailed
<Greenlet at 0x7f96c85b9eb0: <bound method InvokeRetry._retry of <zato.server.service.internal.pattern.invoke_retry.InvokeRetry object at 0x7f96b9cf17d0>>(2)> failed with RetryFailed

Traceback (most recent call last):
  File "/opt/zato/2.0.1/eggs/gevent-1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/zato/2.0.1/zato-server/src/zato/server/service/internal/pattern/invoke_retry.py", line 42, in _retry
    raise RetryFailed(remaining-1, e)
RetryFailed
<Greenlet at 0x7f96c85b9690: <bound method InvokeRetry._retry of <zato.server.service.internal.pattern.invoke_retry.InvokeRetry object at 0x7f96b9cf17d0>>(1)> failed with RetryFailed

...................................................................................................................................................................................................................................................
Name                                                       Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------------
<< snip test coverage report >>
----------------------------------------------------------------------------------------
TOTAL                                                      17179  16740     3%
----------------------------------------------------------------------
Ran 459 tests in 26.594s

OK
Unhandled exception in thread started by <bound method TLSServer.__bootstrap of <TLSServer(Thread-4, stopped daemon 140285592594176)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 823, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):Exception in thread Thread-7 (most likely raised during interpreter shutdown):Exception in thread Thread-8 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner

Traceback (most recent call last):  File "/opt/zato/2.0.1/zato-common/src/zato/common/test/tls.py", line 86, in run
  File "/usr/lib/python2.7/SocketServer.py", line 235, in serve_forever
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'select'

  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/opt/zato/2.0.1/zato-common/src/zato/common/test/tls.py", line 86, in run

Traceback (most recent call last):  File "/usr/lib/python2.7/SocketServer.py", line 235, in serve_forever

  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'select'

  File "/opt/zato/2.0.1/zato-common/src/zato/common/test/tls.py", line 86, in run
  File "/usr/lib/python2.7/SocketServer.py", line 235, in serve_forever
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'select'
~~~

**Comment by dsuch** [comment]
Hi @candlerb 

```raise RetryFailed(remaining-1, e)``` -> yes, this is expected because the test checks how failed invoke/retry calls are handled.

```which may just be shutdown noise?``` -> indeed it is.

The tests try not to be obnoxious but there is currently no effort in making them not output anything. In particular the thread's shutdown thing is always a pain to deal with in Python. I know it would be cool to have only dots and an OK.

**Comment by dsuch** [comment]
By the way, that coverage of 3% is invalid, at one point coverage.py stopped reporting in accurately.
