### ISSUE TITLE
Error when creating a channel via web-admin

### ISSUE THREAD

**Issue by Cito** [zatosource/zato#384]
When creating a new plain HTTP channel via web-admin of Zato 2.0.2 as described in the tutorial, Firefox 36.0 on Win 7 gives me a yellow error message at the top of the screen:

    Could not create the object, e:[Traceback (most recent call last):
      File "/opt/zato/2.0.2/zato-web-admin/src/zato/admin/web/views/http_soap.py", line 189, in create
        response = req.zato.client.invoke('zato.http-soap.create', _get_edit_create_message(req.POST))
      File "/opt/zato/2.0.2/zato-web-admin/src/zato/admin/middleware.py", line 70, in invoke
        raise Exception(response.inner.text)
    Exception: {"zato_env": {"details": "Traceback (most recent call last):\n  File \"\/opt\/zato\/2.0.2\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", line 198, in dispatch\n    payload, worker_store, self.simple_io_config, post_data)\n  File \"\/opt\/zato\/2.0.2\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", line 351, in handle\n    params_priority=channel_item.params_pri)\n  File \"\/opt\/zato\/2.0.2\/zato-server\/src\/zato\/server\/service\/__init__.py\", line 423, in update_handle\n    raise e\nZatoException: Expected elem:[id] not found in item:[{u'id': u'', u'name': u''}]\n", "result": "ZATO_ERROR", "cid": "K06ER1S7TTQ2VDRP0V1NAEAVTKPM"}}
    ]
    
No channel is created. In the admin.log I find the following 2 entries:
    
    2015-03-04 20:33:58,493 - INFO - 1367:Dummy-274 - zato_admin:22 - cid:[K06ER1S7TTQ2VDRP0V1NAEAVTKPM], name:[zato.service.invoke], SIO request:[{u'name': u'zato.http-soap.create', u'data_format': u'json', u'id': u'', u'channel': u'invoke', u'async': False, u'payload': u'eyJzZWNfdGxzX2NhX2NlcnRfaWQiOiBudWxsLCAiaXNfaW50ZXJuYWwiOiBmYWxzZSwgInNvYXBf\nYWN0aW9uIjogIiIsICJjbHVzdGVyX2lkIjogIjEiLCAiaGFzX3JiYWMiOiBmYWxzZSwgInNlcmlh\nbGl6YXRpb25fdHlwZSI6ICJzdHJpbmciLCAicGluZ19tZXRob2QiOiBudWxsLCAiaWQiOiBudWxs\nLCAidHJhbnNwb3J0IjogInBsYWluX2h0dHAiLCAic2VydmljZSI6ICJteS1zZXJ2aWNlLmdldC1n\nbGllbnQtZGV0YWlscyIsICJzb2FwX3ZlcnNpb24iOiBudWxsLCAibWV0aG9kIjogIiIsICJpc19h\nY3RpdmUiOiB0cnVlLCAiaG9zdCI6IG51bGwsICJ1cmxfcGF0aCI6ICJcL3R1dG9yaWFsXC9maXJz\ndC1zZXJ2aWNlIiwgIm1lcmdlX3VybF9wYXJhbXNfcmVxIjogdHJ1ZSwgIm5hbWUiOiAiR2V0IENs\naWVudCBEZXRhaWxzIiwgImRhdGFfZm9ybWF0IjogImpzb24iLCAicG9vbF9zaXplIjogbnVsbCwg\nInVybF9wYXJhbXNfcHJpIjogInFzLW92ZXItcGF0aCIsICJjb25uZWN0aW9uIjogImNoYW5uZWwi\nLCAidGltZW91dCI6IG51bGwsICJzZWN1cml0eV9pZCI6ICJaQVRPX05PTkUiLCAicGFyYW1zX3By\naSI6ICJjaGFubmVsLXBhcmFtcy1vdmVyLW1zZyJ9\n', u'transport': None, u'expiration': 15}]
    2015-03-04 20:33:58,555 - INFO - 1367:Dummy-274 - zato_admin:22 - cid:[K06ER1S7TTQ2VDRP0V1NAEAVTKPM], name:[zato.http-soap.create], SIO request:[{u'sec_tls_ca_cert_id': None, u'is_internal': False, u'is_active': True, u'soap_action': u'', u'host': None, u'cluster_id': 1, u'has_rbac': False, u'serialization_type': u'string', u'url_path': u'/tutorial/first-service', u'transport': u'plain_http', u'ping_method': None, u'name': u'Get Client Details', u'service': u'my-service.get-glient-details', u'soap_version': None, u'data_format': u'json', u'pool_size': None, u'url_params_pri': u'qs-over-path', u'connection': u'channel', u'merge_url_params_req': True, u'timeout': None, u'security_id': u'ZATO_NONE', u'params_pri': u'channel-params-over-msg', u'method': u''}]

When I do the same with Chrome 40.0 on Win 7, everything works, except that the following success message is not displayed on the same page, but in raw JSON form on a new page:
    
    {"message": "Successfully created the Plain HTTP channel [Get Client Details], check server logs for details", "id": 536, "transport": "plain_http"}

When I do the same with Chrome 41.0 on Win 7, everything works as expected, and the success message is displayed properly in a green box on the same page. In the admin.log I get these 4 entries:
    
    2015-03-04 20:42:41,678 - INFO - 1380:Dummy-372 - zato_admin:22 - cid:[K076MX3K1S5KYCF9SVHSAENXHJA2], name:[zato.service.invoke], SIO request:[{u'name': u'zato.http-soap.create', u'data_format': u'json', u'id': u'', u'channel': u'invoke', u'async': False, u'payload': u'eyJzZWNfdGxzX2NhX2NlcnRfaWQiOiBudWxsLCAiaXNfaW50ZXJuYWwiOiBmYWxzZSwgInNvYXBf\nYWN0aW9uIjogIiIsICJjbHVzdGVyX2lkIjogIjEiLCAiaGFzX3JiYWMiOiBmYWxzZSwgInNlcmlh\nbGl6YXRpb25fdHlwZSI6ICJzdHJpbmciLCAicGluZ19tZXRob2QiOiBudWxsLCAiaWQiOiBudWxs\nLCAidHJhbnNwb3J0IjogInBsYWluX2h0dHAiLCAic2VydmljZSI6ICJteS1zZXJ2aWNlLmdldC1j\nbGllbnQtZGV0YWlscyIsICJzb2FwX3ZlcnNpb24iOiBudWxsLCAibWV0aG9kIjogIiIsICJpc19h\nY3RpdmUiOiB0cnVlLCAiaG9zdCI6IG51bGwsICJ1cmxfcGF0aCI6ICJcL3R1dG9yaWFsXC9maXJz\ndC1zZXJ2aWNlIiwgIm1lcmdlX3VybF9wYXJhbXNfcmVxIjogdHJ1ZSwgIm5hbWUiOiAiR2V0IENs\naWVudCBEZXRhaWxzIiwgImRhdGFfZm9ybWF0IjogImpzb24iLCAicG9vbF9zaXplIjogbnVsbCwg\nInVybF9wYXJhbXNfcHJpIjogInFzLW92ZXItcGF0aCIsICJjb25uZWN0aW9uIjogImNoYW5uZWwi\nLCAidGltZW91dCI6IG51bGwsICJzZWN1cml0eV9pZCI6ICJaQVRPX05PTkUiLCAicGFyYW1zX3By\naSI6ICJjaGFubmVsLXBhcmFtcy1vdmVyLW1zZyJ9\n', u'transport': None, u'expiration': 15}]
    2015-03-04 20:42:41,686 - INFO - 1380:Dummy-372 - zato_admin:22 - cid:[K076MX3K1S5KYCF9SVHSAENXHJA2], name:[zato.http-soap.create], SIO request:[{u'sec_tls_ca_cert_id': None, u'is_internal': False, u'is_active': True, u'soap_action': u'', u'host': None, u'cluster_id': 1, u'has_rbac': False, u'serialization_type': u'string', u'url_path': u'/tutorial/first-service', u'transport': u'plain_http', u'ping_method': None, u'name': u'Get Client Details', u'service': u'my-service.get-client-details', u'soap_version': None, u'data_format': u'json', u'pool_size': None, u'url_params_pri': u'qs-over-path', u'connection': u'channel', u'merge_url_params_req': True, u'timeout': None, u'security_id': u'ZATO_NONE', u'params_pri': u'channel-params-over-msg', u'method': u''}]
    2015-03-04 20:42:41,748 - INFO - 1380:Dummy-372 - zato_admin:22 - cid:[K076MX3K1S5KYCF9SVHSAENXHJA2], name:[zato.http-soap.create], response:[{"zato_http_soap_create_response": {"id": 536, "name": "Get Client Details"}}]
    2015-03-04 20:42:41,755 - INFO - 1380:Dummy-372 - zato_admin:22 - cid:[K076MX3K1S5KYCF9SVHSAENXHJA2], name:[zato.service.invoke], response:[{"zato_service_invoke_response": {"response": "eyJ6YXRvX2h0dHBfc29hcF9jcmVhdGVfcmVzcG9uc2UiOiB7ImlkIjogNTM2LCAibmFtZSI6ICJH\nZXQgQ2xpZW50IERldGFpbHMifX0=\n"}}]

**Comment by dsuch** [comment]
Thanks @Cito - this is at least partially related to #377 and the fix for that other ticket dealt with the Chrome-related part.

However, for FF - thanks for admin.log but can you also please send across the contents of server.log at the time you see the traceback (I forgot to ask about it on the list where you originally reported it all).

Thanks a lot.

**Comment by Cito** [comment]
Will do so, but can only come back to this next week.

**Comment by Cito** [comment]
Ok, I have looked into this again, and found the problem in the server.log. It contained the proper error message ``Service [my-service.get-glient-details] does not exist on this cluster``, and then some followup tracebacks.

So sorry for creating confusion. it was not caused by Firefox but by a silly typo in the service name that I entered in the "Create new channel" dialog when I tried with Firefox. The form field history of Firefox always suggested that misspelled name and I didn't notice it and believed it was a Firefox issue. I have now checked that Chrome gives the same error message when entering a non-existing service, and that both Chrome and Firefox work if I enter the correct service name.

However, what should really be improved is the error message presented in the webadmin which did not give me a clue that I just made a typo in the service name but looked more like something was fundamentally broken.

**Comment by dsuch** [comment]
Thanks @Cito - so probably everything would be good if:

* We had auto-completion for services
* Error messages were clearer

What do you think?

**Comment by Cito** [comment]
Exactly, that would solve the problem.

Maybe the "Method" field should also be a select or auto-complete field.

**Comment by dsuch** [comment]
This is done in git master and will be released in 2.1 - instead of auto-completion a select box is shown with a list of services to chose one from.

Thanks @Cito !

**Comment by Cito** [comment]
Just checked it out, works nicely - but I do not have many service definitions yet. At some point, an auto-complete field will be better.
