### ISSUE TITLE
When database or redis restart zato server going craizy

### ISSUE THREAD

**Issue by wbar** [zatosource/zato#394]
When database or Redis restarts ZATO server throws many unexpected errors like:
```
2015-03-16 14:34:39,034 - ERROR - 10720:Dummy-309 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'102200', cid=u'K07CHTSHCPQ2MG0B3XNT5ZPRPVBQ', data_format=u'json', msg_type=u'0002', package_id=4055L, payload={u'package_id': 4055L}, service=u'zato.hot-deploy.create')], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.2/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/2.0.2/zato-server/src/zato/server/base/worker.py", line 1187, in on_broker_msg_HOT_DEPLOY_CREATE
    return self._on_message_invoke_service(msg, 'hot-deploy', 'HOT_DEPLOY_CREATE', args)
  File "/opt/zato/2.0.2/zato-server/src/zato/server/base/worker.py", line 1003, in _on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/2.0.2/zato-server/src/zato/server/service/__init__.py", line 423, in update_handle
    raise e
TypeError: 'NoneType' object is not iterable
]
```
or

```
2015-03-16 14:34:39,033 - ERROR - 10720:Dummy-309 - zato.server.odb:22 - Could not add service, name:[urn:dtag:base:falcon-esb-service], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.2/zato-server/src/zato/server/odb.py", line 195, in add_service
    self._session.commit()
  File "/opt/zato/2.0.2/eggs/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "/opt/zato/2.0.2/eggs/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 368, in commit
    self._assert_active(prepared_ok=True)
  File "/opt/zato/2.0.2/eggs/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 214, in _assert_active
    "This Session's transaction has been rolled back "
InvalidRequestError: This Session's transaction has been rolled back by a nested rollback() call.  To begin a new transaction, issue Session.rollback() first.
]
```

**Comment by dsuch** [comment]
Exceptions can be expected when either Redis or ODB are down, this is a natural sign.

Or are you saying you can see the same when they are back?

**Comment by wbar** [comment]
I mean that after restart of PostgreSQL ZATO throws those exception without handling for example reestablishment the connection pool
