### ISSUE TITLE
AttributeError: 'WorkerStore' object has no attribute 'sql_pool_store' when using service to deploy service

### ISSUE THREAD

**Issue by wbar** [zatosource/zato#396]
Sometimes, when using a service to hot-deploy:

```
2015-03-16 16:23:50,212 - ERROR - 24956:Dummy-14 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'102200', cid=u'K04BVRV1FPA3Z9ZNP5PG51T3NAMS', data_format=u'json', msg_type=u'0002', package_id=4173L, payload={u'package_id': 4173L}, service=u'zato.hot-deploy.create')], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.2/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/2.0.2/zato-server/src/zato/server/base/worker.py", line 1187, in on_broker_msg_HOT_DEPLOY_CREATE
    return self._on_message_invoke_service(msg, 'hot-deploy', 'HOT_DEPLOY_CREATE', args)
  File "/opt/zato/2.0.2/zato-server/src/zato/server/base/worker.py", line 1003, in _on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/2.0.2/zato-server/src/zato/server/service/__init__.py", line 389, in update_handle
    environ=kwargs.get('environ'))
  File "/opt/zato/2.0.2/zato-server/src/zato/server/service/__init__.py", line 830, in update
    service._init()
  File "/opt/zato/2.0.2/zato-server/src/zato/server/service/__init__.py", line 273, in _init
    out_sql = self.worker_store.sql_pool_store
AttributeError: 'WorkerStore' object has no attribute 'sql_pool_store'
]
```

**Comment by dsuch** [comment]
What does it mean 'when using service to deploy service'? What is the input? Is the situation reproducible?

You said in #394 that you restarted PostgreSQL, is that related? Did you restart servers after restarting Postgres?

**Comment by wbar** [comment]
Yes

**Comment by dsuch** [comment]
Sorry @wbar - yes to which question?

**Comment by wbar** [comment]
Duplicate of #395
