### ISSUE TITLE
Bring zato-common and zato-client up to date

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#397]
As reported on the mailing list, both zato-common and zato-client need to be updated so they cleanly install under pip and virtualenv:

https://mailman-mail5.webfaction.com/pipermail/zato-discuss/2015-March/000950.html

**Comment by dsuch** [comment]
```bash
~/tmp/gh397-zato-client-common$ virtualenv .
New python executable in ./bin/python
Installing distribute...........................................................................................................................................................................................................................done.
Installing pip................done.
~/tmp/gh397-zato-client-common$ ./bin/pip install ~/projects/zatosource-zato/code/zato-common
Unpacking /home/dsuch/projects/zatosource-zato/code/zato-common
  Running setup.py egg_info for package from file:///home/dsuch/projects/zatosource-zato/code/zato-common
    
Downloading/unpacking alembic==0.6.5 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading alembic-0.6.5.tar.gz (461kB): 461kB downloaded
  Running setup.py egg_info for package alembic
    
    warning: no files found matching '*.jpg' under directory 'docs'
    warning: no files found matching '*.sty' under directory 'docs'
    warning: no files found matching '*.dat' under directory 'tests'
    warning: no files found matching 'distribute_setup.py'
    no previously-included directories found matching 'docs/build/output'
Downloading/unpacking anyjson==0.3.3 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading anyjson-0.3.3.tar.gz
  Running setup.py egg_info for package anyjson
    
Downloading/unpacking base32-crockford==0.2.0 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading base32-crockford-0.2.0.tar.gz
  Running setup.py egg_info for package base32-crockford
    
Downloading/unpacking bunch==1.0.1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading bunch-1.0.1.tar.gz
  Running setup.py egg_info for package bunch
    
Downloading/unpacking ConcurrentLogHandler==0.9.1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading ConcurrentLogHandler-0.9.1.tar.gz
  Running setup.py egg_info for package ConcurrentLogHandler
    Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-0.7.7.tar.gz
    Extracting in /tmp/tmpzSpVM6
    Now working in /tmp/tmpzSpVM6/setuptools-0.7.7
    Building a Setuptools egg in /home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler
    /home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler/setuptools-0.7.7-py2.7.egg
    
Downloading/unpacking configobj==5.0.5 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading configobj-5.0.5.tar.gz
  Running setup.py egg_info for package configobj
    
Downloading/unpacking bzr==2.6 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading bzr-2.6.0.tar.gz (11.3MB): 11.3MB downloaded
  Running setup.py egg_info for package bzr
    No Cython, trying Pyrex...
    
    The python package 'Pyrex' is not available. If the .c files are available,
    they will be built, but modifying the .pyx files will not rebuild them.
    
    
Downloading/unpacking distutils2==1.0a4 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading Distutils2-1.0a4.tar.gz (894kB): 894kB downloaded
  Running setup.py egg_info for package distutils2
    
Downloading/unpacking gevent==1.0 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading gevent-1.0.tar.gz (1.4MB): 1.4MB downloaded
  Running setup.py egg_info for package gevent
    
Downloading/unpacking lxml==3.3.5 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading lxml-3.3.5.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py egg_info for package lxml
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.3.5.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    
    warning: no previously-included files found matching '*.py'
Downloading/unpacking mock==1.0.1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading mock-1.0.1.tar.gz (818kB): 818kB downloaded
  Running setup.py egg_info for package mock
    
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
Downloading/unpacking nose==1.3.3 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading nose-1.3.3.tar.gz (274kB): 274kB downloaded
  Running setup.py egg_info for package nose
    
    no previously-included directories found matching 'doc/.build'
Downloading/unpacking Paste==1.7.5.1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading Paste-1.7.5.1.tar.gz (523kB): 523kB downloaded
  Running setup.py egg_info for package Paste
    
    warning: no previously-included files matching '*' found under directory 'docs/_build/_sources'
Downloading/unpacking pip==1.5.2 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading pip-1.5.2.tar.gz (1.1MB): 1.1MB downloaded
  Running setup.py egg_info for package pip
    
    warning: no files found matching 'pip/cacert.pem'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no previously-included files matching '*.rst' found under directory 'docs/_build'
    no previously-included directories found matching 'docs/_build/_sources'
Downloading/unpacking psutil==2.1.0 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading psutil-2.1.0.tar.gz (211kB): 211kB downloaded
  Running setup.py egg_info for package psutil
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking pyOpenSSL==0.14 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading pyOpenSSL-0.14.tar.gz (128kB): 128kB downloaded
  Running setup.py egg_info for package pyOpenSSL
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
Downloading/unpacking python-dateutil==2.2 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading python-dateutil-2.2.tar.gz (259kB): 259kB downloaded
  Running setup.py egg_info for package python-dateutil
    
Downloading/unpacking pytz==2014.4 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading pytz-2014.4.tar.bz2 (159kB): 159kB downloaded
  Running setup.py egg_info for package pytz
    
Downloading/unpacking pyzmq==2.2.0.1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading pyzmq-2.2.0.1.tar.gz (789kB): 789kB downloaded
  Running setup.py egg_info for package pyzmq
    
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/gh-pages'
    warning: no previously-included files found matching 'bundled/uuid/Makefile*'
    warning: no previously-included files found matching 'bundled/zeromq/src/Makefile*'
    warning: no previously-included files found matching 'bundled/zeromq/src/platform.hpp'
    warning: no previously-included files found matching 'setup.cfg'
    warning: no previously-included files found matching 'zmq/libzmq*'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '.mailmap' found anywhere in distribution
Downloading/unpacking pyzmq-static==2.2 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading pyzmq-static-2.2.tar.gz
  Running setup.py egg_info for package pyzmq-static
    
Downloading/unpacking redis==2.9.1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading redis-2.9.1.tar.gz (62kB): 62kB downloaded
  Running setup.py egg_info for package redis
    
    warning: no previously-included files found matching '__pycache__'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
Downloading/unpacking requests==2.6.0 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading requests-2.6.0.tar.gz (450kB): 450kB downloaded
  Running setup.py egg_info for package requests
    
Downloading/unpacking springpython==1.3.0RC1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading springpython-1.3.0.RC1.tar.gz (99kB): 99kB downloaded
  Running setup.py egg_info for package springpython
    
Downloading/unpacking SQLAlchemy==0.9.4 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading SQLAlchemy-0.9.4.tar.gz (4.5MB): 4.5MB downloaded
  Running setup.py egg_info for package SQLAlchemy
    
    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking texttable==0.8.1 (from zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading texttable-0.8.1.tar.gz
  Running setup.py egg_info for package texttable
    
Downloading/unpacking Mako (from alembic==0.6.5->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading Mako-1.0.1.tar.gz (473kB): 473kB downloaded
  Running setup.py egg_info for package Mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking six (from configobj==5.0.5->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading six-1.9.0.tar.gz
  Running setup.py egg_info for package six
    
    no previously-included directories found matching 'documentation/_build'
Downloading/unpacking greenlet (from gevent==1.0->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading greenlet-0.4.5.zip (77kB): 77kB downloaded
  Running setup.py egg_info for package greenlet
    
Downloading/unpacking cryptography>=0.2.1 (from pyOpenSSL==0.14->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading cryptography-0.8.tar.gz (268kB): 268kB downloaded
  Running setup.py egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking MarkupSafe>=0.9.2 (from Mako->alembic==0.6.5->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py egg_info for package MarkupSafe
    
Downloading/unpacking pyasn1 (from cryptography>=0.2.1->pyOpenSSL==0.14->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading pyasn1-0.1.7.tar.gz (68kB): 68kB downloaded
  Running setup.py egg_info for package pyasn1
    
Requirement already satisfied (use --upgrade to upgrade): distribute in ./lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg (from cryptography>=0.2.1->pyOpenSSL==0.14->zato-common==2.0.3-local-TEMP-DSUCH)
Downloading/unpacking enum34 (from cryptography>=0.2.1->pyOpenSSL==0.14->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading enum34-1.0.4.tar.gz
  Running setup.py egg_info for package enum34
    
Downloading/unpacking cffi>=0.8 (from cryptography>=0.2.1->pyOpenSSL==0.14->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading cffi-0.9.2.tar.gz (209kB): 209kB downloaded
  Running setup.py egg_info for package cffi
    
Downloading/unpacking pycparser (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL==0.14->zato-common==2.0.3-local-TEMP-DSUCH)
  Downloading pycparser-2.10.tar.gz (206kB): 206kB downloaded
  Running setup.py egg_info for package pycparser
    
Installing collected packages: alembic, anyjson, base32-crockford, bunch, ConcurrentLogHandler, configobj, bzr, distutils2, gevent, lxml, mock, nose, Paste, pip, psutil, pyOpenSSL, python-dateutil, pytz, pyzmq, pyzmq-static, redis, requests, springpython, SQLAlchemy, texttable, zato-common, Mako, six, greenlet, cryptography, MarkupSafe, pyasn1, enum34, cffi, pycparser
  Running setup.py install for alembic
    
    warning: no files found matching '*.jpg' under directory 'docs'
    warning: no files found matching '*.sty' under directory 'docs'
    warning: no files found matching '*.dat' under directory 'tests'
    warning: no files found matching 'distribute_setup.py'
    no previously-included directories found matching 'docs/build/output'
    Installing alembic script to /home/dsuch/tmp/gh397-zato-client-common/bin
  Running setup.py install for anyjson
    
  Running setup.py install for base32-crockford
    
  Running setup.py install for bunch
    
  Running setup.py install for ConcurrentLogHandler
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler/setup.py", line 235, in <module>
        use_setuptools()
      File "ez_setup.py", line 118, in use_setuptools
        pkg_resources.require("setuptools>=" + version)
      File "/home/dsuch/tmp/gh397-zato-client-common/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 699, in require
        self.add(dist)
      File "/home/dsuch/tmp/gh397-zato-client-common/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 538, in add
        dist.insert_on(self.entries, entry)
      File "/home/dsuch/tmp/gh397-zato-client-common/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2356, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler/setuptools-0.7.7-py2.7.egg
    Complete output from command /home/dsuch/tmp/gh397-zato-client-common/bin/python -c "import setuptools;__file__='/home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qmiO25-record/install-record.txt --single-version-externally-managed --install-headers /home/dsuch/tmp/gh397-zato-client-common/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler/setup.py", line 235, in <module>

    use_setuptools()

  File "ez_setup.py", line 118, in use_setuptools

    pkg_resources.require("setuptools>=" + version)

  File "/home/dsuch/tmp/gh397-zato-client-common/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 699, in require

    self.add(dist)

  File "/home/dsuch/tmp/gh397-zato-client-common/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 538, in add

    dist.insert_on(self.entries, entry)

  File "/home/dsuch/tmp/gh397-zato-client-common/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2356, in insert_on

    "with distribute. Found one at %s" % str(self.location))

ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler/setuptools-0.7.7-py2.7.egg

----------------------------------------
Command /home/dsuch/tmp/gh397-zato-client-common/bin/python -c "import setuptools;__file__='/home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qmiO25-record/install-record.txt --single-version-externally-managed --install-headers /home/dsuch/tmp/gh397-zato-client-common/include/site/python2.7 failed with error code 1 in /home/dsuch/tmp/gh397-zato-client-common/build/ConcurrentLogHandler
Storing complete log in /home/dsuch/.pip/pip.log
~/tmp/gh397-zato-client-common$ 

```

**Comment by aek** [comment]
Hi Dariuz
I strugle into this a little. ConcurrentLogHandler when installed using pip seems to be using:
https://pypi.python.org/packages/source/C/ConcurrentLogHandler/ConcurrentLogHandler-0.9.1.tar.gz#md5=9609ecc4c269ac43f0837d89f12554c3
to install it and in that archive, the setup.py is using ez_setup with the hardcoded dependency with setuptools 0.7.7
I think that you should simply get the proper egg from:
https://pypi.python.org/packages/2.7/C/ConcurrentLogHandler/ConcurrentLogHandler-0.9.1-py2.7.egg#md5=784d26d945417274a8ba92c5c5a8d273
and using it like the rest of eggs in zato, that could solve the problem

Cheers

**Comment by dsuch** [comment]
Thanks @aek - but I have a line like here below - how can I point it to this exact version?

```python
      install_requires=[
          'alembic==0.6.5',      install_requires=[
          'alembic==0.6.5',
          'anyjson==0.3.3',
          'base32-crockford==0.2.0',
          'bunch==1.0.1',
          'ConcurrentLogHandler==0.9.1',
          'anyjson==0.3.3',
          'base32-crockford==0.2.0',
          'bunch==1.0.1',
          'ConcurrentLogHandler==0.9.1',
```

**Comment by aek** [comment]
pip doesn’t do everything that easy_install does. Specifically: It cannot install from eggs. It only installs from source. 
Then you have three options here:
First one is to fork ConcurrentLogHandler to alter setup.py and then point the require to your fork on pypy or in a repo like github, bitbucket using the url syntax. 
The second one is that I told you before, just make zato to ship with the egg version.
The last one is to use easy_install or any other deployment method to install the dependency

By the way I use fabric to do my deployments,

**Comment by dsuch** [comment]
I guess forking it shall be - but how do you mean shipping with the egg?

The original question from the mailing list was about installing zato-client and zato-common under virtualenv from PyPI?

**Comment by dsuch** [comment]
Closing, thanks for everyone's help.
