### ISSUE TITLE
server start fails if odb schema already exists on quickstart creation

### ISSUE THREAD

**Issue by pedrudehuere** [zatosource/zato#442]
Hello,

when creating a quickstart cluster with mysql as odb and the schema has already been used by an older cluster (installed in the same directory as the new one) I got this

```
[1/7] Certificate authority created
[2/7] ODB schema already exists
Cluster name [dev_cluster1] already exists
[3/7] ODB initial data created
Server name [server1] already exists  # <-- he knows, but it looks like he's OK with it
[4/7] server1 created
[5/7] Load-balancer created
[6/7] Web admin created
[7/7] Management scripts created
Quickstart cluster dev_cluster1 created
User [admin] already exists in the ODB
Start the cluster by issuing the /home/altux/zato_test_env/zato-qs-start.sh command
Visit https://zato.io/support for more information and support options
```

When I start the server in fg

```
~/zato_test_env$ zato start server1 --fg
2015-05-07 09:55:14,885 - INFO - 5660:MainThread - zato.common.repo:22 - Location [/home/altux/zato_test_env/server1/config/repo] is not a Bazaar branch. Will turn it into one.
2015-05-07 09:55:15 [5660] [INFO] Starting gunicorn 18.0
2015-05-07 09:55:15,715 - INFO - 5660:Dummy-1 - gunicorn.main:22 - Starting gunicorn 18.0
2015-05-07 09:55:15 [5660] [INFO] Listening at: http://127.0.0.1:17010 (5660)
2015-05-07 09:55:15,719 - INFO - 5660:Dummy-1 - gunicorn.main:22 - Listening at: http://127.0.0.1:17010 (5660)
2015-05-07 09:55:15 [5660] [INFO] Using worker: gevent
2015-05-07 09:55:15,720 - INFO - 5660:Dummy-1 - gunicorn.main:22 - Using worker: gevent
2015-05-07 09:55:15 [5667] [INFO] Booting worker with pid: 5667
2015-05-07 09:55:15,724 - INFO - 5667:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 5667
2015-05-07 09:55:15 [5668] [INFO] Booting worker with pid: 5668
2015-05-07 09:55:15,804 - INFO - 5668:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 5668
2015-05-07 09:55:16,257 - ERROR - 5667:Dummy-1 - zato.server.odb:22 - Could not find the server in the ODB, token:[9d2a8ca550f44e4ca7ec8fb929554ba5]
2015-05-07 09:55:16 [5667] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
2015-05-07 09:55:16,259 - ERROR - 5667:Dummy-1 - gunicorn.main:22 - Exception in worker process:
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
2015-05-07 09:55:16 [5667] [INFO] Worker exiting (pid: 5667)
2015-05-07 09:55:16,259 - INFO - 5667:Dummy-1 - gunicorn.main:22 - Worker exiting (pid: 5667)
2015-05-07 09:55:16,366 - ERROR - 5668:Dummy-1 - zato.server.odb:22 - Could not find the server in the ODB, token:[9d2a8ca550f44e4ca7ec8fb929554ba5]
2015-05-07 09:55:16 [5668] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
2015-05-07 09:55:16,367 - ERROR - 5668:Dummy-1 - gunicorn.main:22 - Exception in worker process:
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 834, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 787, in start_server
    server = parallel_server.odb.fetch_server(parallel_server.config.odb_data)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 74, in fetch_server
    filter(Server.token == self.token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
2015-05-07 09:55:16 [5668] [INFO] Worker exiting (pid: 5668)
2015-05-07 09:55:16,368 - INFO - 5668:Dummy-1 - gunicorn.main:22 - Worker exiting (pid: 5668)
2015-05-07 09:55:16 [5660] [INFO] Shutting down: Master
2015-05-07 09:55:16,524 - INFO - 5660:Dummy-1 - gunicorn.main:22 - Shutting down: Master
2015-05-07 09:55:16 [5660] [INFO] Reason: Worker failed to boot.
2015-05-07 09:55:16,525 - INFO - 5660:Dummy-1 - gunicorn.main:22 - Reason: Worker failed to boot.
2015-05-07 09:55:16,991 - ERROR - 5660:Dummy-2 - springpython.context.ApplicationContext:22 - Could not destroy object 'parallel_server', exception 'Traceback (most recent call last):
  File "/home/altux/zato-2.0.3/code/eggs/springpython-1.3.0rc1-py2.7.egg/springpython/context/__init__.py", line 106, in shutdown_hook
    destroy_method()
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/base/parallel.py", line 886, in destroy
    self.odb.server_up_down(self.odb.token, SERVER_UP_STATUS.CLEAN_DOWN)
  File "/home/altux/zato-2.0.3/code/zato-server/src/zato/server/odb.py", line 91, in server_up_down
    filter(Server.token==token).\
  File "/home/altux/zato-2.0.3/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
'
OK
```

I think there is an issue with the usage of the old database, now I don't know how important it is to keep already existing component in the database, maybe it would be better to just whipe the DB (or display a message which says that the schema already exists, like when the directory is not empty).

Cheers!

**Comment by halitalptekin** [comment]
If you change "https://github.com/zatosource/zato/blob/main/code/zato-cli/src/zato/cli/create_server.py#L411" line with the "**server.cluster = cluster**" , problem will be solved. 

In the ipython shell:

```
...

In [12]: s.query(Cluster).all()[0].id        
Out[12]: 1

In [13]: s.query(Cluster).all()[0].name
Out[13]: u'test-cluster'

In [14]: server = Server()

In [15]: server.cluster_id  = 1

In [16]: server.name = 'test-server'

In [17]: server.token = '1231231231321'

In [18]: s.add(server)

In [19]: s.commit()
...

IntegrityError: (psycopg2.IntegrityError) null value in column "cluster_id" violates not-null constraint
DETAIL:  Failing row contains (11, dsadasdas, null, null, null, null, null, null, null, null, null, null, 1231231231321, null).
 [SQL: "INSERT INTO server (id, name, host, bind_host, bind_port, preferred_address, crypto_use_tls, last_join_status, last_join_mod_date, last_join_mod_by, up_status, up_mod_date, token, cluster_id) VALUES (nextval('server_id_seq'), %(name)s, %(host)s, %(bind_host)s, %(bind_port)s, %(preferred_address)s, %(crypto_use_tls)s, %(last_join_status)s, %(last_join_mod_date)s, %(last_join_mod_by)s, %(up_status)s, %(up_mod_date)s, %(token)s, %(cluster_id)s) RETURNING server.id"] [parameters: {'name': 'test-server', 'bind_host': None, 'bind_port': None, 'last_join_status': None, 'host': None, 'up_status': None, 'up_mod_date': None, 'preferred_address': None, 'cluster_id': None, 'token': '1231231231321', 'last_join_mod_by': None, 'crypto_use_tls': None, 'last_join_mod_date': None}]

...

In [31]: server = Server()

In [32]: server.name = 'test-server'

In [33]: server.token = '1231231231321'

In [34]: server.cluster = s.query(Cluster).all()[0] # or just cluster

In [35]: s.add(server)

In [36]: s.commit()

In [37]: 

# now i can see server on the web-admin

**Comment by dsuch** [comment]
Thanks @halitalptekin - let me check it out and report back as soon as I can!
