### ISSUE TITLE
Quickstart create fails on PostgreSQL

### ISSUE THREAD

**Issue by ncadou** [zatosource/zato#469]
This command fails:

``` shell
zato quickstart create . postgresql localhost 6379 --kvdb_password '' \
    --odb_host 172.17.42.77 --odb_port 5432 --odb_user postgres --odb_password '' \
    --odb_db_name zato --postgresql_schema public --verbose
```

... and gives out this:

```
[1/8] Certificate authority created
[2/8] ODB schema created
[3/8] ODB initial data created
[4/8] server1 created
[5/8] server2 created
[6/8] Load-balancer created
Traceback (most recent call last):
  File "/opt/zato/2.0/bin/zato", line 181, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/quickstart.py", line 347, in execute
    create_web_admin_args, False, password, True)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/create_web_admin.py", line 134, in execute
    update_globals(config, self.target_dir)
  File "/opt/zato/2.0.5/zato-web-admin/src/zato/admin/zato_settings.py", line 32, in update_globals
    v = decrypt(v, priv_key)
  File "/opt/zato/2.0.5/zato-common/src/zato/common/util.py", line 172, in decrypt
    return cm.decrypt(data, b64)
  File "/opt/zato/2.0.5/zato-common/src/zato/common/crypto.py", line 64, in decrypt
    return rsa.decrypt(data, self.priv_key)
  File "/opt/zato/2.0.5/eggs/rsa-3.1.2-py2.7.egg/rsa/pkcs1.py", line 226, in decrypt
    encrypted = transform.bytes2int(crypto)
  File "/opt/zato/2.0.5/eggs/rsa-3.1.2-py2.7.egg/rsa/transform.py", line 51, in bytes2int
    return int(binascii.hexlify(raw_bytes), 16)
ValueError: invalid literal for int() with base 16: ''
```

**Comment by dsuch** [comment]
@ncadou - is it reproducible a few times in a row?

I can't quite repeat it here locally?

**Comment by ncadou** [comment]
I happens every time. It's interesting it works for you though, that's a hint the problem might lie with my particular stack. I'll try to narrow it down to something reproducible.

**Comment by dsuch** [comment]
Ok, and what does ```tree .``` show right after the exception? There is something going on when attempting to read contents of one of the crypto files but I'm not sure which one it is.

**Comment by merwok** [comment]
I can reproduce the error.  FWIW this is from a docker container.

From this part of the traceback:
```
  File "/opt/zato/2.0.5/zato-web-admin/src/zato/admin/zato_settings.py", line 32, in update_globals
    v = decrypt(v, priv_key)
```
I find that the file causing the error is web-admin/config/repo/web-admin-priv-key.pem, which is present and seems well-formed.  Looking again at the code chain and the ValueError with an empty string, I think the issue is that we want to use an empty password, and zato or the rsa module is not prepared to handle that.

**Comment by dsuch** [comment]
Hello @merwok and @ncadou - can you please advise how we go about this ticket? Can it be closed? Thanks.

**Comment by merwok** [comment]
Did you try the advice in my last comment?  (not calling rsa.decrypt in zato.common.decrypt for empty values)

**Comment by dsuch** [comment]
Thanks @merwok - question is, why do you need an empty priv_key? Why does it need to have an empty value?

**Comment by merwok** [comment]
We would like to create the database without a password.

**Comment by dsuch** [comment]
Closing due to inactivity - feel free to reopen if this is still needed.
