### ISSUE TITLE
DatabaseError when creating Zato quickstart with Oracle Database 11g XE

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#473]
After executing:

`zato quickstart create --odb_host 10.2.3.99 --odb_port 1521 --odb_user system --odb_db_name XE --odb_password Password123 --kvdb_password '' /opt/zato/env/qs-1 oracle localhost 6379`

I get the following error:

`DatabaseError: (DatabaseError) ORA-02261: such unique or primary key
already exists in the table`

I attempt to create quickstart on Ubuntu 14.04 64-bit box. Oracle db is installed on Oracle Linux 7 64-bit.

Full traceback:

```
zato@ubuntu-1404-64:~/env/qs-1$ zato quickstart create --odb_host 10.2.3.99 --odb_port 1521 
--odb_user zato1 --odb_db_name XE --odb_password zato1 --kvdb_password '' /opt/zato/env/qs-1 oracle localhost 6379
[1/8] Certificate authority created
Traceback (most recent call last):
File "/opt/zato/2.0.5/bin/zato", line 181, in <module>
sys.exit(zato.cli.zato_command.main())
File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
return run_command(get_parser().parse_args())
File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
command_class[args.command](args).run(args)
File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
return_code = self.execute(args)
File "/opt/zato/2.0.5/zato-cli/src/zato/cli/quickstart.py", line 273, in execute
if create_odb.Create(args).execute(args, False) == self.SYS_ERROR.ODB_EXISTS:
File "/opt/zato/2.0.5/zato-cli/src/zato/cli/create_odb.py", line 44, in execute
Base.metadata.create_all(engine)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 3420, in create_all
tables=tables)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1728, in _run_visitor
conn._run_visitor(visitorcallable, element, **kwargs)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1357, in _run_visitor
**kwargs).traverse_single(element)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 120, in traverse_single
return meth(obj, **kw)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 713, in visit_metadata
self.traverse_single(table, create_ok=True)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 120, in traverse_single
return meth(obj, **kw)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 732, in visit_table
self.connection.execute(CreateTable(table))
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 841, in execute
return meth(self, multiparams, params)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
return connection._execute_ddl(self, multiparams, params)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 895, in _execute_ddl
compiled
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1070, in _execute_context
context)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
exc_info
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1063, in _execute_context
context)
File "/opt/zato/2.0.5/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 442, in do_execute
cursor.execute(statement, parameters)
DatabaseError: (DatabaseError) ORA-02261: such unique or primary key already exists in the table
'\nCREATE TABLE deployed_service (\n\tdeployment_time DATE NOT NULL, \n\tdetails VARCHAR2(2000 CHAR) NOT NULL, \n\tsource BLOB, 
\n\tsource_path VARCHAR2(2000 CHAR), \n\tsource_hash VARCHAR2(512 CHAR), \n\tsource_hash_method VARCHAR2(20 CHAR), \n\tserver_id INTEGER NOT NULL, 
\n\tservice_id INTEGER NOT NULL, \n\tPRIMARY KEY (server_id, service_id), \n\tUNIQUE (server_id, service_id), 
\n\tFOREIGN KEY(server_id) REFERENCES server (id) ON DELETE CASCADE, \n\tFOREIGN KEY(service_id) REFERENCES service (id) ON DELETE CASCADE\n)\n\n' {}

zato@ubuntu-1404-64:~/env/qs-1$
```

**Comment by Adniel** [comment]
@rafal-k: Did you find the reason for this? I am experiencing the same error now when trying to create a quickstart cluster on Oracle 11.2.0.2 XE.
