### ISSUE TITLE
HSET: "Expected 'CONFIG'"

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#478]
As reported on IRC:

```
Traceback (most recent call last):
  File "/opt/zato/2.0.5/zato-web-admin/src/zato/admin/web/views/kvdb/__init__.py", line 44, in remote_command_execute
    response = req.zato.client.invoke('zato.kvdb.remote-command.execute', {'command': req.POST['command']})
  File "/opt/zato/2.0.5/zato-web-admin/src/zato/admin/middleware.py", line 72, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: K053C9K58YT2P8BM9AXBJ6RH5BS6
Details: Traceback (most recent call last):
  File "/opt/zato/2.0.5/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/opt/zato/2.0.5/zato-server/src/zato/server/connection/http_soap/channel.py", line 351, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 433, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke
    service.handle()
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/internal/service.py", line 271, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 499, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 483, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 428, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke
    service.handle()
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/internal/kvdb/__init__.py", line 87, in handle
    raise ZatoException(self.cid, msg)
ZatoException: Command parsing error, command:[HSET myhash field1 "Hello"], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.5/zato-server/src/zato/server/service/internal/kvdb/__init__.py", line 62, in handle
    parse_result = redis_grammar.parseString(input_command)
  File "/opt/zato/2.0.5/eggs/pyparsing-2.0.1-py2.7.egg/pyparsing.py", line 1041, in parseString
    raise exc
ParseException: Expected 'CONFIG' (at char 0), (line:1, col:1)
]

```

**Comment by dsuch** [comment]
Done, closing.
