### ISSUE TITLE
Load balancer timing out

### ISSUE THREAD

**Issue by marcoliceti** [zatosource/zato#487]
Hi, I'm experiencing an issue very similar to [this one](https://github.com/zatosource/zato/issues/375).

I'm following the [tutorial](https://zato.io/docs/tutorial/01.html), using Ubuntu 14.04 (no VM!) with both a Zato and a Redis fresh installation.

I've managed to get to the `zato-qs-start.sh` command (which tells me that everything is fine), but when I ping the load balancer, i.e.:

``` bash
curl localhost:11223/zato/ping ; echo
```

(after a while) I get this output:

``` html
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

Tips? :-[

**Comment by dsuch** [comment]
Hi @marcoliceti !

What happens when you execute:

```bash
$ curl localhost:17010/zato/ping ; echo
$ curl localhost:17011/zato/ping ; echo
```

?

**Comment by marcoliceti** [comment]
Hi, thanks for the quick reply.

`curl` on ports 17010 and 17011 keeps me waiting even more. Actually I've killed it after a couple of minutes.

The web-admin console (i.e. localhost:8183), instead, seems to be working. When I select the "Clusters" tab, it gives me this output:

```
quickstart-98405 
Created by zato@marco-lenovo on 2015-10-14T10:21:29.900477 (UTC)

Could not fetch the load balancer's configuration
```

**Comment by dsuch** [comment]
> curl on ports 17010 and 17011 keeps me waiting even more.
> Actually I've killed it after a couple of minutes.

Right, OK, so this is something to do with servers. A request goes to web admin -> LB -> servers.

Now, can you please stop both servers, then run:

```bash
$ zato start /path/to/server1 --fg
```

This will start it in foreground - let's find out what it says and how long it takes to start up.

Thanks!

**Comment by marcoliceti** [comment]
```
2015-10-14 12:50:36 [16317] [INFO] Starting gunicorn 18.0
2015-10-14 12:50:36,216 - INFO - 16317:Dummy-1 - gunicorn.main:22 - Starting gunicorn 18.0
2015-10-14 12:50:36 [16317] [INFO] Listening at: http://127.0.0.1:17010 (16317)
2015-10-14 12:50:36,223 - INFO - 16317:Dummy-1 - gunicorn.main:22 - Listening at: http://127.0.0.1:17010 (16317)
2015-10-14 12:50:36 [16317] [INFO] Using worker: gevent
2015-10-14 12:50:36,224 - INFO - 16317:Dummy-1 - gunicorn.main:22 - Using worker: gevent
2015-10-14 12:50:36 [16324] [INFO] Booting worker with pid: 16324
2015-10-14 12:50:36,231 - INFO - 16324:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 16324
2015-10-14 12:50:36 [16325] [INFO] Booting worker with pid: 16325
2015-10-14 12:50:36,250 - INFO - 16325:Dummy-1 - gunicorn.main:22 - Booting worker with pid: 16325
```

**Comment by marcoliceti** [comment]
Ok, after a while, I've got this additional output:

```
2015-10-14 12:52:50,893 - INFO - 16324:Dummy-1 - zato.server.odb:22 - Server id:[1], name:[server1] is now a connector server for cluster id:[1], name:[quickstart-827128]
2015-10-14 12:52:50,894 - INFO - 16324:Dummy-1 - zato.server.base.parallel:22 - Initializing connectors
2015-10-14 12:52:50,897 - INFO - 16324:Dummy-1 - zato.server.base.parallel:22 - No AMQP channels to start
2015-10-14 12:52:50,900 - INFO - 16324:Dummy-1 - zato.server.base.parallel:22 - No AMQP outgoing connections to start
2015-10-14 12:52:50,905 - INFO - 16324:Dummy-1 - zato.server.base.parallel:22 - No JMS WebSphere MQ channels to start
2015-10-14 12:52:50,910 - INFO - 16324:Dummy-1 - zato.server.base.parallel:22 - No JMS WebSphere MQ outgoing connections to start
2015-10-14 12:52:50,914 - INFO - 16324:Dummy-1 - zato.server.base.parallel:22 - No Zero MQ channels to start
2015-10-14 12:52:50,915 - INFO - 16324:Dummy-3 - zato.broker.client:22 - Starting broker client, host:[127.0.0.1], port:[6379], name:[parallel-K04Y1YV73XXSZQP6K3ER3CJ9TYVW], topics:[['/zato/to-parallel/all', '/zato/to-parallel/any', '/zato/to-singleton']]
2015-10-14 12:52:53,465 - INFO - 16325:Dummy-2 - zato.broker.client:22 - Starting broker client, host:[127.0.0.1], port:[6379], name:[parallel-K040H8JMDK324DD3R7VCWBVVKZFC], topics:[['/zato/to-parallel/all', '/zato/to-parallel/any']]
2015-10-14 12:52:54,222 - INFO - 16324:Dummy-8 - zato.helpers.input-logger:800 - {u'impl_name': u'zato.server.service.internal.helpers.InputLogger', u'name': u'zato.helpers.input-logger', u'cid': u'K04A6HS8MA1D2QYRY47YNRVPSB1C', u'invocation_time': datetime.datetime(2015, 10, 14, 10, 52, 54, 221907), u'job_type': None, u'data_format': None, u'slow_threshold': 99999, u'request.payload': u'Sample payload for a startup service (first worker)', u'wsgi_environ': {u'zato.request_ctx.async_msg': Bunch(action=u'101802', channel=u'startup-service', cid=u'K04A6HS8MA1D2QYRY47YNRVPSB1C', msg_type=u'0001', payload=u'Sample payload for a startup service (first worker)', service=u'zato.helpers.input-logger'), u'zato.request_ctx.fanout_cid': None, u'zato.request_ctx.in_reply_to': None, u'zato.request_ctx.parallel_exec_cid': None}, u'environ': {}, u'usage': 1, u'channel': u'startup-service'}
2015-10-14 12:52:54,276 - ERROR - 16325:Dummy-3 - zato.server.connection.http_soap.channel:22 - [K066P968WDDNPRWRDA9YGB1ZYWJ0] Unknown URL:[/] or SOAP action:[]
2015-10-14 12:52:54,302 - ERROR - 16325:Dummy-3 - zato.server.connection.http_soap.channel:22 - [K044X9WKR3MV768WET0HR591TJE7] Unknown URL:[/favicon.ico] or SOAP action:[]
```

**Comment by dsuch** [comment]
Ok, so that server did start up.

What if you now, while keeping it in foreground, curl to localhost:17010/zato/ping?

**Comment by marcoliceti** [comment]
Ok, now I have a successful reply:

```
{"zato_env": {"details": "", "result": "ZATO_OK", "cid": "K05W1V6EXMDYZA2EKH5Q37ZN6809"}, "zato_ping_response": {"pong": "zato"}}
```

I've also tried to stop server1 and perform the same check for the load balancer:

```
zato@marco-lenovo:~$ curl localhost:11223/zato/ping ; echo
{"zato_env":
  {"details": "No server is available to handle the request",
  "result": "ZATO_ERROR",
  "cid": "K012345678901234567890123456"}
}
```

This is good: the load balancer is running... but when I start _both_ the load balancer and a server, the load balancer starts timing out. If I stop the server, the load balancer becomes responsive again.

Is seems like the "handshaking" between load balancer and server somehow blocks the load balancer.

**Comment by dsuch** [comment]
Thanks, what if you now start both servers with the ```--fg``` flag so you can immediately watch what they are doing and then:

``` bash
$ haproxy -Vd -f /path/to/load-balancer/config/repo/zato.config
```

That will start the LB in foreground as well.

And now, please curl to the load-balancer:

```bash
$ curl localhost:11223/zato/ping
```

Everything is foreground so we should have a better insight into what is going on.

**Comment by marcoliceti** [comment]
This time both server1 and the load balancer did work (by "work" I mean that `curl` doesn't time out). I've tried to also start server2 and web-admin. They did work too. It takes several seconds, but eventually they become responsive. Based on the output I get with the `--fg` flag, it seems to me that the bottleneck is the boot of gunicorn workers.

Then I've tried to stop everything and re-start the cluster with the `zato-qs-start.sh` script (instead of individually starting each node with `zato start`). It didn't work: after a long wait, when I curl server1 and server2, I get:

```
curl: (7) Failed to connect to localhost port 17011: Connessione rifiutata
```

So I've tried to individually start server1 and server2, but I get this error:

```
$ zato start server1
Traceback (most recent call last):
  File "/opt/zato/2.0.5/bin/zato", line 181, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 706, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/start.py", line 77, in _on_server
    self.run_check_config()
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/start.py", line 41, in run_check_config
    cc.execute(Bunch(path='.', ensure_no_pidfile=True, check_server_port_available=True))
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 706, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/check_config.py", line 132, in _on_server
    self.ensure_no_pidfile()
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/check_config.py", line 102, in ensure_no_pidfile
    raise Exception('Cannot proceed, found pidfile `{}`'.format(pidfile))
Exception: Cannot proceed, found pidfile `/opt/zato/tutorial/server1/pidfile`
```

But I can't even stop them:

```
$ zato stop server1
Traceback (most recent call last):
  File "/opt/zato/2.0.5/bin/zato", line 181, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 706, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/stop.py", line 44, in _on_server
    self.signal('Server', 'SIGTERM', signal.SIGTERM)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/stop.py", line 38, in signal
    os.kill(pid, signal_code)
OSError: [Errno 3] No such process
```

I've tried also this (before reissuing stop / start commands):

```
$ fuser -k 17010/tcp
$ fuser -k 17011/tcp
```

But it didn't solve the problem.

I've made several attempts to repeat all the steps in the tutorial, each time deleting the previously created cluster and rebooting my machine. It seems that the only reliable way to get the cluster up and running is to start the nodes one by one _and_ with the `--fg` flag (though I don't understand why).

This weekend I'll try with the Macbook I have at home to see if similar issues arise.

**Comment by dsuch** [comment]
Hi @marcoliceti,

if a server or any component is forcibly shut down the pidfiles may left around:

```
Exception: Cannot proceed, found pidfile `/opt/zato/tutorial/server1/pidfile`
```

You just need to delete them manually then. Calling ```zato stop``` won't work because the PIDs the pidfiles point to may not exist or may already be used by other processes.

Seeing as it's only ```zato-qs-start.sh``` that causes it all, my question now is what hardware is it? CPU, disks and RAM?

The ```zato-qs-start.sh``` script is just a thin wrapper around ```zato start``` so if starting several components in parallel introduces timeouts, it means they can't properly start up -> they are waiting for a resource of some sort.

Thanks.

**Comment by dsuch** [comment]
One thing more @marcoliceti - can you make sure the environment is stopped and then ..

* Open server.conf in each server's config/repo directory
* Set main.gunicorn_workers to 1 instead of 2

.. and now use the zato-qs-start.sh script?

There are 2 servers, each with 2 gunicorn workers (OS processes) so that is 4 processes for servers, one for web-admin and one for LB starting simultaneously.

Let's thin in down to 1 worker per server and let's see how it goes then.

Thanks.

**Comment by marcoliceti** [comment]
Ok, lowering the number of gunicorn workers did work :)

P.s. I have an Intel i7 machine with 8GB main memory.

**Comment by ivaano** [comment]
Exception: Cannot proceed, found pidfile `/opt/zato/tutorial/server1/pidfile`
Just remove the pidfile(s) and try again to start the server(s)

**Comment by dsuch** [comment]
Hi @marcoliceti - in 2.0.6 and later quickstart will run 1 gunicorn worker for each server. That will reduce any potential startup congestion hence making the servers boot faster.

Thanks again for your ticket which prompted the change!

**Comment by marcoliceti** [comment]
Thank you for the support!

2015-10-28 10:18 GMT+01:00 Dariusz Suchojad <notifications@github.com>:
