### ISSUE TITLE
Creating unformatted AMQP channel breaks web admin 

### ISSUE THREAD

**Issue by zoop500** [zatosource/zato#490]
Creating an AQMP channel without setting data format breaks the web admin's channel page.

Details:
If user creates an AMQP channel and leaves dataformat open ("-----"), 
next time he opens the same page an error 500 is thrown with traceback information.

Traceback (most recent call last):
File "/opt/zato/2.0.5/zato-web-admin/src/zato/admin/web/views/__init__.py", line 299, in __call__ response = self.invoke_admin_service() File "/opt/zato/2.0.5/zato-web-admin/src/zato/admin/web/views/__init__.py", line 262, in invoke_admin_service return func(self.service_name, self.input) File "/opt/zato/2.0.5/zato-web-admin/src/zato/admin/middleware.py", line 72, in invoke raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details'))) Exception: CID: K06957V2QR0WGZW7JA7JPX757XEJ Details: Traceback (most recent call last): File "/opt/zato/2.0.5/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch payload, worker_store, self.simple_io_config, post_data) File "/opt/zato/2.0.5/zato-server/src/zato/server/connection/http_soap/channel.py", line 351, in handle params_priority=channel_item.params_pri) File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 433, in update_handle raise Exception(exc_formatted) Exception: Traceback (most recent call last): File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle self._invoke(service, channel) File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke service.handle() File "/opt/zato/2.0.5/zato-server/src/zato/server/service/internal/service.py", line 271, in handle response = func(id_, payload, channel, data_format, transport, serialize=True) File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 499, in invoke return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs) File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 483, in invoke_by_impl_name return self.update_handle(*invoke_args, **kwargs) File "/opt/zato/2.0.5/zato-server/src/zato/server/service/__init__.py", line 429, in update_handle raise resp_e ZatoException: Expected elem:[data_format] not found in item:[(['id', 'name', 'is_active', 'queue', 'consumer_tag_prefix', u'def_name', 'def_id', 'data_format', u'service_name', u'service_impl_name'], (1, u'rabbit_chn', True, u'hello', u'zato.hello', u'RMQS', 1, u'', u'harvesting.harvester', u'harvesting.Harvester'

**Comment by dsuch** [comment]
Labelled with 2.0.8 so it will be looked into before the next patch release.

Thanks @zoop500 !

**Comment by dsuch** [comment]
Done in 75682e92f9b8d50e5ed9cd16267947bfa88ddb24 - thanks @zoop500!
