### ISSUE TITLE
AttributeError: 'str' object has no attribute 'pop'

### ISSUE THREAD

**Issue by DimShadoWWW** [zatosource/zato#497]
I'm using zato 2.0.7 in a docker container. With this code (almost exactly like an example) i'm getting "AttributeError: 'str' object has no attribute 'pop'"

```Python
class SearchTerm(Service):
    def handle(self):
        infoget_terms = self.outgoing.plain_http.get('infoget terms')
 
        request = dumps({'name': 'aa'})
        self.logger.info(request)
        response = infoget_terms.conn.get(self.cid, request)
 
        # if not found, create
        if response.status_code == 404:
            response = infoget_terms.conn.post(self.cid, request)
 
        # confirm
        response = infoget_terms.conn.get(self.cid, request)
        self.logger.info(response.headers['content-type'])
        self.logger.info(response.text)
 
 ```

Traceback:

```
Could not invoke the service. name:[loadosm.search-term], cluster_id:[1], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-web-admin/src/zato/admin/web/views/service.py", line 546, in invoke
    response = req.zato.client.invoke(name, **input_dict)
  File "/opt/zato/2.0.7/zato-web-admin/src/zato/admin/middleware.py", line 72, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: K0637M856Z1Y5HN8XZSPYWJWNMSA
Details: Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 350, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke
    service.handle()
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/internal/service.py", line 271, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 499, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 483, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/server2/work/hot-deploy/current/loadosm.py", line 121, in handle
    response = infoget_terms.conn.get(self.cid, request)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 326, in get
    return self.http_request('GET', cid, None, params, *args, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 297, in http_request
    address, qs_params = self.format_address(cid, params)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 222, in format_address
    path_params[name] = params.pop(name)
AttributeError: 'str' object has no attribute 'pop'
 
]
```

**Comment by dsuch** [comment]
This line is unnecessary:

```request = dumps({'name': 'aa'})```

You don't have to serialize requests to string yourself, Zato will do it yourself if in web-admin you'll set the outgoing connection's format to JSON (or XML but not in your case).

The way you have it right now, Zato wants to find what sort of path parameters your provided it in the .get call and it expects for the parameters to be a dictionary while you serialize them to string. Hence no .pop attribute in a string object.

**Comment by dsuch** [comment]
Closing, feel free to reopen if required, thanks @DimShadoWWW !
