### ISSUE TITLE
KVDB - DUMP remote command raises UnicodeDecodeError

### ISSUE THREAD

**Issue by fklosowski** [zatosource/zato#516]
- Zato 2.0.7.rev-dfee180c

Ussing Key/value DB > Remote commands feature in web admin, there is an error raised while **DUMP** command execution.<br>
Steps to reproduce the error:<br>
1. Execute command ```SET key value``` to set the string value of a key.
2. Execute command ```DUMP key``` which is expected to return a serialized verison of the value stored at the specified key.
At this stage the following error message is displayed:<br>

> Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-web-admin/src/zato/admin/web/views/kvdb/__init__.py", line 44, in remote_command_execute
    response = req.zato.client.invoke('zato.kvdb.remote-command.execute', {'command': req.POST['command']})
  File "/opt/zato/2.0.7/zato-web-admin/src/zato/admin/middleware.py", line 72, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: K06GED3ZQJHEDEXPGFQWFCGV3ABD
Details: Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 350, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke
    service.handle()
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/internal/service.py", line 271, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 499, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 483, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 429, in update_handle
    raise resp_e
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 11: invalid start byte

The same command, executed by redis-cli returns:

> ~$ redis-cli dump key
"\x00\x05value\x06\x00\x17\x1b\xa9\xb84\xff\xa7\xfd"

**Comment by dsuch** [comment]
Done in 364bb95ded993dc3de02a85e5075b60f31f5dcc8.
