### ISSUE TITLE
How I can import zato in python interactive console?

### ISSUE THREAD

**Issue by viatoriche** [zatosource/zato#523]
And how I can setup my PyCharm for autocomplete and code analyze
```
>>> import zato
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named zato
```
```
zato@workstation:~$ zato --version
Zato 2.0.7.rev-dfee180c
```

**Comment by dsuch** [comment]
Hi @viatoriche - what is the Python binary that you are using?

**Comment by viatoriche** [comment]
@dsuch I use python2.7, zato installed from ubuntu repo

**Comment by dsuch** [comment]
Ok, I see, you need to run the one from ```/opt/zato/current/bin/py```.

Cheers.

**Comment by viatoriche** [comment]
```
zato@workstation:~$ /opt/zato/current/bin/python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zato
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named zato
>>> 
```
:baby_chick:

**Comment by dsuch** [comment]
Hi @viatoriche - this needs to be ```/opt/zato/current/bin/py``` not ```/opt/zato/current/bin/python```.

Thanks.

**Comment by viatoriche** [comment]
@dsuch Thank you!

Fulll solution:

```
$ cd /opt/zato/current/bin
$ ln -s py python_zato
```

And now we can use python_zato as interpreter for development with zato

Configure pycharm:

1. Go Project settings
2. Add Local
3. Change interpreter to /opt/zato/current/bin/python_zato
4. Save
5. ?????
6. PROFIT

```
/opt/zato/current/bin/python_zato /home/viator/pycharm-5.0.3/helpers/pydev/pydevconsole.py 55002 38579
PyDev console: starting.

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/viator/coding/zato-tutor'])


Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
>>> from zato.server.service import Service
>>> help(Service)
Help on class Service in module zato.server.service:

class Service(__builtin__.object)
 |  A base class for all services deployed on Zato servers, no matter
 |  the transport and protocol, be it plain HTTP, SOAP, WebSphere MQ or any other,
 |  regardless whether they're built-in or user-defined ones.
 |  
 |  Methods defined here:
 |  
 |  __init__(self, *ignored_args, **ignored_kwargs)
 |  
 |  accept(self)
 |  
 |  after_cron_style_job(self)
 |      Invoked if the service has been defined as a cron-style job's
 |      invocation target.
 |  
 |  after_handle(self)
 |      Invoked right after the actual service has been invoked, regardless
 |      of whether the service raised an exception or not.
 |  
 |  after_interval_based_job(self)
 |      Invoked if the service has been defined as an interval-based job's
 |      invocation target.
 |  
 |  after_job(self)
 |      Invoked  if the service has been defined as a job's invocation target,
 |      regardless of the job's type.
 |  
 |  after_one_time_job(self)
 |      Invoked if the service has been defined as a one-time job's
 |      invocation target.
 |  
 |  before_cron_style_job(self)
 |      Invoked if the service has been defined as a cron-style job's
 |      invocation target.
 |  
 |  before_handle(self, *args, **kwargs)
 |      Invoked just before the actual service receives the request data.
 |  
 |  before_interval_based_job(self)
 |      Invoked if the service has been defined as an interval-based job's
 |      invocation target.
 |  
 |  before_job(self)
 |      Invoked  if the service has been defined as a job's invocation target,
 |      regardless of the job's type.
 |  
 |  before_one_time_job(self)
 |      Invoked if the service has been defined as a one-time job's
 |      invocation target.
 |  
 |  call_handle(self, prefix)
 |  
 |  call_hooks(self, prefix)
 |  
 |  call_job_hooks(self, prefix)
 |  
 |  extract_target(self, name)
 |      Splits a service's name into name and target, if the latter is provided on input at all.
 |  
 |  finalize_handle(self)
 |      Offers the last chance to influence the service's operations.
 |  
 |  handle(self)
 |      The only method Zato services need to implement in order to process
 |      incoming requests.
 |  
 |  invoke(self, name, *args, **kwargs)
 |      Invokes a service synchronously by its name.
 |  
 |  invoke_async(self, name, payload=u'', channel=u'invoke-async', data_format=u'dict', transport=None, expiration=15, to_json_string=False, cid=None, callback=None, zato_ctx={}, environ={})
 |      Invokes a service asynchronously by its name.
 |  
 |  invoke_by_id(self, service_id, *args, **kwargs)
 |      Invokes a service synchronously by its ID.
 |  
 |  invoke_by_impl_name(self, impl_name, payload=u'', channel=u'invoke', data_format=u'dict', transport=None, serialize=False, as_bunch=False, timeout=None, raise_timeout=True, **kwargs)
 |      Invokes a service synchronously by its implementation name (full dotted Python name).
 |  
 |  lock(self, name=None, expires=20, timeout=10, backend=None)
 |      Creates a Redis-backed distributed lock.
 |      
 |      name - defaults to self.name effectively making access to this service serialized
 |      expires - defaults to 20 seconds and is the max time the lock will be held
 |      timeout - how long (in seconds) we will wait to acquire the lock before giving up and raising LockTimeout
 |      backend - a Redis connection object, defaults to self.kvdb.conn
 |  
 |  log_input(self, user_msg=u'', level=20, suppress_keys=None)
 |  
 |  log_output(self, user_msg=u'', level=20, suppress_keys=(u'wsgi_environ',))
 |  
 |  post_handle(self)
 |      An internal method executed after the service has completed and has
 |      a response ready to return. Updates its statistics and, optionally, stores
 |      a sample request/response pair.
 |  
 |  pre_handle(self)
 |      An internal method run just before the service sets to process the payload.
 |      Used for incrementing the service's usage count and storing the service invocation time.
 |  
 |  set_response_data(self, service, **kwargs)
 |  
 |  translate(self, *args, **kwargs)
 |  
 |  update_handle(self, set_response_func, service, raw_request, channel, data_format, transport, server, broker_client, worker_store, cid, simple_io_config, *args, **kwargs)
 |  
 |  validate_input(self)
 |      Invoked right before handle. Any exception raised means handle will not be called.
 |  
 |  validate_output(self)
 |      Invoked right after handle. Any exception raised means further hooks will not be called.
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  add_http_method_handlers(class_) from __builtin__.type
 |  
 |  before_add_to_store(cls, logger) from __builtin__.type
 |      Invoked right before the class is added to the service store.
 |  
 |  get_impl_name(class_) from __builtin__.type
 |  
 |  get_name(class_) from __builtin__.type
 |      Returns a service's name, settings its .name attribute along. This will
 |      be called once while the service is being deployed.
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  after_add_to_store(logger)
 |      Invoked right after the class has been added to the service store.
 |  
 |  convert_impl_name(name)
 |  
 |  get_name_static(class_)
 |  
 |  update(service, channel, server, broker_client, worker_store, cid, payload, raw_request, transport=None, simple_io_config=None, data_format=None, wsgi_environ={}, job_type=None, channel_params=None, merge_channel_params=True, params_priority=None, in_reply_to=None, environ=None, init=True)
 |      Takes a service instance and updates it with the current request's
 |      context data.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  http_method_handlers = {}
```
