### ISSUE TITLE
gh277 - TemplateSyntaxError: Could not parse the remainder: '-remote-command' from 'lb-remote-command'

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#531]
An attempt to access `http://host:8183/zato/load-balancer/remote-command/1/` results in TemplateSyntaxError:

```
2016-02-03 08:54:56,078 - ERROR - 2233:MainThread - django.request:284 - Internal Server Error: /zato/load-balancer/remote-command/1/
Traceback (most recent call last):
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/core/handlers/base.py", line 164, in get_response
    response = middleware_method(request, response)
  File "/home/vagrant/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 132, in process_template_response
    resp.render()
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/response.py", line 82, in resolve_template
    return get_template(template, using=self.using)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 514, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '-remote-command' from 'lb-remote-command'
[03/Feb/2016 08:54:56] "GET /zato/load-balancer/remote-command/1/ HTTP/1.1" 500 134033
```

**Comment by rafal-k** [comment]
Moved
