### ISSUE TITLE
gh277 - NoReverseMatch when accessing "Slow responses"

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#536]
An attempt to access "Slow responses" page ends in NoReverseMatch error:

```
2016-02-03 11:50:11,350 - ERROR - 2943:MainThread - django.request:284 - Internal Server Error: /zato/service/slow-response/[service]/
Traceback (most recent call last):
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/core/handlers/base.py", line 164, in get_response
    response = middleware_method(request, response)
  File "/home/vagrant/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 132, in process_template_response
    resp.render()
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/template/defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/vagrant/zato/code/eggs/Django-1.9.1-py2.7.egg/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'service ' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[03/Feb/2016 11:50:11] "GET /zato/service/slow-response/[service]/?cluster=1 HTTP/1.1" 500 209372
```

**Comment by rafal-k** [comment]
Moved
