### ISSUE TITLE
gh277 - AttributeError in server log after creating a new JSON Pointer

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#537]
Although web admin informs me that "Successfully created the JSON Pointer", there's an error in the server log:

```
2016-02-03 17:18:38,285 - ERROR - 3598:Dummy-255 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'103000', cluster_id=1L, msg_type=u'0002', name=u'Another Customer', value=u'/customer/another')], e:[Traceback (most recent call last):
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/worker.py", line 1284, in on_broker_msg_MSG_JSON_POINTER_CREATE
    self.json_pointer_store.on_broker_msg_create(msg)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/message.py", line 162, in on_broker_msg_create
    self.add(msg.name, msg, ns_map)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/message.py", line 281, in add
    pointer = JsonPointer(value)
  File "/home/vagrant/zato/code/eggs/jsonpointer-1.3-py2.7.egg/jsonpointer.py", line 140, in __init__
    parts = pointer.split('/')
  File "/home/vagrant/zato/code/eggs/bunch-1.0.1-py2.7.egg/bunch/__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: split
]
```

This is also linked to GH-538 and GH-539.

**Comment by rafal-k** [comment]
Moved
