### ISSUE TITLE
gh277 - KeyError in server log after editing a newly created JSON Pointer

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#538]
After I create a new JSON Pointer and try to edit it, web admin reports that "Successfully updated the JSON Pointer [Another Customer]", but there's an error in the server log:

```
2016-02-03 17:20:31,629 - ERROR - 3598:Dummy-268 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'103001', cluster_id=1L, id=2L, msg_pattern_type=u'json-pointer', msg_type=u'0002', name=u'Another Customer', old_name=u'Another Customer', value=u'//customer/another')], e:[Traceback (most recent call last):
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/worker.py", line 1290, in on_broker_msg_MSG_JSON_POINTER_EDIT
    self.json_pointer_store.on_broker_msg_edit(msg)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/message.py", line 168, in on_broker_msg_edit
    del self.data[msg.old_name]
KeyError: u'Another Customer'
]
```

This is linked to GH-#537 and GH-539.

**Comment by rafal-k** [comment]
Moved
