### ISSUE TITLE
gh277 - KeyError in server log after deleting a newly created JSON Pointer

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#539]
Again, web  admin confirms all is fine: "JSON Pointer [Another Customer] deleted", but there is KeyError in the server log:

```
2016-02-03 17:27:08,563 - ERROR - 3616:Dummy-283 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'103002', id=2L, msg_pattern_type=u'json-pointer', msg_type=u'0002', name=u'Another Customer')], e:[Traceback (most recent call last):
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/worker.py", line 1296, in on_broker_msg_MSG_JSON_POINTER_DELETE
    self.json_pointer_store.on_broker_msg_delete(msg, *args)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/message.py", line 175, in on_broker_msg_delete
    del self.data[msg.name]
KeyError: u'Another Customer'
]
```

Linked to GH-#537 and GH-538.

**Comment by rafal-k** [comment]
Moved
