### ISSUE TITLE
gh277 - AssertionError while trying to give a role RBAC read permission to a service

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#543]
I'm actually able to give the permission to a role at `http://host:8183/zato/security/rbac/role-permission/?cluster=1` - web-admin doesn't complain at all. The error is in the server log:

```
2016-02-04 13:29:02,912 - ERROR - 3326:Dummy-21 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'105208', cluster_id=1L, id=1L, msg_type=u'0002', old_name=None, perm_id=2L, role_id=0L, service_id=375L)], e:[Traceback (most recent call last):
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/worker.py", line 1605, in on_broker_msg_RBAC_ROLE_PERMISSION_CREATE
    self.rbac.create_role_permission_allow(msg.role_id, msg.perm_id, msg.service_id)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/rbac_.py", line 188, in create_role_permission_allow
    self.registry.allow(role_id, perm_id, resource)
  File "/home/vagrant/zato/code/eggs/simple_rbac-0.1.1-py2.7.egg/rbac/acl.py", line 44, in allow
    assert not resource or resource in self._resources
AssertionError
]
```

**Comment by rafal-k** [comment]
Moved
