### ISSUE TITLE
gh277 - KeyError in server log after deleting a newly created RBAC permission for a role

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#544]
After deleting a RBAC permission for a role, web-admin confirms that "Role permission [permission] deleted", but there's KeyError in the server log:

```
2016-02-04 14:56:43,929 - ERROR - 3325:Dummy-442 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'105210', id=1L, msg_type=u'0002', name=u'ZATO_NOT_GIVEN', perm_id=2L, role_id=0L, service_id=375L)], e:[Traceback (most recent call last):
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/base/worker.py", line 1608, in on_broker_msg_RBAC_ROLE_PERMISSION_DELETE
    self.rbac.delete_role_permission_allow(msg.role_id, msg.perm_id, msg.service_id)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/rbac_.py", line 196, in delete_role_permission_allow
    self.registry.delete_allow((role_id, perm_id, resource))
  File "/home/vagrant/zato/code/zato-server/src/zato/server/rbac_.py", line 73, in delete_allow
    del self._allowed[config]
KeyError: (0L, 2L, 375L)
]
```

**Comment by rafal-k** [comment]
Moved
