### ISSUE TITLE
gh277 - ProtocolError with Cassandra 3.0.2

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#549]
Trying to create a definition for Cassandra 3.0.2 results in ProtocolError. Web-admin doesn't complain at all.

```
2016-02-08 10:53:25,349 - ERROR - 3399:Dummy-25 - cassandra.connection:22 - Error decoding response from Cassandra. opcode: 0000; message contents: 'Server protocol version (%d) does not match the specified driver protocol version (%d). Consider setting Cluster.protocol_version to %d.'
Traceback (most recent call last):
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/connection.py", line 311, in process_msg
raise ProtocolError(msg % (given_version, self.protocol_version, given_version))
ProtocolError: Server protocol version (4) does not match the specified driver protocol version (2). Consider setting Cluster.protocol_version to 4.
2016-02-08 10:53:25,350 - ERROR - 3399:Dummy-25 - cassandra.connection:22 - Unexpected response during Connection setup: ProtocolError('Server protocol version (4) does not match the specified driver protocol version (2). Consider setting Cluster.protocol_version to 4.',)
2016-02-08 10:53:25,350 - WARNING - 3399:Dummy-21 - cassandra.cluster:22 - [control connection] Error connecting to 127.0.0.1:
Traceback (most recent call last):
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 1524, in _reconnect_internal
return self._try_connect(host)
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 1541, in _try_connect
connection = self._cluster.connection_factory(host.address, is_control_connection=True)
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 502, in connection_factory
return self.connection_class.factory(address, *args, **kwargs)
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/io/geventreactor.py", line 64, in factory
raise conn.last_error
ProtocolError: Unexpected response during Connection setup: ProtocolError('Server protocol version (4) does not match the specified driver protocol version (2). Consider setting Cluster.protocol_version to 4.',)
2016-02-08 10:53:25,350 - ERROR - 3399:Dummy-21 - cassandra.cluster:22 - Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 546, in connect
self.control_connection.connect()
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 1498, in connect
self._set_new_connection(self._reconnect_internal())
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 1533, in _reconnect_internal
raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {u'127.0.0.1': ProtocolError("Unexpected response during Connection setup: ProtocolError('Server protocol version (4) does not match the specified driver protocol version (2). Consider setting Cluster.protocol_version to 4.',)",)})
2016-02-08 10:53:25,350 - WARNING - 3399:Dummy-21 - zato.server.connection:22 - Could not connect to Cassandra `Test Database`, config:`action: '100610'
cluster_id: 1
contact_points: "127.0.0.1\r\n"
cql_version: null
default_keyspace: mykeyspace
exec_size: 2
id: 1
is_active: true
msg_type: '0002'
name: Test Database
old_name: null
password: '******'
port: 9042
proto_version: 2
tls_ca_certs: null
tls_client_cert: null
tls_client_priv_key: null
username: null
`, e:`Traceback (most recent call last):
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/__init__.py", line 405, in _create
session = self.create_session(name, item.config, item.config_no_sensitive)
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/cassandra.py", line 64, in create_session
session = cluster.connect()
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 546, in connect
self.control_connection.connect()
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 1498, in connect
self._set_new_connection(self._reconnect_internal())
File "/home/vagrant/zato/code/eggs/cassandra_driver-2.0.2-py2.7-linux-x86_64.egg/cassandra/cluster.py", line 1533, in _reconnect_internal
raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {u'127.0.0.1': ProtocolError("Unexpected response during Connection setup: ProtocolError('Server protocol version (4) does not match the specified driver protocol version (2). Consider setting Cluster.protocol_version to 4.',)",)})
`, sleeping for 20 s`
```

**Comment by rafal-k** [comment]
Moved
