### ISSUE TITLE
gh277 - ProbableAuthenticationError with AMQP connection

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#551]
I create an AMQP definition, and then connection. While creating the latter, however, I get ProbableAuthenticationError:

```
2016-02-08 12:50:57,563 - INFO - 3737:amqp-consuming-connector-K06ARHEQZZ5NZJ45YTWGRQ3ZPEBR - zato.broker.thread_client:22 - Starting broker client, host:[localhost], port:[6379], name:[amqp-consuming-connector-K06ARHEQZZ5NZJ45YTWGRQ3ZPEBR], topics:[['/zato/connector/amqp/all', '/zato/connector/amqp/consuming/all']]
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/__init__.py", line 91, in _run
self.start()
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/__init__.py", line 131, in start
self._start()
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/amqp/__init__.py", line 56, in _start
self.conn.ioloop.start()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/select_connection.py", line 102, in start
self.poller.start()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/select_connection.py", line 390, in start
self.poll()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/select_connection.py", line 445, in poll
self._handler(fileno, event, write_only=write_only)
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 294, in _handle_events
self._handle_read()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 310, in _handle_read
return self._handle_error(error)
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 274, in _handle_error
self._handle_disconnect()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 223, in _handle_disconnect
self._adapter_disconnect()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 135, in _adapter_disconnect
self._check_state_on_disconnect()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 150, in _check_state_on_disconnect
raise exceptions.ProbableAuthenticationError
ProbableAuthenticationError
```

**Comment by rafal-k** [comment]
Moved
