### ISSUE TITLE
gh277 - AttributeError after deleting AMQP connection

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#552]
After I deleted an AMQP connection, I found the following error in the server log:

```
2016-02-08 12:56:36,605 - ERROR - 3737:Thread-3 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'100602', id=1L, msg_type=u'0005')], e:[Traceback (most recent call last):
File "/home/vagrant/zato/code/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
getattr(self, handler)(msg)
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/amqp/__init__.py", line 152, in on_broker_msg_DEFINITION_AMQP_DELETE
self._close()
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/amqp/__init__.py", line 212, in _close
self._stop_amqp_connection()
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/amqp/channel.py", line 159, in _stop_amqp_connection
self.channel_amqp.consumer.close()
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/__init__.py", line 103, in close
self._close()
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/amqp/__init__.py", line 63, in _close
self.conn.close()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 86, in close
super(BaseConnection, self).close(reply_code, reply_text)
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/connection.py", line 600, in close
self._on_close_ready()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/connection.py", line 1038, in _on_close_ready
self._send_connection_close(self.closing[0], self.closing[1])
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/connection.py", line 1311, in _send_connection_close
self._on_connection_closed, [spec.Connection.CloseOk])
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/connection.py", line 1301, in _rpc
self._send_method(channel_number, method_frame)
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/connection.py", line 1366, in _send_method
self._send_frame(frame.Method(channel_number, method_frame))
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/connection.py", line 1353, in _send_frame
self._flush_outbound()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/select_connection.py", line 41, in _flush_outbound
self.ioloop.poller._manage_event_state()
File "/home/vagrant/zato/code/eggs/pika-0.9.12-py2.7.egg/pika/adapters/base_connection.py", line 358, in _manage_event_state
self.ioloop.update_handler(self.socket.fileno(),
AttributeError: 'NoneType' object has no attribute 'fileno')]
```

**Comment by rafal-k** [comment]
Moved
