### ISSUE TITLE
gh277 - WebSphereMQJMSException: MQSCO wrong size

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#554]
WebSphere MQ  8.0.0.4
pymqi-1.5.4

Creating a JMS WebSphere MQ channel results in the following exception:

```
2016-02-09 12:27:28,128 - INFO - 3456:Thread-4 - springpython.jms.factory.WebSphereMQConnectionFactory:22 - Connecting to queue manager [CRM1], channel [SVRCONN.1], connection info [localhost(1414)]
2016-02-09 12:27:28,129 - ERROR - 3456:Thread-4 - springpython.jms.factory.WebSphereMQConnectionFactory:22 - Could not connect to queue manager, e=[MQSCO wrong size. Given: 568, expected 632]
2016-02-09 12:27:28,129 - WARNING - 3456:Thread-4 - zato.server.connection:22 - Caught [Traceback (most recent call last):
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/__init__.py", line 131, in start
self._start()
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/jms_wmq/__init__.py", line 31, in _start
self.factory._connect()
File "/home/vagrant/zato/code/eggs/springpython-1.3.0rc1-py2.7.egg/springpython/util.py", line 45, in lockedfunc
return f(*args, **kwargs)
File "/home/vagrant/zato/code/eggs/springpython-1.3.0rc1-py2.7.egg/springpython/jms/factory.py", line 218, in _connect
raise exc
WebSphereMQJMSException: MQSCO wrong size. Given: 568, expected 632
] error, will try to (re-)connect to [queue manager=[CRM1], channel=[SVRCONN.1], conn_name=[localhost(1414)] (CRM connection)] in 5 seconds, 10 attempt(s) so far, time spent 0:00:45.080753
```

**Comment by rafal-k** [comment]
Moved
