### ISSUE TITLE
gh277 - SOAP outgoing connection SAXParseException when changing serialization from 'string' to 'suds'

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#555]
I create an outgoing SOAP connection with serialization type 'string', but after I change the type to 'suds', I get SAXParseException:

```
Traceback (most recent call last):
File "/home/vagrant/zato/code/eggs/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
result = self._run(*self.args, **self.kwargs)
File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 401, in add_client
client = Client(self.address, autoblend=True, timeout=self.config['timeout'])
File "build/bdist.linux-x86_64/egg/suds/client.py", line 115, in __init__
self.wsdl = reader.open(url)
File "build/bdist.linux-x86_64/egg/suds/reader.py", line 150, in open
d = self.fn(url, self.options)
File "build/bdist.linux-x86_64/egg/suds/wsdl.py", line 136, in __init__
d = reader.open(url)
File "build/bdist.linux-x86_64/egg/suds/reader.py", line 74, in open
d = self.download(url)
File "build/bdist.linux-x86_64/egg/suds/reader.py", line 100, in download
return sax.parse(string=content)
File "build/bdist.linux-x86_64/egg/suds/sax/parser.py", line 133, in parse
sax.parse(source)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
xmlreader.IncrementalParser.parse(self, source)
File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
self.feed(buffer)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 214, in feed
self._err_handler.fatalError(exc)
File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
raise exception
SAXParseException: <unknown>:1:0: syntax error
<Greenlet at 0x7f2e2db3bb90: <bound method SudsSOAPWrapper.add_client of <zato.server.connection.http_soap.outgoing.SudsSOAPWrapper object at 0x7f2e2e0a7390>>> failed with SAXParseException

2016-02-09 16:42:03,818 - INFO - 5495:Dummy-34 - ConnectionQueue:22 - 0/20 Suds SOAP clients obtained to `http://example.com/` (CRM connection) after 0:00:00.502023 (cap: 30.0s)
2016-02-09 16:42:04,319 - INFO - 5495:Dummy-34 - ConnectionQueue:22 - 0/20 Suds SOAP clients obtained to `http://example.com/` (CRM connection) after 0:00:01.003012 (cap: 30.0s)
2016-02-09 16:42:04,819 - INFO - 5495:Dummy-34 - ConnectionQueue:22 - 0/20 Suds SOAP clients obtained to `http://example.com/` (CRM connection) after 0:00:01.503456 (cap: 30.0s)
```

Linked to GH-556.

**Comment by rafal-k** [comment]
Moved
