### ISSUE TITLE
gh277 - SOAP outgoing connection SAXParseException when creating a connection with serialization type set to 'suds'

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#556]
When I create SOAP outgoing connection with serialization type set to 'suds', I get SAXParseException:

```
Traceback (most recent call last):
  File "/home/vagrant/zato/code/eggs/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/vagrant/zato/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 401, in add_client
    client = Client(self.address, autoblend=True, timeout=self.config['timeout'])
  File "build/bdist.linux-x86_64/egg/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "build/bdist.linux-x86_64/egg/suds/reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "build/bdist.linux-x86_64/egg/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "build/bdist.linux-x86_64/egg/suds/reader.py", line 74, in open
    d = self.download(url)
  File "build/bdist.linux-x86_64/egg/suds/reader.py", line 100, in download
    return sax.parse(string=content)
  File "build/bdist.linux-x86_64/egg/suds/sax/parser.py", line 133, in parse
    sax.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
SAXParseException: <unknown>:1:0: syntax error
<Greenlet at 0x7f3d6e8b7050: <bound method SudsSOAPWrapper.add_client of <zato.server.connection.http_soap.outgoing.SudsSOAPWrapper object at 0x7f3d6ee17510>>> failed with SAXParseException
```

Pinging via web-admin returns successfully:

```
2016-02-09T18:17:07.176361 (UTC) HEAD http://example.com/
Code: 200
Response time: 0:00:00.216373
```

Related to GH-#555.

**Comment by rafal-k** [comment]
Moved
