### ISSUE TITLE
Scheduled service and Integer SIO output

### ISSUE THREAD

**Issue by pedrudehuere** [zatosource/zato#574]
Hello,

I have a service which does some cleanup and then returns the number of deleted things.

The boiled down code is the following

```
from zato.server.service import Service, Integer

class DemoCleanupArchive(Service):

    class SimpleIO:
        output_required = (
            Integer('nb_deleted'),
        )

    @staticmethod
    def get_name():
        return u"demo.archive.cleanup"

    def handle(self):
        deleted_count = 1  # Change this value for debugging
        self.logger.info(u"Deleted {} archives".format(deleted_count))
        self.response.payload.nb_deleted = deleted_count
```

I cron-style scheduled this service, for testing purposes I Executed it manually on the scheduler page in web-admin (schedule or manual start yields the same result).

If deleted_count is 0, then everything is OK, it says:

```
2016-03-01 09:08:07,776 - INFO - 19897:Dummy-668 - demo.archive.cleanup:22 - Deleted 0 archives
```

if it is not 0 I got this error:

```
2016-03-01 09:17:07,674 - INFO - 19898:Dummy-507 - demo.archive.cleanup:22 - Deleted 1 archives
2016-03-01 09:17:07,676 - ERROR - 19898:Dummy-507 - zato.server.service.reqresp.sio:22 - Conversion error, param:`<Integer at 0x7fd1da7e2d10 name:[nb_deleted]>`, param_name:`nb_deleted`, repr:`1`, type:`<type 'int'>`, e:`Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 336, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 91, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value else value
KeyError: (True, None)
`
2016-03-01 09:17:07,676 - WARNING - 19898:Dummy-507 - zato.server.service:22 - Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 414, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/worker.py", line 946, in _set_service_response_data
    service.response.payload = service.response.payload.getvalue()
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/__init__.py", line 343, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/__init__.py", line 298, in _getvalue
    self.int_parameters, self.int_parameter_suffixes, None, self.zato_data_format, True)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 358, in convert
    return convert_sio(*params)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 350, in convert_sio
    raise ZatoException(msg=msg)
ZatoException: Conversion error, param:`<Integer at 0x7fd1da7e2d10 name:[nb_deleted]>`, param_name:`nb_deleted`, repr:`1`, type:`<type 'int'>`, e:`Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 336, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 91, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value else value
KeyError: (True, None)
`

2016-03-01 09:17:07,677 - ERROR - 19898:Dummy-507 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'100004', cid=u'K051T0ZCM1R76V76ERJ1E9FPSJWJ', job_type=u'cron_style', msg_type=u'0001', name=u'demo_archive_cleanup', payload=u'', service=u'demo.archive.cleanup')], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/worker.py", line 1028, in on_broker_msg_SCHEDULER_JOB_EXECUTED
    return self.on_message_invoke_service(msg, CHANNEL.SCHEDULER, 'SCHEDULER_JOB_EXECUTED', args)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/worker.py", line 1007, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 429, in update_handle
    raise resp_e
ZatoException: Conversion error, param:`<Integer at 0x7fd1da7e2d10 name:[nb_deleted]>`, param_name:`nb_deleted`, repr:`1`, type:`<type 'int'>`, e:`Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 336, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 91, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value else value
KeyError: (True, None)
`
]
```

While debugging I found out the following:
- if I create a plain HTTP channel for this service and call it with curl it works fine for any int value of deleted_count

```
$curl 'http://localhost:11223/archive_cleanup'
{"response": {"nb_deleted": 1}}
```
- if I define the SimpleIO field 'nb_deleted' without type it works fine for any int value of deleted_count even when the scheduler calls it (or by calling it manually on the scheduler page in web-admin)

**Comment by pedrudehuere** [comment]
zato is 2.0.7
