### ISSUE TITLE
Updating web-admin password only works with full paths

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#675]
The following commands do not update web-admin password:

```
$ zato update password web-admin admin
$ zato update password web-admin/ admin
$ zato update password ./web-admin admin
$ zato update password ./web-admin/ admin
```

Specifying full path works as intended, though:

```
$ zato update password ~/env/qs-1/web-admin/ admin
$ zato update password /opt/zato/env/qs-1/web-admin/ admin
```

**Comment by dsuch** [comment]
What happens if you provide a relative path but one that does not exist? Such as:

```bash
$ zato update password ./abc-def admin
```

**Comment by rafal-k** [comment]
I got 'No such file or directory' error:

```
$ zato update password ./abc-def admin

The new password (will not be echoed): 
Enter the password again (will not be echoed): 
Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 184, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/web_admin_auth.py", line 115, in execute
    self._prepare(args)
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/web_admin_auth.py", line 22, in _prepare
    os.chdir(os.path.abspath(args.path))
OSError: [Errno 2] No such file or directory: '/opt/zato/env/qs-1/abc-def'
```

**Comment by memlucky71** [comment]
I have this problem too.

**Comment by dsuch** [comment]
Closing old tickets.
