### ISSUE TITLE
Error while trying to send a message to AMQP: Frame SyntaxError: Shortstring overflow

### ISSUE THREAD

**Issue by lgadina** [zatosource/zato#704]
ZATO 2.0.7
ubuntu 16.04.1
RabbitMQ 3.6.5

AMQP Definition

> ```
>       Name    Host    Port    Virtual host    Username    Max frame size  Heartbeat interval           
>     local   localhost   5672    /   test    131072  10
> ```

AMQP outgoing channel

> test-amqp-outconn     Yes     local   Persistent  5   text/html   utf-8   5000    zato    ESB

Send amqp message:

```
from zato.server.service import Service

class DBTimeServiceAMQP(Service):
    def handle(self):
    msg = "test message" 
    self.logger.info(msg)
    out_name = 'test-amqp-outconn'
    exchange = '/zato.test.in'
    routing_key = ''
    properties = {'app_id': 'ESB'}
    headers = {'X-Foo': 'bar'}
    self.outgoing.amqp.send(msg, out_name, exchange, routing_key, properties, headers)
```

And i got error

```
> 2016-09-02 15:11:18,552 - ERROR - 1708:Thread-3 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'100803', args=[], body=u'test message', exchange=u'/zato.test.in', headers={'X-Zato-Msg-TS': '2016-09-02T12:11:18.547081', u'X-Foo': u'bar', 'X-Zato-Component': u'out-amqp/zato/zato/1708/MainThread'}, kwargs={}, msg_type=u'0003', out_name=u'test-amqp-outconn', properties={u'app_id': u'ESB'}, routing_key=u'')], e:[Traceback (most recent call last):
>   File "/opt/zato/2.0.7/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
>     getattr(self, handler)(msg)
>   File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/amqp/outgoing.py", line 219, in on_broker_msg_OUTGOING_AMQP_PUBLISH
>     producer.publish(msg.body, retry=True, routing_key=msg.routing_key, exchange=msg.exchange, headers=headers, **properties)
>   File "/opt/zato/2.0.7/eggs/kombu-3.0.35-py2.7.egg/kombu/messaging.py", line 172, in publish
>     routing_key, mandatory, immediate, exchange, declare)
>   File "/opt/zato/2.0.7/eggs/kombu-3.0.35-py2.7.egg/kombu/connection.py", line 436, in _ensured
>     return fun(*args, **kwargs)
>   File "/opt/zato/2.0.7/eggs/kombu-3.0.35-py2.7.egg/kombu/messaging.py", line 188, in _publish
>     mandatory=mandatory, immediate=immediate,
>   File "/opt/zato/2.0.7/eggs/amqp-1.4.9-py2.7.egg/amqp/channel.py", line 2123, in _basic_publish
>     self._send_method((60, 40), args, msg)
>   File "/opt/zato/2.0.7/eggs/amqp-1.4.9-py2.7.egg/amqp/abstract_channel.py", line 56, in _send_method
>     self.channel_id, method_sig, args, content,
>   File "/opt/zato/2.0.7/eggs/amqp-1.4.9-py2.7.egg/amqp/method_framing.py", line 219, in write_method
>     properties = content._serialize_properties()
>   File "/opt/zato/2.0.7/eggs/amqp-1.4.9-py2.7.egg/amqp/serialization.py", line 499, in _serialize_properties
>     getattr(raw_bytes, 'write_' + proptype)(val)
>   File "/opt/zato/2.0.7/eggs/amqp-1.4.9-py2.7.egg/amqp/serialization.py", line 326, in write_shortstr
>     'Shortstring overflow ({0} > 255)'.format(len(s)))
> FrameSyntaxError: Shortstring overflow (4000 > 255)
> 
```

**Comment by dsuch** [comment]
Fixed in 7b6de727dd6cbc5f6289c5647ef2b2f86e1b57fc - thank you for the ticket!
