### ISSUE TITLE
Error while trying to send a message to AMQP: ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by lgadina** [zatosource/zato#705]
ZATO 2.0.7
ubuntu 16.04.1
RabbitMQ 3.6.5

if set at the outgoing AMQP expiration empty, i got error

```
2016-09-02 15:22:07,670 - DEBUG - 3616:Thread-3 - zato.broker.thread_client:22 - Got broker message payload [action: '100803'
args: []
body: test message
exchange: /zato.test.in
headers:
    X-Foo: bar
kwargs: {}
msg_type: '0003'
out_name: test-amqp-outconn
properties:
    app_id: ESB
routing_key: ''
]
2016-09-02 15:22:07,672 - DEBUG - 3616:Thread-3 - zato.server.base:22 - Got message [Bunch(action=u'100803', args=[], body=u'test message', exchange=u'/zato.test.in', headers={u'X-Foo': u'bar'}, kwargs={}, msg_type=u'0003', out_name=u'test-amqp-outconn', properties={u'app_id': u'ESB'}, routing_key=u'')]
2016-09-02 15:22:07,676 - ERROR - 3616:Thread-3 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'100803', args=[], body=u'test message', exchange=u'/zato.test.in', headers={'X-Zato-Msg-TS': '2016-09-02T12:22:07.673352', u'X-Foo': u'bar', 'X-Zato-Component': u'out-amqp/zato/zato/3616/MainThread'}, kwargs={}, msg_type=u'0003', out_name=u'test-amqp-outconn', properties={u'app_id': u'ESB'}, routing_key=u'')], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/amqp/outgoing.py", line 219, in on_broker_msg_OUTGOING_AMQP_PUBLISH
    producer.publish(msg.body, retry=True, routing_key=msg.routing_key, exchange=msg.exchange, headers=headers, **properties)
  File "/opt/zato/2.0.7/eggs/kombu-3.0.35-py2.7.egg/kombu/messaging.py", line 161, in publish
    properties['expiration'] = str(int(expiration*1000))
ValueError: invalid literal for int() with base 10: ''
]
```

**Comment by dsuch** [comment]
Fixed in 7b6de727dd6cbc5f6289c5647ef2b2f86e1b57fc -thanks for opening the ticket!
