### ISSUE TITLE
Exception in service `zato.server.edit`

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#729]
Sending requests to `zato.server.edit` service results in the following exception:

```
$ curl http://localhost:11223/zato/json/zato.server.edit -u pubapi:pubapi -d '{"id": 1, "name": "server12"}' -D -
HTTP/1.1 500 Internal Server Error
Server: Zato
Date: Tue, 10 Jan 2017 12:18:32 GMT
Connection: close
Transfer-Encoding: chunked
X-Zato-CID: 5c49bb47705478b764dd1bc6

{"zato_env": {"details": "Traceback (most recent call last):\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 206, in dispatch\n    payload, worker_store, self.simple_io_config, post_data)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 351, in handle\n    params_priority=channel_item.params_pri)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py\", line 413, in update_handle\n    raise resp_e\nTypeError: datetime.datetime(2017, 1, 10, 8, 23, 18, 620407) is not JSON serializable\n", "result": "ZATO_ERROR", "cid": "5c49bb47705478b764dd1bc6"}}
```

Attempts to edit a server's name in web-admin result in the following error:

```
Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-web-admin/src/zato/admin/web/views/cluster.py", line 297, in servers_edit
    response = req.zato.client.invoke('zato.cluster.server.edit', {'id':server_id, 'name':req.POST['edit-name']})
  File "/home/rafal/Projects/Zato/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 78, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: a541bc58ee4bc033085d566b
Details: Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 206, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 351, in handle
    params_priority=channel_item.params_pri)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 484, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
KeyError: u'zato.cluster.server.edit'
```

Zato version:  `Zato 3.0.0rc1+rev.fb634a91`

**Comment by dsuch** [comment]
In main and support/2.0 since 6148dffe6161534190b969cde3edc7a78c7fbf28.
