### ISSUE TITLE
'Address already in use: (u'0.0.0.0', 48901)' error when starting server2

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#732]
I'm often getting 'Address already in use: (u'0.0.0.0', 48901)' error when starting server2:

```
2017-01-12 11:29:39,531 - WARNING - 12783:MainThread - zato.server.connection.connector:140 - Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/connector/__init__.py", line 136, in start
    spawn_greenlet(self._spawn_start)
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/connector/__init__.py", line 126, in _spawn_start
    spawn(self._start).get()
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 480, in get
    self._raise_exception()
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 171, in _raise_exception
    reraise(*self.exc_info)
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/web_socket/__init__.py", line 477, in _start
    self.server.serve_forever()
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/baseserver.py", line 347, in serve_forever
    self.start()
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/baseserver.py", line 291, in start
    self.init_socket()
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 1222, in init_socket
    StreamServer.init_socket(self)
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/server.py", line 80, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/server.py", line 91, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "/home/rafal/Projects/Zato/zato/code/eggs/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/server.py", line 177, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use: (u'0.0.0.0', 48901)
```

(ZeroMQ IPC)

Zato version: `Zato 3.0.0rc1+rev.fb634a91`

**Comment by oldbay** [comment]
I reaffirm this error
server2/logs/server.log:
`2017-02-04 01:56:19,505 - INFO - 27961:MainThread - zato.server.base.parallel:368 - Preferred address of `server2@cluster1` (pid: 27961) is `http://127.0.0.1:17011`
2017-02-04 01:56:43,507 - WARNING - 27961:MainThread - zato.server.connection.connector:140 - Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/zato/server/connection/connector/__init__.py", line 136, in start
    spawn_greenlet(self._spawn_start)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib64/python2.7/site-packages/zato/server/connection/connector/__init__.py", line 126, in _spawn_start
    spawn(self._start).get()
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 480, in get
    self._raise_exception()
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 171, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib64/python2.7/site-packages/zato/server/connection/web_socket/__init__.py", line 477, in _start
    self.server.serve_forever()
  File "/usr/lib64/python2.7/site-packages/gevent/baseserver.py", line 347, in serve_forever
    self.start()
  File "/usr/lib64/python2.7/site-packages/gevent/baseserver.py", line 291, in start
    self.init_socket()
  File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 1222, in init_socket
    StreamServer.init_socket(self)
  File "/usr/lib64/python2.7/site-packages/gevent/server.py", line 80, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/lib64/python2.7/site-packages/gevent/server.py", line 91, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "/usr/lib64/python2.7/site-packages/gevent/server.py", line 177, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use: (u'0.0.0.0', 48901)
`
Zato version:  Zato 3.0.0rc1+rev.51cf2261
