### ISSUE TITLE
LB's pidfile is not removed after stopping LB with ctrl-c

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#733]
Stopping LB with ctrl-c doesn't remove the pidfile and then starting LB throws an error:

```
$ zato start load-balancer
Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/bin/zato", line 187, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/zato_command.py", line 261, in main
    return run_command(get_parser().parse_args())
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 485, in run
    return_code = self.execute(args)
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 717, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/start.py", line 121, in _on_lb
    self.run_check_config()
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/start.py", line 64, in run_check_config
    cc.execute(Bunch(path='.', ensure_no_pidfile=True, check_server_port_available=True))
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 717, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/check_config.py", line 139, in _on_lb
    self.ensure_no_pidfile()
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/check_config.py", line 103, in ensure_no_pidfile
    raise Exception('Cannot proceed, found pidfile `{}`'.format(pidfile))
Exception: Cannot proceed, found pidfile `/home/rafal/env/qs-1/load-balancer/pidfile`

$
```

```
$ zato info load-balancer 
Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/bin/zato", line 187, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/zato_command.py", line 261, in main
    return run_command(get_parser().parse_args())
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 485, in run
    return_code = self.execute(args)
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 717, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/home/rafal/Projects/Zato/zato/code/zato-cli/src/zato/cli/info.py", line 40, in _on_server
    info = get_info(os.path.abspath(args.path), args.format)
  File "/home/rafal/Projects/Zato/zato/code/zato-common/src/zato/common/component_info.py", line 96, in get_info
    master_proc = Process(master_proc_pid)
  File "/home/rafal/Projects/Zato/zato/code/eggs/psutil-2.2.1-py2.7-linux-x86_64.egg/psutil/__init__.py", line 311, in __init__
    self._init(pid)
  File "/home/rafal/Projects/Zato/zato/code/eggs/psutil-2.2.1-py2.7-linux-x86_64.egg/psutil/__init__.py", line 346, in _init
    raise NoSuchProcess(pid, None, msg)
NoSuchProcess: no process found with pid 31611

$
```

Zato version: `Zato 3.0.0rc1+rev.d0f13586`

**Comment by dsuch** [comment]
In main since f086e43fcf2fd73848c62e36ba70d99710e7a84a.
