### ISSUE TITLE
zato.service.slow-response.get - Can't run after_handle

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#734]
When executing [this API test scenario](https://github.com/zatosource/zato/blob/main/code/apitest/features/zato_service_slow_response_get.feature#L89), I'm getting the following error:

```
2017-01-17 11:38:31,204 - INFO - 32055:DummyThread-690 - zato.hot-deploy.create:376 - Creating tar archive
2017-01-17 11:38:31,205 - INFO - 32055:DummyThread-690 - zato.hot-deploy.create:376 - Creating tar archive
2017-01-17 11:38:31,251 - INFO - 32055:DummyThread-690 - zato.hot-deploy.create:161 - Uploaded package id:[22], payload_name:[slow_service.py]
2017-01-17 11:38:34,279 - ERROR - 32055:DummyThread-692 - zato.service.slow-response.get:675 - Can't run after_handle of `<zato.server.service.internal.service.GetSlowResponse object at 0x7fa68055c6d0>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 673, in call_handle
    getattr(self, '{}_handle'.format(prefix))()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/__init__.py", line 107, in after_handle
    response = replace_private_key(payload if is_basestring else payload.getvalue())
AttributeError: 'dict' object has no attribute 'getvalue'
`
2017-01-17 11:38:34,280 - WARNING - 32055:DummyThread-692 - zato.server.service:409 - Exception in service `zato.service.slow-response.get`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 398, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 295, in _set_response_data
    self.set_payload(service.response, data_format, transport, service)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 386, in set_payload
    payload = response.payload.getvalue(False)
AttributeError: 'dict' object has no attribute 'getvalue'
`
2017-01-17 11:38:34,280 - ERROR - 32055:DummyThread-692 - zato.server.connection.http_soap.channel:255 - Caught an exception, cid:`2ec6cc4c14a052805bc6eb59`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 209, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 354, in handle
    params_priority=channel_item.params_pri)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 413, in update_handle
    raise resp_e
AttributeError: 'dict' object has no attribute 'getvalue'
`
```

Zato version: `Zato 3.0.0rc1+rev.d0f13586`

**Comment by dsuch** [comment]
Fixed in main in a8f242633187e516ac22487b84f09147b367da35. In support/2.0 in 17611bed1d00a6d9e52a802477b0553448a7e9f8.
