### ISSUE TITLE
zato.kvdb.data-dict.translation.create - ResponseError: value is not an integer or out of range

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#736]
Attempts in web-admin to create a dictionary translation result in ResponseError.

Dictionaries:

```
System,Key,Value
system1,key1,value1
system2,key2,value2
```

Traceback:

```
Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 426, in __call__
    response = self.req.zato.client.invoke(self.service_name, self.input_dict)
  File "/home/rafal/Projects/Zato/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 78, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 4e3063e67fb56c0a788fb9e4
Details: Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 209, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 354, in handle
    params_priority=channel_item.params_pri)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 484, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 467, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 412, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/kvdb/data_dict/translation.py", line 102, in handle
    self.response.payload.id = self._handle(hash_name, item_ids)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/kvdb/data_dict/translation.py", line 122, in _handle
    id = self.server.kvdb.conn.incr(KVDB.TRANSLATION_ID)
  File "/home/rafal/Projects/Zato/zato/code/eggs/redis-2.10.5-py2.7.egg/redis/client.py", line 915, in incr
    return self.execute_command('INCRBY', name, amount)
  File "/home/rafal/Projects/Zato/zato/code/eggs/redis-2.10.5-py2.7.egg/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/rafal/Projects/Zato/zato/code/eggs/redis-2.10.5-py2.7.egg/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/rafal/Projects/Zato/zato/code/eggs/redis-2.10.5-py2.7.egg/redis/connection.py", line 589, in read_response
    raise response
ResponseError: value is not an integer or out of range
```

Zato version: `Zato 3.0.0rc1+rev.d0f13586`

**Comment by dsuch** [comment]
What is the value of this key in Redis?

```
$ redis-cli
127.0.0.1:6379> get zato:kvdb:data-dict:translation:id
"1"
127.0.0.1:6379> 
127.0.0.1:6379> 
$ 
```

**Comment by rafal-k** [comment]
Given the dictionaries  
```
System,Key,Value
system1,key1,value1
system2,key2,value2
```
and given my unsuccessful attempt to create a translation, the value is:
```
$ redis-cli
127.0.0.1:6379> get zato:kvdb:data-dict:translation:id
"None"
127.0.0.1:6379>
$
```

**Comment by dsuch** [comment]
Is that a literal "None"? Four characters?

**Comment by rafal-k** [comment]
Yes, that is literal of four characters
```
$ literal="None"
$ echo ${#literal}
4
$
```

**Comment by dsuch** [comment]
Ok, thanks. Prior to that error, did you carry out an import/export procedure of KVDB data at least once?

**Comment by rafal-k** [comment]
No, I didn't.

I've just tried to export above mentioned data dictionaries and I've got `ValueError: invalid literal for int() with base 10: 'None'`:

```
Exception at /zato/kvdb/data-dict/impexp/cluster/1/export/
CID: 148274747e5b7d4a120808ab
Details: Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 209, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 354, in handle
    params_priority=channel_item.params_pri)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 484, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 467, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 413, in update_handle
    raise resp_e
ZatoException: Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`
```

**Comment by rafal-k** [comment]
Full set of relevant entries from the server log:

```
2017-01-19 14:33:48,901 - ERROR - 24478:DummyThread-356 - zato.server.service.reqresp.sio:353 - Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`
2017-01-19 14:33:48,901 - ERROR - 24478:DummyThread-356 - zato.kvdb.data-dict.translation.get-last-id:675 - Can't run after_handle of `<zato.server.service.internal.kvdb.data_dict.translation.GetLastID object at 0x7ff804657710>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 673, in call_handle
    getattr(self, '{}_handle'.format(prefix))()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/__init__.py", line 107, in after_handle
    response = replace_private_key(payload if is_basestring else payload.getvalue())
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 346, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 301, in _getvalue
    self.int_parameters, self.int_parameter_suffixes, None, self.zato_data_format, True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 363, in convert
    return convert_sio(*params)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 355, in convert_sio
    raise ZatoException(msg=msg)
ZatoException: Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`
`
2017-01-19 14:33:48,902 - ERROR - 24478:DummyThread-356 - zato.server.service.reqresp.sio:353 - Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`
2017-01-19 14:33:48,902 - WARNING - 24478:DummyThread-356 - zato.server.service:409 - Exception in service `zato.kvdb.data-dict.translation.get-last-id`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 398, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 280, in set_response_data
    response = response.getvalue(serialize=kwargs['serialize'])
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 346, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 301, in _getvalue
    self.int_parameters, self.int_parameter_suffixes, None, self.zato_data_format, True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 363, in convert
    return convert_sio(*params)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 355, in convert_sio
    raise ZatoException(msg=msg)
ZatoException: Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`
`
2017-01-19 14:33:48,902 - WARNING - 24478:DummyThread-356 - zato.server.service:469 - Could not invoke `zato.kvdb.data-dict.translation.get-last-id`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 467, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 413, in update_handle
    raise resp_e
ZatoException: Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`
`
2017-01-19 14:33:48,902 - WARNING - 24478:DummyThread-356 - zato.server.service:394 - Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 484, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 467, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 413, in update_handle
    raise resp_e
ZatoException: Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`

2017-01-19 14:33:48,903 - ERROR - 24478:DummyThread-356 - zato.server.connection.http_soap.channel:255 - Caught an exception, cid:`148274747e5b7d4a120808ab`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 209, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 354, in handle
    params_priority=channel_item.params_pri)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 484, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 467, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 413, in update_handle
    raise resp_e
ZatoException: Conversion error, param:`<Integer at 0x7ff81a50bc90 name:[value]>`, param_name:`value`, repr:`'None'`, type:`<type 'str'>`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 342, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 92, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value is not None else value
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/reqresp/sio.py", line 192, in from_json
    return int(value) if value else 0
ValueError: invalid literal for int() with base 10: 'None'
`
`
```

**Comment by dsuch** [comment]
Ok, this is expected that further errors would allow. I have just pushed commit 07b5a21. Please delete the zato:kvdb:data-dict:translation:id key and we'll see if it ever happens again.
