### ISSUE TITLE
KeyError: u'id' when invoking a service over HTTP channel with WSS credentials 

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#737]
When I send a request to a service over HTTP channel secured with WSS, I get the `KeyError: u'id'` in response.

Request:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:zato="https://zato.io/ns/20130518"
                  xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
    <soapenv:Body>
        <zato:zato_ping_request></zato:zato_ping_request>
    </soapenv:Body>
    <soapenv:Header>
        <wsse:Security>
            <wsse:UsernameToken>
                <wsse:Username>TestUsername</wsse:Username>
                <wsse:Password
                        Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">TestPassword</wsse:Password>
                <wsse:Nonce
                        EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">f8nUe3YupTU5ISdCy3X9Gg==</wsse:Nonce>
                <wsu:Created>2017-01-18T140:00:00.000Z</wsu:Created>
            </wsse:UsernameToken>
        </wsse:Security>
    </soapenv:Header>
</soapenv:Envelope>
```

Response:
```
2017-01-18 13:59:19,517 - ERROR - 17609:DummyThread-392 - zato.server.connection.http_soap.channel:255 - Caught an exception, cid:`82e8b72c97c6bb494d787ad2`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 201, in dispatch
    sec, cid, channel_item, path_info, payload, wsgi_environ, post_data, worker_store)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/url_data.py", line 699, in check_security
    self.enrich_with_sec_data(wsgi_environ, sec_def, sec_def_type)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/url_data.py", line 194, in enrich_with_sec_data
    data_dict['zato.sec_def']['id'] = sec_def['id']
KeyError: u'id'
`
2017-01-18 13:59:19,522 - ERROR - 17593:DummyThread-537 - zato.server.connection.http_soap.url_data:342 - UNAUTHORIZED path_info:[/apitest/security/wss/ping], cid:[38a50793677b9f78dd82780c], sec-wall code:[0003.0002], description:[Invalid username or password]

2017-01-18 13:59:19,522 - ERROR - 17593:DummyThread-537 - zato.server.connection.http_soap.channel:255 - Caught an exception, cid:`38a50793677b9f78dd82780c`, status_code:`401`, _format_exc:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 201, in dispatch
    sec, cid, channel_item, path_info, payload, wsgi_environ, post_data, worker_store)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/url_data.py", line 687, in check_security
    if not getattr(self, handler_name)(cid, sec_def, path_info, payload, wsgi_environ, post_data, enforce_auth):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/url_data.py", line 343, in _handle_security_wss
    raise Unauthorized(cid, msg, 'zato-wss')
Unauthorized: UNAUTHORIZED path_info:[/apitest/security/wss/ping], cid:[38a50793677b9f78dd82780c], sec-wall code:[0003.0002], description:[Invalid username or password]
```

Zato version: `Zato 3.0.0rc1+rev.d0f13586`

**Comment by dsuch** [comment]
Fixed in main since 53d6faa785491b931927f8bc346919a26c5cab89. In support/2.0 since 89267f0f5e1b245e06b81bf9f1798b98aa5b00e6.
