### ISSUE TITLE
'ValueError: need more than 1 value to unpack' when invoking zato.channel.zmq.edit service

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#739]
I see the ValueError in server logs, although requests sent via curl and manual edit of a ZMQ channel in web-admin are both successful:

```
$ curl $ZATO_API_TEST_SERVER/zato/json/zato.channel.zmq.edit -u pubapi:pubapi -d '{"id": 1, "cluster_id": 1, "name": "test_zmq_channel_edit232141234", "is_active": "true", "address": "127.0.0.1:33445", "socket_type": "PULL", "socket_method": "Bind", "pool_strategy": "Single", "service_source": "Zato", "service": "zato.ping", "data_format": "json"}' -D -
HTTP/1.1 200 OK
Server: Zato
Date: Wed, 18 Jan 2017 17:09:26 GMT
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
X-Zato-CID: cf4cbb23a72a48b7d0027ef9

{"zato_env": {"details": "", "result": "ZATO_OK", "cid": "cf4cbb23a72a48b7d0027ef9"}, "zato_channel_zmq_edit_response": {"id": 1, "name": "test_zmq_channel_edit232141234"}}
```

Traceback from the server log:

```
2017-01-18 18:09:26,218 - ERROR - 27592:DummyThread-108 - zato.broker:53 - Could not handle broker msg:`Bunch(action='101009', address='127.0.0.1:33445', cluster_id=1, config_cid='channel.zmq.edit.server2@quickstart-587030.cf4cbb23a72a48b7d0027ef9', data_format='json', id=1, is_active=True, msg_source=u'', msg_type='0002', name='test_zmq_channel_edit232141234', old_name='test_zmq_channel_edit232141234', old_socket_type='PULL', pool_strategy='Single', service='zato.ping', service_name='zato.ping', service_source='Zato', socket_method='Bind', socket_type='PULL', source_server='server2@quickstart-587030', sub_key=u'')`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-broker/src/zato/broker/__init__.py", line 48, in on_broker_msg
    getattr(self, handler)(msg)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/base/worker/__init__.py", line 1914, in on_broker_msg_CHANNEL_ZMQ_EDIT
    update_bind_port(msg, self.worker_idx)
  File "/home/rafal/Projects/Zato/zato/code/zato-common/src/zato/common/util.py", line 1576, in update_bind_port
    base, port = address_info.netloc.split(':')
ValueError: need more than 1 value to unpack
`
```

Zato version: `Zato 3.0.0rc1+rev.d0f13586`.

**Comment by dsuch** [comment]
The address must start with tcp:// and the correct one will be then tcp://127.0.0.1:33445 rather than 127.0.0.1:33445 alone. This is the root cause.
