### ISSUE TITLE
zato.service.get-source-info - 'NoResultFound: No row was found for one'

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato#740]
Request and response:

```
$ curl $ZATO_API_TEST_SERVER/zato/json/zato.service.get-source-info -u pubapi:pubapi -d '{"cluster_id": 1, "name": "zato.ping"}' -D -
HTTP/1.1 500 Internal Server Error
Server: Zato
Date: Wed, 18 Jan 2017 17:41:35 GMT
Connection: close
Transfer-Encoding: chunked
X-Zato-CID: 4327ba8770a7b1eac4a69736

{"zato_env": {"details": "Traceback (most recent call last):\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 209, in dispatch\n    payload, worker_store, self.simple_io_config, post_data)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 354, in handle\n    params_priority=channel_item.params_pri)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py\", line 382, in update_handle\n    self._invoke(service, channel)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py\", line 316, in _invoke\n    service.handle()\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py\", line 366, in handle\n    si = self.get_data(session)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py\", line 361, in get_data\n    filter(Server.id==self.server.id).\\\n  File \"/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py\", line 2404, in one\n    raise orm_exc.NoResultFound(\"No row was found for one()\")\nNoResultFound: No row was found for one()\n", "result": "ZATO_ERROR", "cid": "4327ba8770a7b1eac4a69736"}}
```

Traceback from the server log (reader friendly):

```
2017-01-18 18:45:21,409 - WARNING - 27592:DummyThread-733 - zato.server.service:394 - Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 366, in handle
    si = self.get_data(session)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 361, in get_data
    filter(Server.id==self.server.id).\
  File "/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2017-01-18 18:45:21,410 - ERROR - 27592:DummyThread-733 - zato.server.connection.http_soap.channel:255 - Caught an exception, cid:`ecfbe20668d389f0815e0cc7`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 209, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 354, in handle
    params_priority=channel_item.params_pri)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 366, in handle
    si = self.get_data(session)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 361, in get_data
    filter(Server.id==self.server.id).\
  File "/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
`
```

Zato version: `Zato 3.0.0rc1+rev.d0f13586`.

**Comment by dsuch** [comment]
Please make odb.extra in server.conf read as follows:

```
extra=echo=True
```

This will display SQL queries as they go along with their input parameters. Can you find the one responsible for this exception + its input in server.log?

Also, does the same happen in web-admin?

**Comment by rafal-k** [comment]
I'm pasting the output as it appears in the log after sending a request with curl:

```
$ curl $ZATO_API_TEST_SERVER/zato/json/zato.service.get-source-info -u pubapi:pubapi -d '{"cluster_id": 1, "name": "zato.ping"}' -D -                                          
HTTP/1.1 500 Internal Server Error
Server: Zato
Date: Tue, 24 Jan 2017 18:02:46 GMT
Connection: close
Transfer-Encoding: chunked
X-Zato-CID: fc1e2e683d0812f8df98497f

{"zato_env": {"details": "Traceback (most recent call last):\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 211, in dispatch\n    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 359, in handle\n    params_priority=channel_item.params_pri)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py\", line 382, in update_handle\n    self._invoke(service, channel)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py\", line 316, in _invoke\n    service.handle()\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py\", line 366, in handle\n    si = self.get_data(session)\n  File \"/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py\", line 361, in get_data\n    filter(Server.id==self.server.id).\\\n  File \"/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py\", line 2404, in one\n    raise orm_exc.NoResultFound(\"No row was found for one()\")\nNoResultFound: No row was found for one()\n", "result": "ZATO_ERROR", "cid": "fc1e2e683d0812f8df98497f"}}
```

The `server.log`:

```
2017-01-24 19:02:58,994 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2017-01-24 19:02:58,994 - INFO - 5805:DummyThread-35 - sqlalchemy.engine.base.Engine:109 - BEGIN (implicit)
2017-01-24 19:02:58,995 INFO sqlalchemy.engine.base.Engine SELECT service.id AS service_id, server.name AS server_name, deployed_service.source AS deployed_service_source, deployed_service.source_path AS deployed_service_source_path, deployed_service.source_hash AS deployed_service_source_hash, deployed_service.source_hash_method AS deployed_service_source_hash_method 
FROM service, server, deployed_service, cluster 
WHERE cluster.id = service.cluster_id AND cluster.id = ? AND service.name = ? AND service.id = deployed_service.service_id AND server.id = deployed_service.server_id AND server.id = ?
2017-01-24 19:02:58,995 - INFO - 5805:DummyThread-35 - sqlalchemy.engine.base.Engine:109 - SELECT service.id AS service_id, server.name AS server_name, deployed_service.source AS deployed_service_source, deployed_service.source_path AS deployed_service_source_path, deployed_service.source_hash AS deployed_service_source_hash, deployed_service.source_hash_method AS deployed_service_source_hash_method 
FROM service, server, deployed_service, cluster 
WHERE cluster.id = service.cluster_id AND cluster.id = ? AND service.name = ? AND service.id = deployed_service.service_id AND server.id = deployed_service.server_id AND server.id = ?
2017-01-24 19:02:58,995 INFO sqlalchemy.engine.base.Engine (1, u'zato.ping', 1)
2017-01-24 19:02:58,995 - INFO - 5805:DummyThread-35 - sqlalchemy.engine.base.Engine:109 - (1, u'zato.ping', 1)
2017-01-24 19:02:58,996 INFO sqlalchemy.engine.base.Engine ROLLBACK
2017-01-24 19:02:58,996 - INFO - 5805:DummyThread-35 - sqlalchemy.engine.base.Engine:109 - ROLLBACK
2017-01-24 19:02:58,997 - WARNING - 5805:DummyThread-35 - zato.server.service:394 - Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 366, in handle
    si = self.get_data(session)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 361, in get_data
    filter(Server.id==self.server.id).\
  File "/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2017-01-24 19:02:58,997 - WARNING - 5805:DummyThread-35 - zato.server.service:472 - Could not invoke `zato.service.get-source-info`, e:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 470, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 366, in handle
    si = self.get_data(session)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 361, in get_data
    filter(Server.id==self.server.id).\
  File "/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
`
2017-01-24 19:02:58,997 - WARNING - 5805:DummyThread-35 - zato.server.service:394 - Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 487, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 470, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 366, in handle
    si = self.get_data(session)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 361, in get_data
    filter(Server.id==self.server.id).\
  File "/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2017-01-24 19:02:58,998 - ERROR - 5805:DummyThread-35 - zato.server.connection.http_soap.channel:257 - Caught an exception, cid:`c464f3f15574f2a5ee211a7e`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 211, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 359, in handle
    params_priority=channel_item.params_pri)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 487, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 470, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 382, in update_handle
    self._invoke(service, channel)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 316, in _invoke
    service.handle()
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 366, in handle
    si = self.get_data(session)
  File "/home/rafal/Projects/Zato/zato/code/zato-server/src/zato/server/service/internal/service.py", line 361, in get_data
    filter(Server.id==self.server.id).\
  File "/home/rafal/Projects/Zato/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2404, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
`
```

The same response I get in the web-admin while using the service's invoker.

Zato version: `Zato 3.0.0rc1+rev.d0f13586`.
