### ISSUE TITLE
Could not handle broker msg

### ISSUE THREAD

**Issue by raybog** [zatosource/zato#756]
The service is run via scheduler but for some reason suddenly Zato throws following error:

```
ERROR - 2690:Dummy-10652 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'100004', cid=u'K05764QRQ2NXWF8NRRX9400GQJD1', job_type=u'interval_based', msg_type=u'0001', name=u'GetProducts', payload=u'', service=u'test-erp--request.get-product-details')], e:[Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/worker.py", line 1028, in on_broker_msg_SCHEDULER_JOB_EXECUTED
    return self.on_message_invoke_service(msg, CHANNEL.SCHEDULER, 'SCHEDULER_JOB_EXECUTED', args)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/base/worker.py", line 1007, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 348, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/server1/work/hot-deploy/current/test_ERP_Request.py", line 54, in handle
    response = out.conn.post(self.cid, request)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 337, in post
    return self.http_request('POST', cid, data, params, *args, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 307, in http_request
    response = self.invoke_http(cid, method, address, data, headers, {}, params=qs_params, *args, **kwargs)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 83, in invoke_http
    cert=cert, verify=verify, timeout=self.config['timeout'], *args, **kwargs)
  File "/opt/zato/2.0.7/eggs/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/zato/2.0.7/eggs/requests-2.7.0-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/zato/2.0.7/eggs/requests-2.7.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
]
```

**Comment by raybog** [comment]
Ok I have found where was the problem.
My config is a zato docker qs, running on Mac. For some reason docker container lost network connectivity. I could not access zato from the host and inside zato container I could not access internet. I had to stop zato container, restart docker and start zato container.
