### ISSUE TITLE
Ping for Plain HTTP outgoing connection returned None

### ISSUE THREAD

**Issue by oldbay** [zatosource/zato#758]
for Zato 3.0.0rc1+rev.990f98f
Ping for Plain HTTP outgoing connection for tutorial returned NoneType:
View Web-admin:
CRM    Yes    http://tutorial.zato.io    /get-customer    No security definition    Edit    Delete    Ping

Output traceback for operation Ping:
```
Could not ping the connection, e:[Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/zato/admin/web/views/__init__.py", line 519, in id_only_service
    result = req.zato.client.invoke(service, {'id': id})
  File "/usr/lib64/python2.7/site-packages/zato/admin/middleware.py", line 78, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 772cf830da2b9a622d2a4c7f
Details: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/zato/server/connection/http_soap/channel.py", line 212, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/usr/lib64/python2.7/site-packages/zato/server/connection/http_soap/channel.py", line 369, in handle
    params_priority=channel_item.params_pri)
  File "/usr/lib64/python2.7/site-packages/zato/server/service/__init__.py", line 456, in update_handle
    self._invoke(service, channel)
  File "/usr/lib64/python2.7/site-packages/zato/server/service/__init__.py", line 379, in _invoke
    service.handle()
  File "/usr/lib64/python2.7/site-packages/zato/server/service/internal/service.py", line 306, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/usr/lib64/python2.7/site-packages/zato/server/service/__init__.py", line 578, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zato/server/service/__init__.py", line 560, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zato/server/service/__init__.py", line 499, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/zato/server/service/__init__.py", line 456, in update_handle
    self._invoke(service, channel)
  File "/usr/lib64/python2.7/site-packages/zato/server/service/__init__.py", line 379, in _invoke
    service.handle()
  File "/usr/lib64/python2.7/site-packages/zato/server/service/internal/http_soap.py", line 400, in handle
    self.response.payload.info = config_dict.get(item.name).ping(self.cid)
AttributeError: 'NoneType' object has no attribute 'get'
```
In Zato 3.0.0rc1+rev.76ed3a2 this problem was not observed.

**Comment by dsuch** [comment]
I can confirm it and will check it out. This is likely related to works from ticket #754, thanks @oldbay.

**Comment by oldbay** [comment]
Hello, @dsuch,
The first time this error appears in Zato 3.0.0rc1+rev.348f926 - commit message:"Added pool_size to AMQP outgoing connections." As reported already, one commit earlier (76ed3a2), all is well.

**Comment by oldbay** [comment]
In new version Zato 3.0.0rc1+rev.0617e8b this problem is observed.
