### ISSUE TITLE
Issues with pub/sub consumer "clear in-flight" and REST consumer acknowledgement/reject on zato-2.0.7

### ISSUE THREAD

**Issue by keith-phua** [zatosource/zato#761]
We are using zato-2.0.7-stable.el6.

When I click on "clear in-flight" in the consumer webadmin UI, it throws the following error:

Traceback (most recent call last):
  File "/opt/zato/2.0.7/code/zato-web-admin/src/zato/admin/web/views/pubsub/consumers.py", line 142, in clear_queue
    'zato.pubsub.consumers.clear-queue', {'queue_type': queue_type, 'client_id': client_id})
  File "/opt/zato/2.0.7/code/zato-web-admin/src/zato/admin/middleware.py", line 72, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: K059NTQH3N7M7GC4GY05NNQACGGX
Details: Traceback (most recent call last):
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 350, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke
    service.handle()
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/internal/service.py", line 271, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/__init__.py", line 499, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/__init__.py", line 483, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/__init__.py", line 401, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/__init__.py", line 344, in _invoke
    service.handle()
  File "/opt/zato/2.0.7/code/zato-server/src/zato/server/service/internal/pubsub/consumers.py", line 295, in handle
    self.pubsub.acknowledge(sub_key, self.pubsub.get_consumer_in_flight_message_list(sub_key))
  File "/opt/zato/2.0.7/code/zato-common/src/zato/common/pubsub/__init__.py", line 921, in acknowledge
    return self.impl.acknowledge_delete(ctx)
  File "/opt/zato/2.0.7/code/zato-common/src/zato/common/pubsub/__init__.py", line 643, in acknowledge_delete
    args=[int(is_delete)] + ctx.msg_ids)
TypeError: can only concatenate list (not "set") to list

Also when I use REST to ack/reject topic message, it throws the following errors:

curl -XDELETE -H X-Zato-PubSub-key:K05RED7312RC4X8SXMQQPTWBGMHE 'http://pubsubuser:test123@localhost:11223/zato/pubsub/msg/K040W1NAXBSJC7ZEEGCHVC8CK1BM/?ack=true'
Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 198, in dispatch
    payload, worker_store, self.simple_io_config, post_data)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/connection/http_soap/channel.py", line 350, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 388, in update_handle
    environ=kwargs.get('environ'))
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 845, in update
    service._init()
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/__init__.py", line 298, in _init
    self.request.init(is_sio, self.cid, self.SimpleIO, self.data_format, self.transport, self.wsgi_environ)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/__init__.py", line 129, in init
    optional_list, use_channel_params_only, path_prefix, default_value, use_text, False)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/__init__.py", line 163, in get_params
    raise Exception(msg)
Exception: Caught an exception, param:`<Boolean at 0x7fed6d8726d0 name:[ack]>`, params_to_visit:`(u'max', u'dir', u'format', u'mime_type', <Integer at 0x7fed6d872590 name:[priority]>, <Integer at 0x7fed6d872490 name:[expiration]>, <AsIs at 0x7fed6d872e10 name:[msg_id]>, <Boolean at 0x7fed6d8726d0 name:[ack]>, <Boolean at 0x7fed6d872350 name:[reject]>)`, has_simple_io_config:`True`, e:`Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/__init__.py", line 156, in get_params
    self.bool_parameter_prefixes, self.int_parameters, self.int_parameter_suffixes, self.params_priority)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 412, in convert_param
    int_parameters, int_parameter_suffixes, None, data_format, False)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 350, in convert_sio
    raise ZatoException(msg=msg)
ZatoException: Conversion error, param:`<Boolean at 0x7fed6d8726d0 name:[ack]>`, param_name:`ack`, repr:`True`, type:`<type 'bool'>`, e:`Traceback (most recent call last):
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 336, in convert_sio
    value = param.convert(value, param_name, data_format, from_sio_to_external)
  File "/opt/zato/2.0.7/zato-server/src/zato/server/service/reqresp/sio.py", line 91, in convert
    return self.serialize_dispatch[(from_sio_to_external, data_type)](value, param_name) if value else value
KeyError: (False, None)

Rgds,

Keith Phua.

**Comment by dsuch** [comment]
Thanks for the ticket - I will be closing it in favour of #755, which is the new pub/sub mechanism.
