### ISSUE TITLE
Connection Error is not releasing distributed lock

### ISSUE THREAD

**Issue by raybog** [zatosource/zato#766]
Service exited with following error:
```
zato service invoke /opt/zato/env/qs-1/server1 my_service

Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 184, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.7/zato-cli/src/zato/cli/service.py", line 68, in execute
    response = func(args.name, args.payload, headers, args.channel, args.data_format, args.transport, to_json=to_json)
  File "/opt/zato/2.0.7/zato-client/src/zato/client/__init__.py", line 400, in invoke
    return self._invoke(async=False, *args, **kwargs)
  File "/opt/zato/2.0.7/zato-client/src/zato/client/__init__.py", line 397, in _invoke
    return super(AnyServiceInvoker, self).invoke(dumps(request), ServiceInvokeResponse, async, headers, output_repeated)
  File "/opt/zato/2.0.7/zato-client/src/zato/client/__init__.py", line 334, in invoke
    return self.inner_invoke(request, response_class, async, headers)
  File "/opt/zato/2.0.7/zato-client/src/zato/client/__init__.py", line 319, in inner_invoke
    raw_response = self.session.post(self.service_address, request, headers=headers)
  File "/opt/zato/2.0.7/eggs/requests-2.7.0-py2.7.egg/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/zato/2.0.7/eggs/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/zato/2.0.7/eggs/requests-2.7.0-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/zato/2.0.7/eggs/requests-2.7.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

after that distributed lock is not released.

Anyway where can I remove the lock on the zato cluster?

**Comment by dsuch** [comment]
@raybog - I know this is an old ticket but if it is still relevant, please share the source of that service.

**Comment by dsuch** [comment]
Closing due to inactivity.
