### ISSUE TITLE
IntegrityError when starting qs-1 zato 3

### ISSUE THREAD

**Issue by raybog** [zatosource/zato#769]
keep getting following when trying to start qs-1
Zato 3.0.0rc1+rev.a0d5040d

```
ERROR - 101:MainThread - gunicorn.main:182 - Exception in worker process:
Traceback (most recent call last):
  File "/opt/zato/tmp/zato/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 495, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 538, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 376, in start_server
    is_first, locally_deployed = self._after_init_common(server)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 300, in _after_init_common
    is_first, locally_deployed = self.maybe_on_first_worker(server, self.kvdb.conn)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 232, in maybe_on_first_worker
    locally_deployed = import_initial_services_jobs(is_first)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 200, in import_initial_services_jobs
    self.odb.add_channels_2_0()
  File "/opt/zato/tmp/zato/code/zato-common/src/zato/common/odb/api.py", line 767, in add_channels_2_0
    filter(Service.cluster_id==self.cluster.id).\
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2398, in one
    ret = list(self)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2440, in __iter__
    self.session._autoflush()
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1274, in _autoflush
    util.raise_from_cause(e)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1264, in _autoflush
    self.flush()
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1985, in flush
    self._flush(objects)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2103, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2067, in _flush
    flush_context.execute()
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) UNIQUE constraint failed: http_soap.name, http_soap.connection, http_soap.transport, http_soap.cluster_id u'INSERT INTO http_soap (name, is_active, is_internal, connection, transport, host, url_path, method, soap_action, soap_version, data_format, content_type, ping_method, pool_size, serialization_type, timeout, merge_url_params_req, url_params_pri, params_pri, audit_enabled, audit_back_log, audit_max_payload, audit_repl_patt_type, sec_tls_ca_cert_id, has_rbac, sec_use_rbac, service_id, cluster_id, security_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (u'zato.security.ntlm.change-password', 1, 1, u'channel', u'soap', None, u'/zato/soap', None, u'zato.security.ntlm.change-password', u'1.1', u'xml', None, None, None, u'suds', 10, 1, u'qs-over-path', u'channel-params-over-msg', 0, 1440, 0, u'json-pointer', None, 0, 0, 399, 1, 2)
Traceback (most recent call last):
  File "/opt/zato/tmp/zato/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 495, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 538, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 376, in start_server
    is_first, locally_deployed = self._after_init_common(server)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 300, in _after_init_common
    is_first, locally_deployed = self.maybe_on_first_worker(server, self.kvdb.conn)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 232, in maybe_on_first_worker
    locally_deployed = import_initial_services_jobs(is_first)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 200, in import_initial_services_jobs
    self.odb.add_channels_2_0()
  File "/opt/zato/tmp/zato/code/zato-common/src/zato/common/odb/api.py", line 767, in add_channels_2_0
    filter(Service.cluster_id==self.cluster.id).\
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2398, in one
    ret = list(self)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2440, in __iter__
    self.session._autoflush()
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1274, in _autoflush
    util.raise_from_cause(e)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1264, in _autoflush
    self.flush()
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1985, in flush
    self._flush(objects)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2103, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2067, in _flush
    flush_context.execute()
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/opt/zato/tmp/zato/code/eggs/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) UNIQUE constraint failed: http_soap.name, http_soap.connection, http_soap.transport, http_soap.cluster_id u'INSERT INTO http_soap (name, is_active, is_internal, connection, transport, host, url_path, method, soap_action, soap_version, data_format, content_type, ping_method, pool_size, serialization_type, timeout, merge_url_params_req, url_params_pri, params_pri, audit_enabled, audit_back_log, audit_max_payload, audit_repl_patt_type, sec_tls_ca_cert_id, has_rbac, sec_use_rbac, service_id, cluster_id, security_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (u'zato.security.ntlm.change-password', 1, 1, u'channel', u'soap', None, u'/zato/soap', None, u'zato.security.ntlm.change-password', u'1.1', u'xml', None, None, None, u'suds', 10, 1, u'qs-over-path', u'channel-params-over-msg', 0, 1440, 0, u'json-pointer', None, 0, 0, 399, 1, 2)
2017-05-22 11:39:51,697 - INFO - 101:MainThread - gunicorn.main:176 - Worker exiting (pid: 101)
2017-05-22 11:39:51,700 - ERROR - 101:DummyThread-1 - springpython.context.ApplicationContext:109 - Could not destroy object 'server', exception 'Traceback (most recent call last):
  File "/opt/zato/tmp/zato/code/eggs/springpython-1.3.0rc1-py2.7.egg/springpython/context/__init__.py", line 106, in shutdown_hook
    destroy_method()
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 572, in destroy
    self.invoke('zato.channel.web-socket.client.delete-by-server')
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/parallel/__init__.py", line 523, in invoke
    service, request, data_format=kwargs.pop('data_format', DATA_FORMAT.DICT), *args, **kwargs)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/worker/__init__.py", line 1244, in invoke
    }, channel, None, needs_response=True, serialize=kwargs.get('serialize', True))
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/base/worker/__init__.py", line 1305, in on_message_invoke_service
    service, is_active = self.server.service_store.new_instance_by_name(msg['service'])
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/service/store.py", line 197, in new_instance_by_name
    return self.new_instance(impl_name)
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/service/store.py", line 185, in new_instance
    return _info['service_class'](), _info['is_active']
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/service/internal/__init__.py", line 66, in __init__
    super(AdminService, self).__init__()
  File "/opt/zato/tmp/zato/code/zato-server/src/zato/server/service/__init__.py", line 245, in __init__
    self._worker_store.sql_pool_store,
AttributeError: 'WorkerStore' object has no attribute 'sql_pool_store'
'

```

**Comment by dsuch** [comment]
Thanks @raybog - a lot has changed since this ticket was opened - I will be closing it. If it still happens, please (again) provide Zato version but also exact DB version/configuration. Regards.
