### ISSUE TITLE
Not work outgoing sql

### ISSUE THREAD

**Issue by shizacat** [zatosource/zato#771]
Hi,
https://github.com/zatosource/zato/blob/main/code/zato-common/src/zato/common/odb/api.py#L79

You again create Session object, line 75 already create.

Code of service raise exception, log below:
```
with closing(self.outgoing.sql.get(out_name).session()) as session:
            result = session.execute(query).fetchall()
            self.logger.info(result)
```
But work with:

```
with closing(self.outgoing.sql.get(out_name)._session) as session:
            result = session.execute(query).fetchall()
            self.logger.info(result)
```

```
2017-05-23 12:50:53,220 - [1;31mERROR[0m - 21:DummyThread-98 - zato.server.connection.http_soap.channel:258 - Caught an exception, cid:`f0527f37734de2a92d4d3cc7`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/opt/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 212, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 369, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/code/zato-server/src/zato/server/service/__init__.py", line 456, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/code/zato-server/src/zato/server/service/__init__.py", line 379, in _invoke
    service.handle()
  File "/opt/zato/code/conf/work/hot-deploy/current/sql_service.py", line 16, in handle
    with closing(sql_obj.session()) as session:
  File "/opt/zato/code/zato-common/src/zato/common/odb/api.py", line 79, in session
    return self._Session()
AttributeError: 'SessionWrapper' object has no attribute '_Session'
```

**Comment by dsuch** [comment]
Hello @shizacat - this is done on purpose and according to the documentation, a new .session() object is created each time it is needed, hence I thank you for the ticket but I will close it now.

https://zato.io/docs/progguide/examples/sql.html

If you still like to discuss it, please reopen with a full example, Zato version and exact database version.

Thanks.
