### ISSUE TITLE
Not run scheduler if point password for broker client

### ISSUE THREAD

**Issue by shizacat** [zatosource/zato#773]
Hi,
https://github.com/zatosource/zato/blob/main/code/zato-scheduler/src/zato/scheduler/api.py#L57

Not run scheduler if point password for broker client.
Not found **decrypt_func**
```
self.broker_conn = KVDB(config=self.config.main.broker, decrypt_func=...)
```

**Comment by dsuch** [comment]
Hi @shizacat,

can you paste in the full exception and state the Zato version you are using?

Thanks.

**Comment by shizacat** [comment]
3.0.0rc1+rev.f4caea23
```
2017-05-24 09:18:13,671 - [1;37mINFO[0m - 29384:MainThread - __main__:57 - Scheduler starting (https://0.0.0.0:31530)
2017-05-24 09:18:13,755 - [1;33mWARNING[0m - 29384:MainThread - __main__:68 - Traceback (most recent call last):
  File "/z/zato/code/zato-scheduler/src/zato/scheduler/main.py", line 66, in main
    SchedulerServer(config, repo_location).serve_forever()
  File "/z/zato/code/zato-scheduler/src/zato/scheduler/server.py", line 90, in __init__
    self.scheduler = Scheduler(self.config)
  File "/z/zato/code/zato-scheduler/src/zato/scheduler/api.py", line 58, in __init__
    self.broker_conn.init()
  File "/z/zato/code/zato-common/src/zato/common/kvdb.py", line 130, in init
    config['password'] = self.decrypt_func(self.config.password)
TypeError: 'NoneType' object is not callable
```

**Comment by dsuch** [comment]
Done in 76aa18d821e10d79bcba14525d3aa9ba5903e63c - thanks @shizacat !
