### ISSUE TITLE
AMQP Channel. If you specify the "reject" mode, it will resubmit ack

### ISSUE THREAD

**Issue by shizacat** [zatosource/zato#778]
Zato 3.0.0rc1+rev.d28b225d

```
2017-05-31 13:35:08,029 - WARNING - 6589:DummyThread-46 - zato.server.connection.amqp_:228 - Unrecoverable exception in consumer, e:`Traceback (most recent call last):
  File "/z/zato/code/zato-server/src/zato/server/connection/amqp_.py", line 182, in start
    connection.drain_events(timeout=timeout)
  File "/z/zato/code/eggs/kombu-4.0.2-py2.7.egg/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/z/zato/code/eggs/kombu-4.0.2-py2.7.egg/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/z/zato/code/eggs/amqp-2.1.4-py2.7.egg/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/z/zato/code/eggs/amqp-2.1.4-py2.7.egg/amqp/connection.py", line 469, in blocking_read
    return self.on_inbound_frame(frame)
  File "/z/zato/code/eggs/amqp-2.1.4-py2.7.egg/amqp/method_framing.py", line 68, in on_frame
    callback(channel, method_sig, buf, None)
  File "/z/zato/code/eggs/amqp-2.1.4-py2.7.egg/amqp/connection.py", line 473, in on_inbound_method
    method_sig, payload, content,
  File "/z/zato/code/eggs/amqp-2.1.4-py2.7.egg/amqp/abstract_channel.py", line 142, in dispatch_method
    listener(*args)
  File "/z/zato/code/eggs/amqp-2.1.4-py2.7.egg/amqp/channel.py", line 293, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
PreconditionFailed: Basic.reject: (406) PRECONDITION_FAILED - unknown delivery tag 1
```

**Comment by dsuch** [comment]
Hi @shizacat - I sent a question in PR #779 - can you please have a look at it? I'd like to understand better what the situation here is. Thanks!
