### ISSUE TITLE
HTTP request with ¤ character in the URL returns error 500

### ISSUE THREAD

**Issue by zoop500** [zatosource/zato#819]
When HTTP request like this "http://localhost:11223/¤¤¤¤" is made, UnicodeDecodeError is raised.

Log snippet:
```
2018-01-25 13:13:48,649 - ERROR - 23013:Dummy-110 - gunicorn.main:22 - Error handling request
Traceback (most recent call last):
  File "/opt/zato/2.0.8/eggs/gunicorn-18.0-py2.7.egg/gunicorn/workers/async.py", line 45, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/zato/2.0.8/eggs/gunicorn-18.0-py2.7.egg/gunicorn/workers/ggevent.py", line 150, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/opt/zato/2.0.8/eggs/gunicorn-18.0-py2.7.egg/gunicorn/workers/async.py", line 93, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/zato/2.0.8/zato-server/src/zato/server/base/parallel.py", line 151, in on_wsgi_request
    cid, datetime.utcnow(), wsgi_environ, self.worker_store) or b''
  File "/opt/zato/2.0.8/zato-server/src/zato/server/connection/http_soap/channel.py", line 145, in dispatch
    url_match, channel_item = self.url_data.match(path_info, soap_action)
  File "/opt/zato/2.0.8/zato-server/src/zato/server/connection/http_soap/url_data.py", line 354, in match
    needs_is_internal = url_path.startswith('/zato')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)
```

**Comment by dsuch** [comment]
Thanks, that's an interesting matter. Can you also tell me:

* How did you create such a channel?
* How are you invoking it? Can you send in the exact bytes (in hex) that you are sending?
* What is this ¤ character? What does it mean?

Regards.

**Comment by zoop500** [comment]
**How did you create such a channel?**
Basically I did not. The thing is that this issue is not related to any specific channel. I found it by accident when testing invalid input for a channel (example: /api/v1/myservice/5414¤¤¤/). The character can be placed into any part of the URL and same issue occurs.

**How are you invoking it? Can you send in the exact bytes (in hex) that you are sending?**
I managed to get this error by using Firefox, Chrome and Insomnia REST client.
These clients use URL encoding, which makes the request following: http://localhost:11223/%C2%A4%C2%A4

**What is this ¤ character? What does it mean?**
As I said in the first part, it was purely accident that I used this character, so it is not required from my end. However just for information, it is character for unspecified currency. In Scandinavian keyboard layout this character is created by pressing shift+4.  Even I did not know the meaning of this character, as it is not normally used.

**Comment by dsuch** [comment]
Right, I see. I will see about handling it - it's not part of our design that they cannot be handled.

With regard to non-ASCII input, the only requirement is that everything be encoded in UTF-8, this is the only encoding that we support in addition to ASCII, no matter what kind of input. Other than that, I don't see why ¤ should not be accepted in URL paths.

Thanks again for raising this point.

**Comment by zoop500** [comment]
Personally I do not have any requirement for such characters. 
Only reason why I raised this point was the Internal Server Error. It would be nice if it returned something else, for example 400 Bad Request.

Thanks for looking into this issue.
