### ISSUE TITLE
Web admin - Delete service causes TypeError

### ISSUE THREAD

**Issue by zoop500** [zatosource/zato#821]
**Description**
When a service is deleted via Web admin's Services page, TypeError is raised. This happens for every service which is deleted. In this case, I'm removing every service contained by single service module, which is not in use anymore. 

**Symptoms of the TypeError**
Deleted service disappears from the Web admin's service page and channels and scheduler jobs connected to the deleted service will disappear from the Web admin. However the scheduler will keep invoking the deleted service until Zato is restarted.

When Zato is restarted scheduled job is not causing any issues, but the deleted servers are deployed again from the "/serverX/work/hot-deploy/current/" directory. Which makes them visible again in the Web admin's Services page.

**Workaround**
After deleting the services from Web admin, stop Zato completely (or only servers).  Then remove the wanted service module from each servers work directory manually. After this you can start Zato again.

**Log snippet**

	2018-01-31 14:29:31,637 - INFO - 18733:Dummy-22 - zato.hot-deploy.create:22 - Uploaded package id:[1796], payload_name:[forum_example.py]
	2018-01-31 14:29:32,616 - INFO - 18734:Dummy-13 - zato.hot-deploy.create:22 - Uploaded package id:[1796], payload_name:[forum_example.py]
	2018-01-31 14:29:40,990 - ERROR - 18733:Dummy-26 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'101801', id=459L, impl_name=u'forum_example.TimeoutExample', is_internal=False, msg_type=u'0002')], e:[Traceback (most recent call last):
	  File "/opt/zato/2.0.8/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
		getattr(self, handler)(msg)
	  File "/opt/zato/2.0.8/zato-server/src/zato/server/base/worker.py", line 1163, in on_broker_msg_SERVICE_DELETE
		fs_location = self.server.service_store.services[msg.impl_name]['deployment_info']['fs_location']
	TypeError: string indices must be integers, not unicode
	]
	2018-01-31 14:29:40,994 - ERROR - 18734:Dummy-17 - zato.server.base:22 - Could not handle broker msg:[Bunch(action=u'101801', id=459L, impl_name=u'forum_example.TimeoutExample', is_internal=False, msg_type=u'0002')], e:[Traceback (most recent call last):
	  File "/opt/zato/2.0.8/zato-server/src/zato/server/base/__init__.py", line 47, in on_broker_msg
		getattr(self, handler)(msg)
	  File "/opt/zato/2.0.8/zato-server/src/zato/server/base/worker.py", line 1163, in on_broker_msg_SERVICE_DELETE
		fs_location = self.server.service_store.services[msg.impl_name]['deployment_info']['fs_location']
	TypeError: string indices must be integers, not unicode
	]

Ps.
While this is not the most serious bug and there is a workaround for it, 
it might cause downtime as the Zato must be stopped and restarted for deleting services.

**Comment by dsuch** [comment]
Thanks, I confirmed it looks similar in the latest git version - I will fix it and backport to 2.0.x.
