### ISSUE TITLE
Enmasse Is Broken In V3

### ISSUE THREAD

**Issue by paperstack** [zatosource/zato#851]
When running enmasse the following stacktrace is produced (seemingly for all operations).

> Traceback (most recent call last):
  File "/opt/zato_main/zato/code/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato_main/zato/code/zato-cli/src/zato/cli/zato_command.py", line 362, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato_main/zato/code/zato-cli/src/zato/cli/__init__.py", line 354, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato_main/zato/code/zato-cli/src/zato/cli/__init__.py", line 630, in run
    return_code = self.execute(args)
  File "/opt/zato_main/zato/code/zato-cli/src/zato/cli/__init__.py", line 907, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato_main/zato/code/zato-cli/src/zato/cli/enmasse.py", line 1141, in _on_server
    populate_services_from_apispec(self.client, self.logger)
  File "/opt/zato_main/zato/code/zato-cli/src/zato/cli/enmasse.py", line 85, in populate_services_from_apispec
    for service in response.data['namespaces']['']['services']:
KeyError: u'namespaces'

**Comment by dsuch** [comment]
Thanks - are you running enmasse v3 with a v2 cluster or is it enmasse v3 on a v3 cluster?

**Comment by paperstack** [comment]
Its a V3 cluster with version: Zato 3.0.0rc1+rev.5cb06001

**Comment by dsuch** [comment]
Hello - this is fixed, please install latest updates as documented here:

https://zato.io/docs/3.0/admin/guide/install/update.html

I will be closing the ticket - if anything else is still needed, feel free to re-open.
