### ISSUE TITLE
sso create-super-user error

### ISSUE THREAD

**Issue by zhuangyan** [zatosource/zato#852]
zato@ubuntu:~$ zato --version
Zato 3.0.0+rev.f5dbf26b
zato@ubuntu:~$ zato sso create-super-user ~/env/qs-1/server1/ admin1 --verbose

Password (will not echo): 
Password again (will not echo): 
Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/zato_command.py", line 362, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 354, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 630, in run
    return_code = self.execute(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/sso.py", line 78, in execute
    return self._on_sso_command(args, user, user_api)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/sso.py", line 107, in _on_sso_command
    if user_api.get_user_by_username('', args.username):
  File "/opt/zato/3.0/code/zato-sso/src/zato/sso/user.py", line 501, in get_user_by_username
    with closing(self.odb_session_func()) as session:
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/sso.py", line 48, in _get_session
    return self.get_odb_session_from_server_config(server_conf, None)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 698, in get_odb_session_from_server_config
    return cli_util.get_odb_session_from_server_config(config, cm)
TypeError: get_odb_session_from_server_config() takes exactly 3 arguments (2 given)

zato@ubuntu:~$

**Comment by dsuch** [comment]
Thanks for the report, I will look into it soon.

**Comment by dsuch** [comment]
Hello, this is done, please install the latest updates as detailed here, below. Thanks!

https://zato.io/docs/3.0/admin/guide/install/update.html
