### ISSUE TITLE
New Zato 3 "zato create scheduler" does not work

### ISSUE THREAD

**Issue by rtrind** [zatosource/zato#862]
I am having trouble trying to create the component manually. First, because even if the code hints at the existence of a "zato ca create scheduler", it does not work:
```
[zato@zato3playground1 ~]$ zato ca create scheduler --help
usage: zato ca create [-h] {ca,lb_agent,server,web_admin} ...
zato ca create: error: invalid choice: 'scheduler' (choose from u'ca', u'lb_agent', u'server', u'web_admin')
```

Creating certs using "zato ca create server", I can continue to the actual scheduler creation, but the secret parameter seems to be messing something up:

```
[zato@zato3playground1 ~]$ zato create scheduler --odb_host localhost --odb_port 6446 --odb_user zatouser --odb_db_name zatodb --odb_password zatopw ~/env/LAB1/scheduler mysql ~/env/LAB1/ca/out-pub/LAB1-scheduler1-pub-*.pem ~/env/LAB1/ca/out-priv/LAB1-scheduler1-priv-*.pem ~/env/LAB1/ca/out-cert/LAB1-scheduler1-cert-*.pem ~/env/LAB1/ca/ca-material/ca-cert.pem LAB1 secret --verbose
Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/zato_command.py", line 362, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 354, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 630, in run
    return_code = self.execute(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/create_scheduler.py", line 143, in execute
    secret_key = args.get('secret_key') or SchedulerCryptoManager.generate_key()
AttributeError: 'Namespace' object has no attribute 'get'
```

Tried using a real secret string from a quickstart environment in another lab and the error is the same.

I think I know how to fix this, based on how the quickstart environment made it work, will try to submit a pull request soon.

Finally, not sure if this secret needs to be the same between all scheduler elements, since I don't know what it is ultimately used for, please advise.

**Comment by kbni** [comment]
@dsuch So how does the new scheduler work?

**Comment by kbni** [comment]
So, I did get the scheduler created, although initially I supplied _cluster_name_ instead of _cluster_id_, which resulted in the following error:

```
ProgrammingError: ("(pg8000.core.ProgrammingError) (u'FATAL', u'57P03', u'the database system is starting up', u'postmaster.c', u'2204', u'ProcessStartupPacket')",) (Hint: re-run with --verbose for full traceback)
ProgrammingError: ("(pg8000.core.ProgrammingError) (u'FATAL', u'57P03', u'the database system is starting up', u'postmaster.c', u'2204', u'ProcessStartupPacket')",) (Hint: re-run with --verbose for full traceback)
ProgrammingError: ("(pg8000.core.ProgrammingError) (u'FATAL', u'57P03', u'the database system is starting up', u'postmaster.c', u'2204', u'ProcessStartupPacket')",) (Hint: re-run with --verbose for full traceback)
2018-07-31 06:55:40,691 - INFO - 23:MainThread - __main__:61 - Scheduler starting (https://0.0.0.0:31530)
2018-07-31 06:55:40,989 - WARNING - 23:DummyThread-1 - zato.scheduler.backend:466 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-scheduler/src/zato/scheduler/backend.py", line 442, in run
    add_scheduler_jobs(self.api, self.odb, self.config.main.cluster.id, spawn=False)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 1267, in add_scheduler_jobs
    in odb.get_job_list(cluster_id):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/odb/api.py", line 846, in get_job_list
    return query.job_list(session, cluster_id, needs_columns)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/odb/query/__init__.py", line 92, in inner
    tool = _SearchWrapper(func(*args), **kwargs)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/odb/query/__init__.py", line 67, in __init__
    self.total = q.session.execute(total_q).scalar()
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/pg8000/core.py", line 884, in execute
    self._c.execute(self, operation, args)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/pg8000/core.py", line 1911, in execute
    self.handle_messages(cursor)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/pg8000/core.py", line 1978, in handle_messages
    raise self.error
ProgrammingError: (pg8000.core.ProgrammingError) (u'ERROR', u'22P02', u'invalid input syntax for integer: "cluster1"', u'numutils.c', u'62', u'pg_atoi') [SQL: u'SELECT count(*) AS count_1 \nFROM cluster, service, job LEFT OUTER JOIN job_interval_based ON job.id = job_interval_based.job_id LEFT OUTER JOIN job_cron_style ON job.id = job_cron_style.job_id \nWHERE job.cluster_id = cluster.id AND job.service_id = service.id AND cluster.id = %s'] [parameters: ('cluster1',)] (Background on this error at: http://sqlalche.me/e/f405)
```

Recreating with cluster_name (actually, in my case just fixing up scheduler.conf) resolved this. Thought I would post in case anyone else was trying to do the same. I don't suppose we can use the cluster name in the future?

**Comment by rtrind** [comment]
Confirmed working on yesterday "support/3.0" version. Small comment, I'm doing a new set of tests and there is still no ca command for the scheduler. It would be nice just to hear a confirmation (which could later be in the docs as well) to using the server variant for it.

**Comment by dsuch** [comment]
You are right @rtrind - would you please be able to open a ticket for the command needed? Thank you.
