### ISSUE TITLE
Errors on Zato 3 scheduler logs after starting

### ISSUE THREAD

**Issue by rtrind** [zatosource/zato#864]
After the scheduler starts, these lines appear on the logs:
```
2018-07-20 19:27:44,938 - INFO - 5248:MainThread - __main__:61 - Scheduler starting (https://0.0.0.0:31530)
2018-07-20 19:27:45,250 - INFO - 5248:DummyThread-1 - zato.scheduler.backend:457 - Scheduler started
2018-07-20 19:28:25,953 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:25,960 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:25,967 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:25,973 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:25,979 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:25,985 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:25,992 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:25,998 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:26,003 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

2018-07-20 19:28:26,009 - WARNING - 5248:DummyThread-2 - zato.common.util:813 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 784, in add_startup_jobs
    filter(Cluster.id==cluster_id).\
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2900, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
```

Active jobs from previous executions do not fire. Making a job inactive/active makes it work properly after this.

Turning off the stats from the configuration turned the errors to a single line, which I believe is the autoping service. Commenting the autoping suppresses the errors, but the services still do not fire, only making a service inactive/active brings it back until the scheduler dies again.

**Comment by dsuch** [comment]
This may happen if the scheduler is first time started but none of the cluster's servers have ever be started. It means that the scheduler needs to be started after at least one server has been started at least once.

The reason is that servers populate SQL tables with information about jobs that the scheduler needs.

**Comment by dsuch** [comment]
Hm hm.. I see where you are coming from - let me reopen the ticket in that case to investigate if the metadata population task could not be moved to the scheduler.
