### ISSUE TITLE
Multiple issues around sso option

### ISSUE THREAD

**Issue by kbni** [zatosource/zato#866]
It seems that I cannot reset SSO passwords using the command line.

```
$ docker exec -ti 0128bd1dffe5 /opt/zato/current/bin/zato sso reset-user-password /opt/zato/env/server01/run alex --verbose
Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/zato_command.py", line 362, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 354, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 630, in run
    return_code = self.execute(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/sso.py", line 78, in execute
    return self._on_sso_command(args, user, user_api)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/sso.py", line 223, in _on_sso_command
    user_api.set_password('cli', user.user_id, new_password, args.must_change, args.expiry)
TypeError: set_password() takes at least 8 arguments (6 given)
```

Additionally, whenever I try to perform user actions via the `web_admin` installation, I run into this error:

```
$ docker exec -ti e40fbec0eef5 /opt/zato/current/bin/zato sso create-super-user /opt/zato/env/web_admin/run --first-name "Alex" --last-name "Wilson" alex --verbose

Password (will not echo):
Password again (will not echo):
Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/zato_command.py", line 362, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 354, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 630, in run
    return_code = self.execute(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/sso.py", line 68, in execute
    user_api = self._get_sso_config(args, repo_location, secrets_conf)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/sso.py", line 39, in _get_sso_config
    normalize_password_reject_list(sso_conf)
  File "/opt/zato/3.0/code/zato-sso/src/zato/sso/util.py", line 108, in normalize_password_reject_list
    for line in sso_conf.password.get('reject_list', '').strip().splitlines():
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/bunch/__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: password
```

Turns out I was mistaking SSO users for the other users... so I was already looking in the wrong place, but possibly the above are bugs?

**Comment by dsuch** [comment]
The first part is done and you can install the updates already: https://zato.io/docs/3.0/admin/guide/install/update.html

As for running the command against web-admin installations - this will not work, it needs to be done using servers, web-admin will not work.

However, I'm not sure about the path `/opt/zato/env/web_admin/run` - can you send output from `$ tree /opt/zato/env/web_admin/run`?

I'm asking for it because there are already checks in place to guard against this kind of usage, e.g.:

```
$ zato sso lock-user ~/env/qs-ps2/web-admin/ dsuch1
Could not find file `secrets.conf` in `/home/dsuch/env/qs-ps2/web-admin/config/repo`
$ 
```

I.e. file `secrets.conf` exists for server only and I'm not fully clear if you have it under `/opt/zato/env/web_admin/run`?

**Comment by kbni** [comment]
So `/opt/zato/env/web_admin/run` is definitely where my web_admin is (as in, I specifically wanted that `run` directory there. I do this for all Zato components. I wasn't sure what was going on with the sso commands so I copied the secrets.conf there myself. Sorry for any confusion caused by this. :)
