### ISSUE TITLE
Invoking a service from another causes TypeError

### ISSUE THREAD

**Issue by rtrind** [zatosource/zato#880]
Trying to execute something like this:
```
    def __get_drmid_list(self, _editorial_sid):
        input_data = {'editorial_sid': _editorial_sid}
        return self.invoke('drmid-cache-service', input_data)
```

This gives me the error below:
```
2018-09-05 18:08:24,002 - WARNING - 3335:DummyThread-20 - zato.server.service:583 - Could not invoke `drmid-cache-service`, e:`Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 581, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 446, in update_handle
    if (not self.accept) or service.accept():
TypeError: 'NoneType' object is not callable
`
2018-09-05 18:08:24,003 - ERROR - 3335:DummyThread-20 - mscs-mediator:81 - 'NoneType' object is not callable
2018-09-05 18:08:24,003 - ERROR - 3335:DummyThread-20 - mscs-mediator:81 - Service didn't finished properly. Marking error
2018-09-05 18:08:24,004 - ERROR - 3335:DummyThread-20 - mscs-mediator:84 - 'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/zato/env/LAB1/server/work/hot-deploy/current/mhm_service.py", line 64, in handle
    self.service_code(db)
  File "/opt/zato/env/LAB1/server/work/hot-deploy/current/mhm_service.py", line 204, in service_code
    self.__process_request(db)
  File "/opt/zato/env/LAB1/server/work/hot-deploy/current/mhm_service.py", line 226, in __process_request
    drmid_dict = self.__get_drmid_list(source_uri)
  File "/opt/zato/env/LAB1/server/work/hot-deploy/current/mhm_service.py", line 256, in __get_drmid_list
    return self.invoke('drmid-cache-service', input_data, as_bunch=True)  # ['response']['security_id_list']
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 599, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 581, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 446, in update_handle
    if (not self.accept) or service.accept():
TypeError: 'NoneType' object is not callable
```

Looking at the source, I tried adding an accept method on the target service, like this:
```
    def accept(self):
        return True
```

Now it's working properly. Since the documentation specifies the accept method should only be overriden in case you need to return False to cancel an invocation for any reason, it seems like a bug to me. Please evaluate and if you need extra info let me know.

**Comment by dsuch** [comment]
I know it has been a while but I cannot reproduce it. For sure, method accept() does not have to overridden unless needed for other purposes. Does the issue still persist today?

**Comment by dsuch** [comment]
Closing due to inactivity - I cannot reproduce it. Please feel free to reopen if needed, thank you!
