### ISSUE TITLE
Pulling latest support/3.0 breaks Zato instance on missing cleanup module

### ISSUE THREAD

**Issue by jjmurre** [zatosource/zato#903]
When the latest (branch support/3.0 for this day) is placed under an existing Zato instance, zato refuses to start, with:

```
│2018-11-16 14:19:56,582 - ^{[1;31mERROR^{[0m - 11434:MainThread - gunicorn.main:182 - Exception in worker process:                                                                     │
      │Traceback (most recent call last):                                                                                                                                                     │
      │  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker                                                                           │
      │    self.cfg.post_fork(self, worker)                                                                                                                                                   │
      │  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 792, in post_fork                                                                              │
      │    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)                                                                                                 │
      │  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 441, in start_server                                                                           │
      │    is_first, locally_deployed = self._after_init_common(server)                                                                                                                       │
      │  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 355, in _after_init_common                                                                     │
      │    is_first, locally_deployed = self.maybe_on_first_worker(server, self.kvdb.conn)                                                                                                    │
      │  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 287, in maybe_on_first_worker                                                                  │
      │    locally_deployed = import_initial_services_jobs(is_first)                                                                                                                          │
    Im│  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 253, in import_initial_services_jobs                                                           │
    20│    internal_service_modules, self.base_dir, self.sync_internal, is_first))                                                                                                            │
    20│  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/store.py", line 257, in import_internal_services                                                                        │
    20│    deployed = self.import_services_from_anywhere(items, base_dir)                                                                                                                     │
    00│  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/store.py", line 316, in import_services_from_anywhere                                                                   │30
      │    deployed.extend(self.import_services_from_module(item, is_internal))                                                                                                               │
      │  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/store.py", line 362, in import_services_from_module                                                                     │
      │    return self.import_services_from_module_object(import_module(mod_name), is_internal)                                                                                               │
      │  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module                                                                                                           │
      │    __import__(name)                                                                                                                                                                   │
      │  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__                                                                               │
      │    result = _import(*args, **kwargs)                                                                                                                                                  │
      │ImportError: No module named cleanup 
```

The config for this zato instance contains references to internal zato services, with names like `zato.server.service.internal.pubsub.cleanup.*`.  An instance where the same upgrade has been done, and where `cleanup.pyc` is still available does start.

So, it seems there has been a refactoring that removed the module `zato.server.service.internal.pubsub.cleanup`, where this module could still be referenced in the Zato configuration.

**Comment by dsuch** [comment]
Did you start servers using the --sync-internal flag?

https://zato.io/docs/admin/guide/install/update.html

**Comment by dsuch** [comment]
Also, @jjmurre - I am not 100% sure which configuration you mean? Can you say more about what references that module "zato.server.service.internal.pubsub.cleanup"? Thanks.

**Comment by jjmurre** [comment]
> Did you start servers using the --sync-internal flag?
> 
> https://zato.io/docs/admin/guide/install/update.html

One of my co-workers ran into this. He did not do sync-internal, followed intstructions here:
https://zato.io/docs/admin/guide/install/ubuntu.html (bullet install latest additions).

**Comment by jjmurre** [comment]
Would the `--sync-internal` startup after `git pull` of zato have fixed this problem?
In that case, it would be nice to also add this to https://zato.io/docs/admin/guide/install/ubuntu.html

**Comment by dsuch** [comment]
Flag ```--sync-internal``` is used only when you update an already existing installation per instructions [here](https://zato.io/docs/admin/guide/install/update.html). That is, you have a Zato environment and simply update it to the latest version.

But the link that you sent is used when you install Zato from scratch, so ```--sync-internal``` is not applicable, which is why it is not mentioned at all over [there](https://zato.io/docs/admin/guide/install/ubuntu.html). This link does not say anything about creation of an environment, with this flag or not.

In the end, I just do not know still what your co-worker did. My understanding is that someone wanted to update Zato to the latest version but instead of using the update instructions, the person ran commands for installing Zato from scratch, is that correct?

**Comment by jjmurre** [comment]
Well, the instructions for installing from scratch, also have one section (bullet "Install latest additions"), there the instruction to use --sync-internal is missing.

Maybe it would be better to make that a link to https://zato.io/docs/admin/guide/install/update.html?

**Comment by dsuch** [comment]
I would really like to keep the installation instructions as simple as possible, without having to follow a link and then going back to the main page.

I honestly do not understand why ```--sync-internal``` should be added there, I can do it, but I do not understand what the root cause is?

These are instructions for how to install a Zato package from scratch, which means that there is no environment to run ```--sync-internal``` against yet. How should I justify inserting this information on the page?

The installation from scratch boils down to:

* Install base system package
* Pull updates

This does not seem to have anything to do with updating an existing environment?

**Comment by jjmurre** [comment]
I agree with you that the instructions are OK like they are. It is clear that this is only about installing a fresh system. I will point my co-worker in the direction of the instructions for upgrading an installing system.

**Comment by jjmurre** [comment]
I found a way to reproduce the original error that this issue is about.

I have an existing Zato instance, based on this git revision.
c4c7fcf2a83bf76fa83c58a6912d5add399ceddc

I updated this zato instance to git revision:
4bd37f2e950c13cf9054a0b0b0b985baa20c0f58

It starts without problems (with or without --sync-internal), this file is gone after the git pull:
<zato-code-root>/zato-server/src/zato/server/service/internal/pubsub/cleanup.py
The associated pyc is still there.

When I remove the pyc file, zato does not start anymore (with or without --sync-internal), producing the traceback at the beginning of this issue.

**Comment by dsuch** [comment]
I will clarify in the documentation that update instructions are in a different chapter.

I have just pushed a change to support/3.0 to make sure this module is not needed - can you try it out, with --sync-internal and then without?

**Comment by jjmurre** [comment]
Works great. I'll close the issue.

**Comment by dsuch** [comment]
Thank you @jjmurre - I will reopen to make it act as a reminder to revise the documentation.
