### ISSUE TITLE
Web Admin, pub/sub -> tasks crashes on click

### ISSUE THREAD

**Issue by badsequel** [zatosource/zato#904]
Hi,

Zato 3.0.0+rev.f5dbf26b

Fresh quickstart cluster, just looking around. 
Tried clicking on Pub/sub -> Tasks in the gui and crash:

`Traceback (most recent call last): File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 375, in __call__ response = self.invoke_admin_service() File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 333, in invoke_admin_service return func(service_name, request) File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/middleware.py", line 78, in invoke raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details'))) Exception: CID: ac0cea732c11a2b69ce9c5f0 Details: Traceback (most recent call last): File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 268, in dispatch payload, worker_store, self.simple_io_config, post_data, path_info, soap_action) File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 502, in handle params_priority=channel_item.params_pri) File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle self._invoke(service, channel) File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke service.handle() File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/service.py", line 311, in handle response = func(id_, payload, channel, data_format, transport, serialize=True) File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 602, in invoke return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs) File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 584, in invoke_by_impl_name return self.update_handle(*invoke_args, **kwargs) File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle self._invoke(service, channel) File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke service.handle() File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/task/delivery_server.py", line 197, in handle self.response.payload[:] = self.get_data() File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/task/delivery_server.py", line 172, in get_data pid_response = bunchify(self.servers[server_name].invoke(GetDeliveryServerDetails.name, pid=pid)) File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/server.py", line 123, in __getitem__ self._servers[full_name] = self._add_server(cluster_name, server_name) File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/server.py", line 146, in _add_server return self.get_server_from_odb(session, cluster_name, server_name) File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/server.py", line 164, in get_server_from_odb raise ValueError(msg) ValueError: No such server or cluster server1@quickstart-392790 `

**Comment by badsequel** [comment]
Actually, if you do a refresh in the browser you can get the page to load correctly on every second refresh
