### ISSUE TITLE
create pubsub subscription is not working with sqlite 

### ISSUE THREAD

**Issue by bip91** [zatosource/zato#906]
Lack sub_pattern_matching in Insert (not null constraint)

**context :** 
when validate subscription form, Insert cannot realized.
Not depending of the type Pull and Notify have the same behavior.
```
Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 460, in __call__
    response = self.req.zato.client.invoke(self.service_name, self.input_dict)
  File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/middleware.py", line 78, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 8208efbdff146d7e5e7c4449
Details: Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 268, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 502, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/service.py", line 311, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 602, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 584, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 536, in handle
    self.response.payload = self.invoke(sub_service, sub_request)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 602, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 584, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 324, in handle
    self._handle_subscription(ctx)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 462, in _handle_subscription
    self._subscribe_impl(ctx)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 393, in _subscribe_impl
    move_messages_to_sub_queue(session, ctx.cluster_id, ctx.topic.id, ctx.endpoint_id, ctx.sub_key, now)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/odb/query/pubsub/subscribe.py", line 173, in move_messages_to_sub_queue
    session.execute(insert_messages)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: pubsub_endp_msg_queue.sub_pattern_matched [SQL: u'INSERT INTO pubsub_endp_msg_queue (pub_msg_id, topic_id, creation_time, endpoint_id, sub_key, is_in_staging, cluster_id) SELECT pubsub_message.pub_msg_id AS pubsub_message_pub_msg_id, pubsub_message.topic_id AS pubsub_message_topic_id, ? AS creation_time, ? AS endpoint_id, ? AS sub_key, ? AS is_in_staging, ? AS cluster_id \nFROM pubsub_message \nWHERE pubsub_message.topic_id = ? AND pubsub_message.cluster_id = ? AND pubsub_message.expiration_time > ? AND pubsub_message.is_in_sub_queue = 0 AND pubsub_message.pub_msg_id NOT IN (SELECT pubsub_endp_msg_queue.pub_msg_id AS pubsub_endp_msg_queue_pub_msg_id \nFROM pubsub_endp_msg_queue \nWHERE pubsub_endp_msg_queue.sub_key = ?)'] [parameters: (1544259615.051415, 4, u'zpsk.rest.None.b853c517c3f31a162e7142be', 0, 1, 2, 1, 1544259615.046856, u'zpsk.rest.None.b853c517c3f31a162e7142be')] (Background on this error at: http://sqlalche.me/e/gkpj)
```
**DB Analysis :** 
sqlite> INSERT INTO pubsub_endp_msg_queue (pub_msg_id, topic_id, creation_time, endpoint_id, sub_key, is_in_staging, cluster_id) values ('zpsm2ca8c36424d5c622ed2dccb0',2,1544259615.05141,4,'zpsk.rest.None.b853c517c3f31a162e7142be',0,1);
Error: NOT NULL constraint failed: pubsub_endp_msg_queue.sub_pattern_matched
sqlite> describe table pubsub_endp_msg_queue;
Error: near "describe": syntax error
sqlite> .schema pubsub_endp_msg_queue
CREATE TABLE pubsub_endp_msg_queue (
	id INTEGER NOT NULL, 
	creation_time NUMERIC(20, 7) NOT NULL, 
	delivery_count INTEGER DEFAULT '0' NOT NULL, 
	last_delivery_time NUMERIC(20, 7), 
	is_in_staging BOOLEAN DEFAULT 0 NOT NULL, 
	sub_pattern_matched TEXT **NOT NULL**, 
	is_deliverable BOOLEAN DEFAULT 1 NOT NULL, 
	delivery_status INTEGER DEFAULT '2' NOT NULL, 
	delivery_time NUMERIC(20, 7), 
	opaque1 TEXT, 
	pub_msg_id VARCHAR(200) NOT NULL, 
	endpoint_id INTEGER NOT NULL, 
	topic_id INTEGER NOT NULL, 
	sub_key VARCHAR(200) NOT NULL, 
	cluster_id INTEGER NOT NULL,

**Comment by dsuch** [comment]
Hello,

I cannot reproduce it. Can you send a screenshot with the form that you are using and values that you provide?

Also, does a server restart help as a temporary workaround?

Thank you.

**Comment by dsuch** [comment]
I think this can be closed - if it still applies and can be reproduced, please let me know. Thanks @bip91!
