### ISSUE TITLE
Enmasse throws AttributeError

### ISSUE THREAD

**Issue by paperstack** [zatosource/zato#907]
When trying to run enmasse (import or export) an AttributeError: secret_keys error is thrown.
The following is an output from a clean install.

zato@zato-VirtualBox:~$ zato enmasse ./env/server1  --export-odb --verbose
Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/zato_command.py", line 379, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 356, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 632, in run
    return_code = self.execute(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 909, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/enmasse.py", line 1192, in _on_server
    self.client = get_client_from_server_conf(self.args.path)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 1422, in get_client_from_server_conf
    return client_get_client_from_server_conf(server_dir, get_server_client_auth, get_config)
  File "/opt/zato/3.0/code/zato-client/src/zato/client/__init__.py", line 524, in get_client_from_server_conf
    cm = ServerCryptoManager.from_repo_dir(None, repo_dir, None)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/crypto.py", line 177, in from_repo_dir
    return cls(secret_key=secret_key, repo_dir=repo_dir, stdin_data=stdin_data)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/crypto.py", line 63, in __init__
    secret_key, well_known_data = self.get_config(repo_dir)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/crypto.py", line 252, in get_config
    return conf.secret_keys.key1, conf.zato.well_known_data
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/bunch/__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: secret_keys

zato@zato-VirtualBox:~$ zato --version
Zato 3.0.0+rev.f5dbf26b

**Comment by dsuch** [comment]
Hello @paperstack,

I would like to confirm if the server that you run enmasse against was also created with Zato 3.0 or is it a 2.0 one?

If it is the latter then you need to export objects using v2.0's enmasse. If it is the former then are you sure that the server is running when you execute the command?

**Comment by yohannesHL** [comment]
I also get the same error using `Zato 3.0` command `zato enmass --input input.json --export-local`.

**Comment by dsuch** [comment]
Hello @yohannesHL,

I have a question - does it happen even if the path to server is an absolute one?

**Comment by dsuch** [comment]
@yohannesHL - just to confirm it, it works with absolute paths but not with relative ones?

**Comment by paperstack** [comment]
I've confirmed that it does work with absolute paths but not relative ones.

**Comment by dsuch** [comment]
Thank you both, I pushed a change that makes it possible to run the command with relative paths. You can install it per the instructions below:

https://zato.io/docs/admin/guide/install/update.html
