### ISSUE TITLE
Attempt to send message to outgoing zmq connection throws AttributeError

### ISSUE THREAD

**Issue by yohannesHL** [zatosource/zato#908]
`AttributeError: 'NoneType' object has no attribute 'worker_store'` is thrown when trying to send messages to an  outgoing zmq connection. I'm using Zato 3.0.

**Steps**:
* Create outgoing connection  `zmq-connection` using Web Admin UI
* Create service to send message using `self.outgoing.zmq.send('Hello', 'zmq-connection')`
* The following error is shown upon invoking new service using Web Admin UI :
```
Could not invoke the service. name:[invoke-generic.my-service], cluster_id:[1], e:[Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/web/views/service.py", line 496, in invoke
    response = req.zato.client.invoke(name, **input_dict)
  File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/middleware.py", line 78, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 56fa5ec6dd2fc345480003e2
Details: Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 268, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 502, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/service.py", line 311, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 602, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 584, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/server2/work/hot-deploy/current/invoke_generic.py", line 22, in handle
    self.outgoing.zmq.send('test', 'zmqs')
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/zmq_/outgoing.py", line 38, in send
    conn = self.server.worker_store.zmq_out_api.connectors[out_name]
AttributeError: 'NoneType' object has no attribute 'worker_store'

]
```

**Comment by dsuch** [comment]
@yohannesHL - thank you for the ticket, I will have a closer look as soon as possible.

**Comment by dsuch** [comment]
Thanks again @yohannesHL - this is done, you can install the updates as documented here:

https://zato.io/docs/admin/guide/install/update.html
