### ISSUE TITLE
AttributeError: '_BrokerClient' object has no attribute 'pub_client'

### ISSUE THREAD

**Issue by crsde** [zatosource/zato#912]
Hello,

after updating zato and restarting servers, i get an error when try get second server running:

```
2019-02-01 14:50:41,440 - WARNING - 22392:MainThread - zato.server.service:502 - Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 403, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 219, in handle
    self.response.payload.services_deployed = self.deploy_package(self.request.input.package_id, session)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 175, in deploy_package
    return self._deploy_package(session, package_id, dp.payload_name, dp.payload)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 149, in _deploy_package
    services_deployed = self._deploy_file(current_work_dir, payload, file_name)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/hot_deploy/__init__.py", line 139, in _deploy_file
    self.broker_client.publish(msg)
  File "/opt/zato/3.0/code/zato-broker/src/zato/broker/client.py", line 163, in publish
    self.pub_client.publish(topic, dumps(msg))
AttributeError: '_BrokerClient' object has no attribute 'pub_client'

```
while first server works perfect.

**Comment by dsuch** [comment]
Hello @crsde,

in logging.conf, please change INFO to DEBUG for logger 'zato', which will put most parts of the server in debug mode.

Then start the server again and send in here to GitHub the whole of the server.log file from the moment you start it up to the exception.

Thanks.

**Comment by dsuch** [comment]
Actually, seeing as I cannot reproduce it in any way, please also:

* Send the output of **git log -1** of your Zato installation
* Change logging configuration for the first server too and send its server.log file as well

**Comment by crsde** [comment]
`zato@esb-server:~/current$ git log -1
commit 11a3ab278bc06aab6dfa3848edffc9562a642750
Merge: 3fc6614 0dd6317
Author: Dariusz Suchojad <dsuch-github@m.zato.io>
Date:   Thu Jan 31 23:01:03 2019 +0100

    Merge branch 'pre-support/3.0' into support/3.0

[server1.log](https://github.com/zatosource/zato/files/2823455/server1.log)
[server2.log](https://github.com/zatosource/zato/files/2823456/server2.log)

**Comment by dsuch** [comment]
I have just pushed a commit - can you install the latest updates and confirm if it helped?

https://zato.io/docs/admin/guide/install/update.html

**Comment by crsde** [comment]
Now it works just fine, thank you!

**Comment by crsde** [comment]
Hello, both servers and redis running locally on single vm now

**Comment by dsuch** [comment]
I see, I understand. I will close the ticket, thanks again.
