### ISSUE TITLE
slow-response-details view throws TemplateSyntaxError

### ISSUE THREAD

**Issue by klamar** [zatosource/zato#914]
Error occurs when clicking on a slow response detail link:

![image](https://user-images.githubusercontent.com/1537125/52963327-c1750880-339f-11e9-91c2-41f49f1812e2.png)

StackTrace:
```
2019-02-18 11:03:24,384 - ERROR - 5120:MainThread - django.request:284 - Internal Server Error: /zato/service/slow-response/details/dcd8517e92f48b782f406698/myserice.test/
Traceback (most recent call last):
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = middleware_method(request, response)
  File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/middleware.py", line 152, in process_template_response
    resp.render()
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/response.py", line 82, in resolve_template
    return get_template(template, using=self.using)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '-invoker' from 'service-invoker'
```

Running version 3.0 (latest commit as of today from support/3.0 branch)

**Comment by dsuch** [comment]
Hi @klamar - thank you for opening the ticket, I will be looking into it soon. I will keep you informed.

**Comment by dsuch** [comment]
Can you please install the latest updates and give it a try now? Note that there was a somewhat related matter in that the slow responses would be under certain conditions saved no matter what the threshold was but this is now corrected too.

https://zato.io/docs/admin/guide/install/update.html

**Comment by klamar** [comment]
works perfectly, thank you very much 👍

**Comment by dsuch** [comment]
Thanks for the confirmation @klamar.

Actually, I would like to ask you a question privately - can you recommend what email address I can use? Please feel free to contact me on dsuch at zato.io. Thank you.

**Comment by klamar** [comment]
@dsuch done :-)
