### ISSUE TITLE
web-admin error 500 after login

### ISSUE THREAD

**Issue by heggi** [zatosource/zato#916]
New installation
New mysql database

Config file for create web-admin
```
ca_certs_path=../certs/ca-material/ca-cert.pem
cert_path=../certs/out-cert/web-admin-cert-xxx.pem
command=create_web_admin
odb_db_name=zato
odb_host=localhost
odb_port=3306
odb_type=mysql
odb_user=zato
path=./web-admin
priv_key_path=../certs/out-priv/web-admin-priv-xxx.pem
pub_key_path=../certs/out-pub/web-admin-pub-xxx.pem
tech_account_name=tech
```
After logged in web got error 500
server.log:
```
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/django/core/handlers/base.py", line 123, in get_response
    response = middleware_method(request)
  File "/opt/zato/3.1/code/zato-web-admin/src/zato/admin/middleware.py", line 122, in process_request
    req.zato.user_profile = get_user_profile(req.user)
  File "/opt/zato/3.1/code/zato-web-admin/src/zato/admin/web/util.py", line 27, in get_user_profile
    return user_profile
UnboundLocalError: local variable 'user_profile' referenced before assignment
```

Zato 3.1.0pre1+rev.5607c519-py2.7.5
CentOS 7

**Comment by dsuch** [comment]
Hello,

thank you for the ticket - I am not able to reproduce the situation hence I added additional logging and I ask you to carry out the following:

* Navigate to /opt/zato/3.1
* Make sure you are in branch main
* Run git pull
* Stop web-admin
* Start it again
* Run SELECT * FROM user_profile in MySQL and save the output of that query before you log in
* Log in again
* Upload here the contents of the server.log file from web-admin right after you attempted to log in
* Also, upload the result of the query above

Here, below, is how it should look like when it works correctly - your credentials are checked then your profile is created and next, it is used in subsequent requests.

```
2019-02-26 08:48:50,540 - INFO - zato.admin.web.views.main:65 - Login request received
2019-02-26 08:48:50,541 - INFO - zato.admin.web.views.main:79 - Login request -> POST
2019-02-26 08:48:50,541 - INFO - zato.admin.web.views.main:86 - Login username -> `admin`
2019-02-26 08:48:50,602 - INFO - zato.admin.web.views.main:97 - User password confirmed `admin`
2019-02-26 08:48:50,602 - INFO - zato.admin.web.views.main:134 - User credentials are valid, redirecting `admin` to `/zato/`
2019-02-26 08:48:50,616 - INFO - zato.admin.web.util:25 - Getting profile for user `admin`
2019-02-26 08:48:50,617 - INFO - zato.admin.web.util:33 - Did not find an existing profile for user `admin`
2019-02-26 08:48:50,625 - INFO - zato.admin.web.util:36 - Created a profile for user `admin`
2019-02-26 08:48:50,625 - INFO - zato.admin.web.util:38 - Return a user profile for `admin`
2019-02-26 08:48:50,699 - INFO - zato.admin.web.util:25 - Getting profile for user `admin`
2019-02-26 08:48:50,699 - INFO - zato.admin.web.util:31 - Found an existing profile for user `admin`
2019-02-26 08:48:50,700 - INFO - zato.admin.web.util:38 - Return a user profile for `admin`
2019-02-26 08:48:50,710 - INFO - zato.admin.web.util:25 - Getting profile for user `admin`
2019-02-26 08:48:50,711 - INFO - zato.admin.web.util:31 - Found an existing profile for user `admin`
2019-02-26 08:48:50,711 - INFO - zato.admin.web.util:38 - Return a user profile for `admin`
2019-02-26 08:48:50,724 - INFO - zato.admin.web.util:25 - Getting profile for user `admin`
2019-02-26 08:48:50,725 - INFO - zato.admin.web.util:31 - Found an existing profile for user `admin`
```

**Comment by heggi** [comment]
```
mysql> SELECT * FROM user_profile;
Empty set (0.00 sec)
```
server.log
```
2019-02-27 00:03:36,692 - ESC[1;37mINFOESC[0m - 26456:MainThread - zato.admin.web.util:25 - Getting profile for user `admin`
2019-02-27 00:03:36,696 - ESC[1;37mINFOESC[0m - 26456:MainThread - zato.admin.web.util:38 - Returning a user profile for `admin`
2019-02-27 00:03:36,698 - ESC[1;31mERRORESC[0m - 26456:MainThread - django.request:284 - Internal Server Error: /
Traceback (most recent call last):
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/django/core/handlers/base.py", line 123, in get_response
    response = middleware_method(request)
  File "/opt/zato/3.1/code/zato-web-admin/src/zato/admin/middleware.py", line 122, in process_request
    req.zato.user_profile = get_user_profile(req.user)
  File "/opt/zato/3.1/code/zato-web-admin/src/zato/admin/web/util.py", line 39, in get_user_profile
    return user_profile
UnboundLocalError: local variable 'user_profile' referenced before assignment
```
./zato --version
Zato 3.1.0pre1+rev.71c48336-py2.7.5

**Comment by heggi** [comment]
```
show create table user_profile \G
*************************** 1. row ***************************
       Table: user_profile
Create Table: CREATE TABLE `user_profile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timezone` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date_format` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `time_format` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `user_profile_user_id_8fdce8e2_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by heggi** [comment]
Alter table work for me
`alter table user_profile add column opaque1 text;`

**Comment by dsuch** [comment]
> Alter table work for me
> `alter table user_profile add column opaque1 text;`

You initially report that it was a new installation and I do not understand - are you saying that right after creating a completely new environment from scratch this column was missing in the table?

Or was it not a new installation because the database already existed?

**Comment by heggi** [comment]
New installating. Column was missing.
I'm recreate database, recreate web-admin and got similar problem.
I'm using Percona XtraDB Cluster 5.7

**Comment by dsuch** [comment]
I am still not clear - was the column missing in a newly created database?

Also, Percona XtraDB Cluster 5.7 is not MySQL, please use a supported database, such as MySQL, Amazon RDS or MariaDB.

**Comment by heggi** [comment]
Clear server. CentOS 7, mysql 5.6:
```
mysql> create database zato;
Query OK, 1 row affected (0.00 sec)

mysql> create user 'zato'@'localhost' identified by 'zato';
Query OK, 0 rows affected (0.00 sec)

mysql> grant all on zato.* to 'zato'@'localhost';
Query OK, 0 rows affected (0.00 sec)
```

```
[root@centos7 zato-test]# ./zato create odb --odb_host localhost --odb_port 3306 --odb_user zato --odb_db_name zato mysql

ODB database password (will not echo): 
Odb_password again (will not echo): 
OK

[root@centos7 zato-test]# ./zato ca create ca ./certs
OK
[root@centos7 zato-test]# ./zato ca create web_admin ./certs
OK

[root@centos7 zato-test]# ./zato create web_admin  --odb_host localhost --odb_port 3306 --odb_user zato --odb_db_name zato ./web-admin mysql /opt/zato-test/certs/out-pub/web-admin-pub-2019-02-27_06-40-05.pem /opt/zato-test/certs/out-priv/web-admin-priv-2019-02-27_06-40-05.pem /opt/zato-test/certs/out-cert/web-admin-cert-2019-02-27_06-40-05.pem /opt/zato-test/certs/ca-material/ca-cert.pem  tech

ODB database password (will not echo): 
Odb_password again (will not echo): 

Technical account password (will not echo): 
Tech_account_password again (will not echo): 
Superuser created successfully.
OK
```

```
mysql> show create table user_profile \G
*************************** 1. row ***************************
       Table: user_profile
Create Table: CREATE TABLE `user_profile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timezone` varchar(100) DEFAULT NULL,
  `date_format` varchar(100) DEFAULT NULL,
  `time_format` varchar(10) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `user_profile_user_id_8fdce8e2_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)
```

Column is missing

**Comment by dsuch** [comment]
I see, thank you. I was able to reproduce it now - please git pull the latest changes and the column will be there now.

**Comment by heggi** [comment]
Work!
