### ISSUE TITLE
Incompatible with Percona XtraDB Cluster

### ISSUE THREAD

**Issue by heggi** [zatosource/zato#917]
Percona XtraDB Cluster do not allow using GET_LOCK or similar function in ENFORCING mode

https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html

```
2019-02-27 09:18:25,244 - ERROR - 32656:MainThread - gunicorn.main:277 - Exception in worker process
Traceback (most recent call last):
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/3.1/code/zato-server/src/zato/server/base/parallel/__init__.py", line 861, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/3.1/code/zato-server/src/zato/server/base/parallel/__init__.py", line 435, in start_server
    with self.zato_lock_manager(uuid4().hex):
  File "/opt/zato/3.1/code/zato-distlock/src/zato/distlock/__init__.py", line 116, in __enter__
    self.acquired = self._acquire()
  File "/opt/zato/3.1/code/zato-distlock/src/zato/distlock/__init__.py", line 135, in _acquire
    acquired = self._acquire_impl()
  File "/opt/zato/3.1/code/zato-distlock/src/zato/distlock/__init__.py", line 225, in _acquire_impl
    return self.session.execute(self._acquire_func(self.priv_id, 0)).scalar()
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/sql/functions.py", line 66, in _execute_on_connection
    return connection._execute_function(self, multiparams, params)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_function
    multiparams, params)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/connections.py", line 1403, in read
    self._read_result_packet(first_packet)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/connections.py", line 1473, in _read_result_packet
    self._read_rowdata_packet()
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/connections.py", line 1507, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (pymysql.err.InternalError) (1105, u'Percona-XtraDB-Cluster prohibits use of GET_LOCK with pxc_strict_mode = ENFORCING') [SQL: u'SELECT get_lock(%(get_lock_2)s, %(get_lock_3)s) AS get_lock_1'] [parameters: {u'get_lock_3': 0, u'get_lock_2': '-3870818368101346902'}] (Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by dsuch** [comment]
According to [this document](https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html), Percona XtraDB Cluster has limited support for explicit table locks which are required to support [distributed locks](https://zato.io/docs/progguide/dist-locks.html) in Zato.

I will keep the ticket open but there will be no works to support this database at the moment.

**Comment by dsuch** [comment]
Closing old tickets.
