### ISSUE TITLE
Server don't start while binding to 0.0.0.0

### ISSUE THREAD

**Issue by heggi** [zatosource/zato#918]
server.conf:
```
[main]
gunicorn_bind=0.0.0.0:9600
.........
```
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/zato/3.1/code/zato-server/src/zato/server/main.py", line 358, in <module>
    run(server_base_dir, options=parse_cmd_line_options(cmd_line_options))
  File "/opt/zato/3.1/code/zato-server/src/zato/server/main.py", line 190, in run
    preferred_address = get_preferred_ip(server_config.main.gunicorn_bind, server_config.preferred_address)
  File "/opt/zato/3.1/code/zato-common/src/zato/common/ipaddress_.py", line 105, in get_preferred_ip
    if ip_address(current) in preferred:
  File "/opt/zato/3.1/code/lib/python2.7/site-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
ipaddress.AddressValueError: '10.0.62.201' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
```

If binding to 127.0.0.1 or specify address server started successful

**Comment by dsuch** [comment]
What is the output of this command?

$ ip addr

**Comment by heggi** [comment]
```
 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:3f:01:fc brd ff:ff:ff:ff:ff:ff
    inet 10.0.62.201/23 brd 10.0.63.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe3f:1fc/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by dsuch** [comment]
I pushed a new commit to branch main. Can you run git pull and start the server again?

**Comment by heggi** [comment]
Thanks, it's work!
