### ISSUE TITLE
class CONNECTOR has no attribute 'IBM_MQ'

### ISSUE THREAD

**Issue by acrofrank** [zatosource/zato#920]
When I quickstart create cluster through sqlite then 
`Kvdb_password again (will not echo): 
[1/10] Certificate authority created
[2/10] ODB schema created
File "/data/app/zato/zato/code/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/data/app/zato/zato/code/zato-cli/src/zato/cli/zato_command.py", line 392, in main
    return run_command(get_parser().parse_args())
  File "/data/app/zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 362, in run_command
    command_class[args.command](args).run(args)
  Traceback (most recent call last):
  File "/data/app/zato/zato/code/zato-cli/src/zato/cli/__init__.py", line 637, in run
    return_code = self.execute(args)
  File "/data/app/zato/zato/code/zato-cli/src/zato/cli/quickstart.py", line 346, in execute
    create_cluster.Create(create_cluster_args).execute(create_cluster_args, False)
  File "/data/app/zato/zato/code/zato-cli/src/zato/cli/create_cluster.py", line 514, in execute
    self.add_internal_callback_wmq(session, cluster)
  File "/data/app/zato/zato/code/zato-cli/src/zato/cli/create_cluster.py", line 1043, in add_internal_callback_wmq
    wmq_username = IPC.CONNECTOR.IBM_MQ.USERNAME
AttributeError: class CONNECTOR has no attribute 'IBM_MQ'
`

**Comment by dsuch** [comment]
Can you tell me what your Zato version is and how you installed it?

The command to check version is:

$ zato --version

**Comment by acrofrank** [comment]
Zato version is 3.1.0 python 2.7.9

**Comment by dsuch** [comment]
Please run the command that I provided and send its output.

**Comment by acrofrank** [comment]
I install it through git clone, and the output  Zato 3.1.0pre1+rev.981bd3ae-py2.7.5

**Comment by dsuch** [comment]
Thanks - this is fixed, can you install updates and try again?

https://zato.io/docs/admin/guide/install/update.html

**Comment by acrofrank** [comment]
It's ok！Thank you for your help
