### ISSUE TITLE
AttributeError on 'Simple' object in ZMQ outgoing

### ISSUE THREAD

**Issue by MikHulk** [zatosource/zato#934]
Hello,

the code from tutorial here: https://zato.io/docs/tutorial/02.html#sending-messages-asynchronously

raise this error:
```
2019-03-30 16:51:51,866 DEBG 'zato-server2' stdout output:
2019-03-30 16:51:51,866 - ERROR - 277:DummyThread-58 - zato.server.connection.http_soap.channel:324 - Caught an exception, cid:`36d283c39aab2d1cb68b7719`, status_code:`500`, _format_exc:`Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 268, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 502, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/server2/work/hot-deploy/current/client_details.py", line 50, in handle
    self.outgoing.zmq.send(fraud_request, 'Fraud detection')
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/zmq_/outgoing.py", line 45, in send
    conn.send(msg, *args, **kwargs)
  File "/opt/zato/3.0/code/zato-zmq/src/zato/zmq_/outgoing.py", line 24, in send
    self.impl.send_string(msg)
AttributeError: 'Simple' object has no attribute 'impl'
```

this is how the outgoing connection is configured in my setup:
![capt](https://user-images.githubusercontent.com/10364941/55279116-1566fb80-5315-11e9-9639-8553249e9eae.png)
 

This is the service as it is configured in zato:

```python
# stdlib
from datetime import datetime
from json import dumps

# Zato
from zato.server.service import Service

class GetClientDetails(Service):

    def should_notify_frauds(self, cust_type):
        config_key = 'myapp:fraud-detection:cust-type'
        return cust_type in ('A', 'B', 'C')

    def handle(self):

        self.logger.info('Request: {}'.format(self.request.payload))
        self.logger.info('Request type: {}'.format(type(self.request.payload)))

        # Fetch connection to CRM
        crm = self.outgoing.plain_http.get('CRM')

        # Fetch connection to Payments
        payments = self.outgoing.plain_http.get('Payments')

        # Grab the customer info ..
        response = crm.conn.send(self.cid, self.request.payload)
        cust = response.data

        # .. and last payment's details
        response = payments.conn.send(self.cid, self.request.payload)
        last_payment = response.data

        self.logger.info('Customer details: {}'.format(cust))
        self.logger.info('Last payment: {}'.format(last_payment))

        response = {}
        response['first_name'] = cust['firstName']
        response['last_name'] = cust['lastName']
        response['last_payment_date'] = last_payment['DATE']
        response['last_payment_amount'] = last_payment['AMOUNT']

        if self.should_notify_frauds(self.request.payload['cust_type']):

            fraud_request = {}
            fraud_request['timestamp'] = datetime.utcnow().isoformat()
            fraud_request['request'] = dumps(self.request.payload)
            fraud_request['response'] = response
            fraud_request = dumps(fraud_request)

            self.outgoing.zmq.send(fraud_request, 'Fraud detection')

        else:
            self.logger.info('Skipped fraud detection for CID {}'.format(self.cid))

        self.logger.info('Response: {}'.format(response))

        # And return response to the caller
        self.response.payload = response
```

What is the problem ?

Regards,

**Comment by MikHulk** [comment]
I have cloned the repository to see If I could make en idea of what is going wrong. 
I have trouble in setup a development environment.
Is there any how-to in the doc explaining how setting up a dev env ?

thx

**Comment by dsuch** [comment]
A development environment is Zato [built from source](https://zato.io/docs/admin/guide/install/source.html), there is no other task to do. You can simply clone the repository, build Zato and this is it.

During development, I recommend starting components, at least servers, in foreground, e.g. zato start /path/to/server --fg. This will let you stop them with Ctrl-C.

Also, change the number of worker processes in server.conf from 2 to 1 (main.gunicorn_workers), this will make the server start faster during development, which is what is usually needed.

**Comment by MikHulk** [comment]
Hi @dsuch,

I would like to run zato in a virtual env in Pycharm without make a system wide installation.

In https://zato.io/docs/admin/guide/install/source.html the command install need to sudo so I guess zato will be installed in my system. I don't want this. I can use vagrant or build a docker, but the best would be running dev server in a virtualenv.

I will look into the install script to understand what it does.

Thx, for your help,


Regards,

**Comment by dsuch** [comment]
It will do what you are looking for, you can open install.sh and check inside.

**Comment by MikHulk** [comment]
thx I am gonna do this. Do you have any hint about where to begin to understand where the AttributeError comes from ?

**Comment by dsuch** [comment]
I would just open the module where this exception happens and try to find out if 'impl' is there defined for objects of 'Simple' and if it is not, what other attribute has a sub-attribute called 'send_string'.

**Comment by MikHulk** [comment]
the attribute is set in the super class Base in `code/zato-zmq/src/zato/zmq_/__init__.py`:

```
class Base(Connector):
    """ Base class for ZeroMQ connections, both channels and outgoing ones, other than Majordomo (MDP).
    """
    def init_simple_socket(self):
        """ Initializes a ZeroMQ socket other than Majordomo one.
        """
        try:
            # Open a ZMQ socket and set its options, if required
            self.impl = self.ctx.socket(getattr(zmq, self.config.socket_type))

            if self.config.socket_type == ZMQ.SUB and self.config.sub_key:
                self.impl.setsockopt(zmq.SUBSCRIBE, self.config.sub_key)

            # Whether to bind or connect?
            socket_method = getattr(self.impl, self.config.socket_method)
            socket_method(self.config.address)

            # Notify parent class that we are connected now.
            self.is_connected = True

        except Exception:
            logger.warn('ZeroMQ socket could not be initialized, e:`%s`', format_exc())
            raise

    def _start(self):
        self.conn = self
        self.ctx = zmq.Context()

    def _send(self, msg, *args, **kwargs):
        raise NotImplementedError('Should be defined in subclasses')

    def _stop(self):
        self.impl.close(50) # TODO: Should be configurable

    def _get_log_details(self, address):
        return '{} {}'.format(self.config.socket_type, address)

    def get_prev_log_details(self):
        return self._get_log_details(self.config.prev_address if 'prev_address' in self.config else self.config.address)

    def get_log_details(self):
        return self._get_log_details(self.config.address)
```

the method is calling from the method `zato.zmq_.Simple._start`:
```
class Simple(Base):
    """ An outgoing ZeroMQ connection of a type other than Majordomo (MDP).
    """
    def _start(self):
        super(Simple, self)._start()
        self.init_simple_socket()

    def send(self, msg):
        self.impl.send_string(msg)
```

It seems init_simple_socket fails because the port is already in use, in the docker.

I let the docker running zato this night and get this error message this morning:
```
2019-03-31 08:05:17,923 DEBG 'zato-server1' stdout output:
2019-03-31 08:05:17,923 - WARNING - 4709:MainThread - zato.server.connection.connector:139 - Caught ZeroMQ outgoing exception `Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 128, in _start_loop
    self._start()
  File "/opt/zato/3.0/code/zato-zmq/src/zato/zmq_/outgoing.py", line 21, in _start
    self.init_simple_socket()
  File "/opt/zato/3.0/code/zato-zmq/src/zato/zmq_/__init__.py", line 41, in init_simple_socket
    socket_method(self.config.address)
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
ZMQError: Address already in use
` (id:0x7fd0a3318390) (`Fraud detection` PUSH tcp://127.0.0.1:35101)
```

But in the tutorial this service must be launch manually:
> Assuming you’ve installed Zato binaries in $install_dir, you can run the server like below - note that the command really is ‘py’, not ‘python’:
```
$install_dir/bin/py zmq-server1.py
INFO - Fraud detection app running on tcp://127.0.0.1:35101
```

I suppose not in the docker itself but somewhere out, and outgoing connection must be on the IP of this "somewhere out". But tutorial gives "127.0.0.1"  for the address of the zmq connection. Does this assumption make sense for you ?

**Comment by dsuch** [comment]
In your outgoing connection, do you bind or connect to tcp://127.0.0.1:35101 ?

**Comment by MikHulk** [comment]
I tried both, but this morning I was bound to. I am trying connect.

**Comment by dsuch** [comment]
If there is a process bound to a TCP socket then by default another process will not be able to do the same. 

This is why if zmq-server1.py binds to 35101 then the outgoing connection needs to connect to it rather than bind.

**Comment by MikHulk** [comment]
Ok.

With connect, I get the same AttributeError. 

The ZMQError I described is raised this morning when I wake up my laptop (where the zato docker run).

While, the impl attr is set in the `init_simple_socket` I guess something went wrong in this method. But I have nothing about this in the log. That's what the method seems to be doing though:

```
        except Exception:
            logger.warn('ZeroMQ socket could not be initialized, e:`%s`', format_exc())
            raise
```

**Comment by Hupeli** [comment]
2019-10-03 15:36:18,926 - ERROR - 4251:DummyThread-110 - zato.server.connection.http_soap.channel:428 - Caught an exception, cid:`0d8c7adeb3ccc123c32a3810`, status_code:`500`, `Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 696, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
AttributeError: 'Simple' object has no attribute 'impl'

**Comment by brugr9** [comment]
It seems to me: does not relate to docker nor the ZeroMQ method bind or connect, but evetually on sqlalchemy disk I/O error: `sqlite3.OperationalError disk I/O error`

Kind regards, Roland
[server.log](https://github.com/zatosource/zato/files/4551813/server.log)

**Comment by dsuch** [comment]
Hi @brugr9,

is it correct to say that you have one server with two worker processes? As defined in server.conf's [main] section under gunicorn_workers?

**Comment by brugr9** [comment]
exactly, 2 servers.

**Comment by dsuch** [comment]
Can you switch to PostgreSQL in this case? It seems it can be a conflict between two processes trying to access the same SQLite file concurrently.

SQLite is good for smaller environments with one server and one worker process so ultimately, such a change would be needed anyway.

**Comment by brugr9** [comment]
Hi @dsuch,
same error using 1 server with 1 worker each (`gunicorn_worker=1`);
setup was made using
`zato quickstart create ~/esb/dgesqlite1 sqlite localhost 6379 --verbose --servers 1`

**Comment by brugr9** [comment]
Hi @dsuch,
same error using 1 server with 1 worker each (gunicorn_worker=1);
setup was made using
`zato quickstart create ~/esb/dgesqlite1 sqlite localhost 6379 --verbose --servers 1`

**Comment by dsuch** [comment]
And this happens, basically, when you hot-deploy a service? In what way are you doing it, via web-admin?

**Comment by brugr9** [comment]
Hot-deploy service via web-admin
![ue4 sqlite service py](https://user-images.githubusercontent.com/1733987/80620589-78f6b780-8a46-11ea-8dbd-32b9bdc6c7da.jpg)

**Comment by BartKalkman** [comment]
Does anyone know if this is fixed already. I get the same error as the original post and do not see a solution in the thread. On creating the outgoing connection I get this error:
```
2020-07-23 13:22:14,797 DEBG 'zatoserver2' stdout output:
2020-07-23 13:22:14,797 - ERROR - 491:DummyThread-174 - zato:0 - Could not handle broker msg:`Bunch(action='100809', address='tcp://127.0.0.1:35102', cluster_id=1, id=1, is_active=True, msg_source='', msg_type='0002', name='Fraud detection', old_name='Fraud detection', socket_method='bind', socket_type='PUSH')`, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-broker/src/zato/broker/__init__.py", line 52, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 2247, in on_broker_msg_OUTGOING_ZMQ_EDIT
    self.zmq_out_api.edit(del_name, msg)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 331, in edit
    self._edit(old_name, config)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 321, in _edit
    connector = self._delete(old_name)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 338, in _delete
    connector.stop()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 278, in stop
    self._stop()
  File "/opt/zato/3.1.0/code/zato-zmq/src/zato/zmq_/__init__.py", line 58, in _stop
    self.impl.close(50) # TODO: Should be configurable
AttributeError: 'Simple' object has no attribute 'impl'
`

2020-07-23 13:22:14,801 DEBG 'zatoserver1' stdout output:
2020-07-23 13:22:14,797 - ERROR - 495:DummyThread-268 - zato:0 - Could not handle broker msg:`Bunch(action='100809', address='tcp://127.0.0.1:35102', cluster_id=1, id=1, is_active=True, msg_source='', msg_type='0002', name='Fraud detection', old_name='Fraud detection', socket_method='bind', socket_type='PUSH')`, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-broker/src/zato/broker/__init__.py", line 52, in on_broker_msg
    getattr(self, handler)(msg)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 2247, in on_broker_msg_OUTGOING_ZMQ_EDIT
    self.zmq_out_api.edit(del_name, msg)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 331, in edit
    self._edit(old_name, config)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 321, in _edit
    connector = self._delete(old_name)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 338, in _delete
    connector.stop()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/connector/__init__.py", line 278, in stop
    self._stop()
  File "/opt/zato/3.1.0/code/zato-zmq/src/zato/zmq_/__init__.py", line 58, in _stop
    self.impl.close(50) # TODO: Should be configurable
AttributeError: 'Simple' object has no attribute 'impl'
```

**Comment by dsuch** [comment]
Hello @BartKalkman,

I have not looked into it yet - just for reference, can you please tell me what the output of **zato --version** is?

Thanks.

**Comment by BartKalkman** [comment]
Hi,

No I did not look further that I already had when I posted the question. I installed the latest docker quickstart python 3 version.

**Comment by dsuch** [comment]
Thanks @BartKalkman - one more question. If it works under Docker but not standalone, which are the same versions really, I would like to confirm if you run the **update.sh** script after the standalone installation. Do you perhaps remember?
