### ISSUE TITLE
zato enmasse raises InvalidToken

### ISSUE THREAD

**Issue by Adniel** [zatosource/zato#941]
Doing a yum install of Zato 3.0.0+rev.f5dbf26b and creating a quickstart cluster:

```$ zato quickstart create $HOME/env/qs-1 sqlite localhost 6379 --kvdb_password '' --verbose
[1/9] Certificate authority created
[2/9] ODB schema created
[3/9] ODB initial data created
[4/9] server1 created
[5/9] server2 created
[6/9] Load-balancer created
Superuser created successfully.
[7/9] Web admin created
[8/9] Scheduler created
[9/9] Management scripts created
Quickstart cluster quickstart-126355 created
Web admin user:[admin], password:[*****************************]
Start the cluster by issuing the /opt/zato/env/qs-1/zato-qs-start.sh command
Visit https://zato.io/support for more information and support options
``` 
and then trying to export server objects using enmasse and an empty json (`{}`) raises `InvalidToken` (it is also raised if using not empty json).

`$ zato enmasse ~/env/qs-1/server1/ --input empty.json --export-local --verbose`

```Traceback (most recent call last):
  File "/opt/zato/current/bin/zato", line 11, in <module>
    load_entry_point('zato-cli', 'console_scripts', 'zato')()
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/zato_command.py", line 379, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 356, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 632, in run
    return_code = self.execute(args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/__init__.py", line 909, in execute
    return self._get_dispatch()[json_data['component']](args)
  File "/opt/zato/3.0/code/zato-cli/src/zato/cli/enmasse.py", line 1217, in _on_server
    self.client = get_client_from_server_conf(self.component_dir)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 1422, in get_client_from_server_conf
    return client_get_client_from_server_conf(server_dir, get_server_client_auth, get_config)
  File "/opt/zato/3.0/code/zato-client/src/zato/client/__init__.py", line 529, in get_client_from_server_conf
    client_auth = client_auth_func(config, repo_dir, cm, False)
  File "/opt/zato/3.0/code/zato-common/src/zato/common/util/__init__.py", line 1418, in get_server_client_auth
    return (security.username, cm.decrypt(password))
  File "/opt/zato/3.0/code/zato-common/src/zato/common/crypto.py", line 199, in decrypt
    return self.secret_key.decrypt(encrypted.encode('utf8'))
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/cryptography/fernet.py", line 74, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/cryptography/fernet.py", line 88, in _get_unverified_token_data
    raise InvalidToken
InvalidToken
```
OS is CentOS 7.

**Comment by dsuch** [comment]
Hello @Adniel,

InvalidToken indicates a lower-level issue - does the environment start correctly?

**Comment by dsuch** [comment]
Also, there is a question if you have installed the updates after installing the base package?

https://zato.io/docs/admin/guide/install/update.html

**Comment by Adniel** [comment]
I did install the updates.
And you are correct, there is a problem when starting the server worker:

```
$ zato start server1 --fg --sync-internal --verbose
2019-04-11 09:48:53,597 - INFO - 19913:MainThread - gunicorn.error:213 - Starting gunicorn 18.0
2019-04-11 09:48:53,603 - INFO - 19913:MainThread - gunicorn.error:213 - Listening at: http://0.0.0.0:17010 (19913)
2019-04-11 09:48:53,603 - INFO - 19913:MainThread - gunicorn.error:213 - Using worker: gevent
2019-04-11 09:48:53,609 - INFO - 19926:MainThread - gunicorn.error:213 - Booting worker with pid: 19926
2019-04-11 09:48:53,614 - ERROR - 19926:MainThread - gunicorn.error:219 - Exception in worker process:
Traceback (most recent call last):
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 838, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 398, in start_server
    self.is_first_worker = int(os.environ['ZATO_SERVER_WORKER_IDX']) == 0
  File "/opt/zato/3.0/code/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: u'ZATO_SERVER_WORKER_IDX'
Traceback (most recent call last):
  File "/opt/zato/3.0/code/lib/python2.7/site-packages/gunicorn/arbiter.py", line 494, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 838, in post_fork
    ParallelServer.start_server(worker.app.zato_wsgi_app, arbiter.zato_deployment_key)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 398, in start_server
    self.is_first_worker = int(os.environ['ZATO_SERVER_WORKER_IDX']) == 0
  File "/opt/zato/3.0/code/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: u'ZATO_SERVER_WORKER_IDX'
2019-04-11 09:48:53,614 - INFO - 19926:MainThread - gunicorn.error:213 - Worker exiting (pid: 19926)
2019-04-11 09:48:55,264 - INFO - 19913:MainThread - gunicorn.error:213 - Shutting down: Master
2019-04-11 09:48:55,269 - INFO - 19913:MainThread - gunicorn.error:213 - Reason: Worker failed to boot.
No handlers could be found for logger "zato.common.util.proc"```

**Comment by dsuch** [comment]
In /tmp there will be files named like **/tmp/tmpw3UUH6-zato-start-server.txt** - can you please run ls -latrh /tmp and send to me the latest one, the one relevant to this traceback?

Or you can just start the server again and a new temporary file in /tmp will be created.

**Comment by dsuch** [comment]
And another request - please send the result of **git -C /opt/zato/3.0 log -1**. Thanks.

**Comment by Adniel** [comment]
**git -C /opt/zato/3.0 log -1**  tells me: `Unknown option: -C`

I assume it is the same as **git log -1** from **3.0** dir:

```$ pwd
/opt/zato/3.0
$ git log -1
commit f5dbf26b7e10de42ee7835225e24b072df9a854a
Author: Dariusz Suchojad <dsuch-github@m.zato.io>
Date:   Tue Jun 26 14:18:41 2018 +0200

    Merge branch 'main' into support/3.0
```

[tmprTbt3Y-zato-start-server.txt](https://github.com/zatosource/zato/files/3068084/tmprTbt3Y-zato-start-server.txt)

I will also try to do a clean install and test again to make sure I have not done something strange with the environment.

**Comment by Adniel** [comment]
Ok. After removing the zato user and all files and reinstalling zato, the problem is not there anymore. Not sure why. Yet.

**Comment by dsuch** [comment]
The cause is probably the fact the previously the updates somehow were not installed - in the previous git log output you can find that the latest commit was in June 2018 whereas now it will be a correct one from 2019.

**Comment by dsuch** [comment]
Hi @Adniel - I think the ticket may be closed. If you still need anything, please simply reopen. Thanks.
