### ISSUE TITLE
error when creating a subscription

### ISSUE THREAD

**Issue by marcosmile** [zatosource/zato#942]
`Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 473, in __call__
    response = self.req.zato.client.invoke(self.service_name, self.input_dict)
  File "/opt/zato/3.0/code/zato-web-admin/src/zato/admin/middleware.py", line 78, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: e86f9e55b5eeb6b31602d1fd
Details: Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 268, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 502, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/service.py", line 311, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 602, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 584, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 617, in handle
    self.response.payload = self.invoke(sub_service, sub_request)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 602, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 584, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 399, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 323, in handle
    self._handle_subscription(ctx)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 543, in _handle_subscription
    self._subscribe_impl(ctx)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/subscription.py", line 380, in _subscribe_impl
    if has_subscription(session, ctx.cluster_id, ctx.topic.id, ctx.endpoint_id):
  File "/opt/zato/3.0/code/zato-common/src/zato/common/odb/query/pubsub/subscribe.py", line 38, in has_subscription
    scalar()[0]
TypeError: 'bool' object has no attribute '__getitem__'`

I first started using the docker install image for zato3 in january.
This week I rebuild my install with a fresh docker install and I got the error.
I also tried the regular ubuntu install and got the same error.

**Comment by dsuch** [comment]
Hello @marcosmile,

please provide more information - what you are doing precisely, what exact arguments you are providing and in what way.

Please also check server log files for any useful information:

* server.log
* admin.log
* pubsub.log
* pubsub-audit.log

**Comment by marcosmile** [comment]
I have
- a topic
- an outgoing rest connection
- a rest endpoint with pub and sub access to my topic

I want to create a subscription between the endpoint the topic and the outgoing connection.
But I get the error mentioned above.

[admin.log](https://github.com/zatosource/zato/files/3072767/admin.log)
[server.log](https://github.com/zatosource/zato/files/3072768/server.log)

**Comment by LordShion** [comment]
HI, we updated one of our zato instances with 3.1 and are now confronted to this issue.
Any news?

**Comment by dsuch** [comment]
Thank you both, I will investigate it as soon as possible but I cannot commit to a specific deadline at this point.

**Comment by dsuch** [comment]
Hello,

I tried to reproduce this situation with Zato 3.1 and I was not able to, there is no such exception. To be precise, the version I am on is this one:

$ zato --version
Zato 3.1+rev.c34a7c3f3-py2.7.15
$

Note that there is no free support for 3.0 anymore, per our lifecycle policy:

https://zato.io/docs/3.0/release/policy.html

Please upgrade to 3.1 and if it still happens, I will need the exact instructions, step-by-step, on how to reproduce it, along with server.log and admin.log files from servers.

Not just the traceback alone, I will need the whole of it because, like I said, I am not able to reproduce this situation.

Thank you.

**Comment by dsuch** [comment]
Hello,

this is done - please install the latest updates and retry:

https://zato.io/docs/admin/guide/install/update.html
