### ISSUE TITLE
Error when publish to topic

### ISSUE THREAD

**Issue by al-prk** [zatosource/zato#943]
Hello, i cannot publish data to topic from zato service.
I have code like this in my service
```
topic_name = '/pbx/cdr'        
msg_id = self.pubsub.publish(topic_name, data=dumps(cdr))

```
but when it executes, i receive error

```
2019-04-12 12:59:19,882 - INFO - 11547:DummyThread-2 - zato_pubsub.task:342 - Waking task:zpsk.rest.None.b5700380229ccdae571553f2 now:1555063159.88 last:1555063129.88 diff:30.01 interval:2.0 len-list:1
2019-04-12 12:59:19,887 - WARNING - 11547:DummyThread-2 - zato_pubsub.task:294 - Could not deliver pub/sub messages, e:`Traceback (most recent call last):
  File "/opt/zato/3.0/code/zato-server/src/zato/server/pubsub/task.py", line 286, in run_delivery
    deliver_pubsub_msg(self.sub_key, to_deliver if self.wrap_in_list else to_deliver[0])
  File "/opt/zato/3.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 2053, in deliver_pubsub_msg
    'subscription':self.get_subscription_by_sub_key(sub_key)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 2074, in invoke_service
    return self.server.invoke(name, msg, *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 753, in invoke
    *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1311, in invoke
    }, channel, None, needs_response=True, serialize=serialize)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1381, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 477, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/__init__.py", line 403, in _invoke
    service.handle()
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 85, in handle
    func(self, msg, subscription, endpoint_impl_getter)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 116, in _deliver_rest_soap
    http_soap.conn.http_request(subscription.config.out_http_method, self.cid, data=data)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 363, in http_request
    response = self.invoke_http(cid, method, address, data, headers, {}, params=qs_params, *args, **kwargs)
  File "/opt/zato/3.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 96, in invoke_http
    cert=cert, verify=verify, timeout=self.config['timeout'], *args, **kwargs)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/requests/sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/requests/models.py", line 315, in prepare
    self.prepare_body(data, files, json)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/requests/models.py", line 506, in prepare_body
    body = self._encode_params(data)
  File "/opt/zato/3.0/code/local/lib/python2.7/site-packages/requests/models.py", line 97, in _encode_params
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack
`
2019-04-12 12:59:19,890 - WARNING - 11547:DummyThread-2 - zato_pubsub.task:416 - Sleeping for 30.0s after `other-error` in sub_key:`zpsk.rest.None.b5729ccdae571553f2`
```

**Comment by LordShion** [comment]
Hi I'm also running into this issue
on Zato 3.1+rev.36c7bc22b-py3.6.8
got a service on an url rest  ,  with a curl service is ok
got a topic with a notify to a rest outgoing    localhost:11223 with previous working url

`2019-10-11 13:00:58,339 - INFO - 32722:DummyThread-24 - zato.server.connection.http_soap.outgoing:0 - CID:`9f193bf4e09ee7b655605730`, address:`http://localhost:11223/3DS/receive/fmp`, qs:`{}`, auth_user:`3dsservice`, kwargs:`{}`
2019-10-11 13:00:58,340 - WARNING - 32722:DummyThread-24 - zato.server.service:0 - Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 644, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 538, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 86, in handle
    func(self, msg, subscription, endpoint_impl_getter)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 117, in _deliver_rest_soap
    http_soap.conn.http_request(subscription.config.out_http_method, self.cid, data=data)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 367, in http_request
    response = self.invoke_http(cid, method, address, data, headers, {}, params=qs_params, *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 100, in invoke_http
    cert=cert, verify=verify, timeout=self.config['timeout'], *args, **kwargs)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 510, in prepare_body
    body = self._encode_params(data)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 97, in _encode_params
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack (expected 2)

2019-10-11 13:00:58,341 - WARNING - 32722:DummyThread-24 - zato:0 - Could not deliver pub/sub messages, e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pubsub/task.py", line 292, in run_delivery
    deliver_pubsub_msg(self.sub_key, to_deliver if self.wrap_in_list else to_deliver[0])
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1317, in deliver_pubsub_msg
    'subscription':self.get_subscription_by_sub_key(sub_key)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1338, in invoke_service
    return self.server.invoke(name, msg, *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 869, in invoke
    *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1482, in invoke
    }, channel, None, needs_response=True, serialize=serialize)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1552, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 696, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 644, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 538, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 86, in handle
    func(self, msg, subscription, endpoint_impl_getter)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/delivery.py", line 117, in _deliver_rest_soap
    http_soap.conn.http_request(subscription.config.out_http_method, self.cid, data=data)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 367, in http_request
    response = self.invoke_http(cid, method, address, data, headers, {}, params=qs_params, *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 100, in invoke_http
    cert=cert, verify=verify, timeout=self.config['timeout'], *args, **kwargs)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 510, in prepare_body
    body = self._encode_params(data)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 97, in _encode_params
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack (expected 2)

2019-10-11 13:00:58,341 - WARNING - 32722:DummyThread-24 - zato:0 - Sleeping for 5.0s after other-error in sub_key: zpsk.rest.None.087a67
`

**Comment by LordShion** [comment]
publishing message from webadmin

**Comment by LordShion** [comment]
here is a log info of values for the invoke_http
/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 100, in invoke_http

**method**: POST, **address**: http://localhost:11223/3DS/receive/fmp, **data**: [{'data': '1', 'delivery_count': 0, 'expiration': 2147483647000, 'expiration_time_iso': '2087-10-29T16:51:08.041485', 'has_gd': False, 'mime_type': 'application/json', 'priority': 5, 'pub_time_iso': '2019-10-11T13:37:01.041485', 'server_name': 'server1', 'server_pid': 1941, 'size': 1, 'sub_key': 'zpsk.rest.None.1b95f6', 'topic_name': '/3DS/lab_to_odoo', 'msg_id': 'zpsm9f131b5a76939becf1503bba'}], **auth**: ('passremoved', 'passremoved'), **headers**: {'X-Zato-CID': '1166141724e6df6586007d5c', 'X-Zato-Component': 'parallel/dev_zato/ip-XXX-XX-X-XXX.eu-west-3.compute.internal/1941/MainThread', 'X-Zato-Msg-TS': '2019-10-11T13:37:01.437633', 'Content-Type': 'application/json'}, **hooks**: {},**cert**: None, **verify**: False, **timeout**: 10.0, **args**: (), **kwargs**: {'params': {}}

**Comment by LordShion** [comment]
normaly method in /opt/zato/3.1.0/code/lib/python3.6/site-packages/requests/models.py", line 97, in _encode_params

receives for example:
**data:** OrderedDict([('v', '3.1+rev.36c7bc22b-py3.6.8')])
gives
**to_key_val_list(data):** [('v', '3.1+rev.36c7bc22b-py3.6.8')]

but it receives
**data:** [{'data': '{"cproj":"toto"}', 'delivery_count': 0, 'expiration': 2147483647000, 'expiration_time_iso': '2087-10-29T17:51:05.626119', 'has_gd': False, 'mime_type': 'text/plain', 'priority': 5, 'pub_time_iso': '2019-10-11T14:36:58.626119', 'server_name': 'server1', 'server_pid': 3626, 'size': 16, 'sub_key': 'zpsk.rest.None.1b95f6', 'topic_name': '/3DS/lab_to_odoo', 'user_ctx': '', 'zato_ctx': '', 'msg_id': 'zpsmd22b0a5650590ae86830965c'}]
gives
**to_key_val_list(data):** [{'data': '{"cproj":"toto"}', 'delivery_count': 0, 'expiration': 2147483647000, 'expiration_time_iso': '2087-10-29T17:51:05.626119', 'has_gd': False, 'mime_type': 'text/plain', 'priority': 5, 'pub_time_iso': '2019-10-11T14:36:58.626119', 'server_name': 'server1', 'server_pid': 3626, 'size': 16, 'sub_key': 'zpsk.rest.None.1b95f6', 'topic_name': '/3DS/lab_to_odoo', 'user_ctx': '', 'zato_ctx': '', 'msg_id': 'zpsmd22b0a5650590ae86830965c'}]

**Comment by LordShion** [comment]
### **good news.**
after some investigations, it appears that the problem is related to the data_format field on the outgoing channel config
on upon creation of a new outgoing channel , there is not data format field.
thus causing in the database the data_format field is null
which causes the delivery service raising the previous error in this thread.
the solution, is to put data format field in the outgoing rest pop up, so we can choose json or xml, and send correct configuration.
for the moment, we set data_format to json in the database, to avoid the error on our configurations
Can you put again this field on the web admin please @dsuch

**Comment by dsuch** [comment]
Hello,

my apologies that it has taken so long - it is done now, please install updates and Data format will be back.

https://zato.io/docs/admin/guide/install/update.html
