### ISSUE TITLE
Handle exceptions when starting without Internet connection

### ISSUE THREAD

**Issue by jsabater** [zatosource/zato#949]
When starting the servers (via `zato-qs-start.sh` or `zato-qs-restart.sh`) without a connection to the Internet, the following exceptions are thrown:

```
2019-04-23 10:54:37,911 - [1;37mINFO[0m - 2275:MainThread - gunicorn.main:0 - Starting gunicorn 19.9.0
2019-04-23 10:54:37,915 - [1;37mINFO[0m - 2275:MainThread - gunicorn.main:0 - Listening at: http://0.0.0.0:17010 (2275)
2019-04-23 10:54:37,915 - [1;37mINFO[0m - 2275:MainThread - gunicorn.main:0 - Using worker: gevent
2019-04-23 10:54:37,921 - [1;37mINFO[0m - 2307:MainThread - gunicorn.main:0 - Booting worker with pid: 2307
2019-04-23 10:54:38,247 - [1;37mINFO[0m - 2307:MainThread - zato.server.base.parallel:0 - Preferred address of `server1@quickstart-314729` (pid: 2307) is `http://172.17.0.1:17010`
2019-04-23 10:54:39,647 - [1;37mINFO[0m - 2307:MainThread - zato.server.service.store:0 - Deploying cached internal services (server1)
2019-04-23 10:54:41,077 - [1;37mINFO[0m - 2307:MainThread - zato.server.service.store:0 - Deployed 536 cached internal services (server1)
2019-04-23 10:54:41,078 - [1;37mINFO[0m - 2307:MainThread - zato.server.base.parallel:0 - Deploying user-defined services (server1)
2019-04-23 10:54:41,097 - [1;37mINFO[0m - 2307:MainThread - zato.server.base.parallel:0 - Deployed 0 user-defined services  (server1)
2019-04-23 10:54:42,255 - [1;37mINFO[0m - 2307:DummyThread-13 - zato:0 - Set sk_server for sub_key `zpsk.rest.zeci.dc68ae2e78f3e40aa302c3d4` (wsx:0) - `server1:2307`, current sk_servers:
+--------+-----------------+----------+--------+-------------------+----------------------------------------------------------------------------------+
|   #    |     created     |   name   |  pid   |   channel_name    |                                     sub_key                                      |
+========+=================+==========+========+===================+==================================================================================+
|   1    |   2019-04-23    | server1  |  2307  |        ---        |                    b'zpsk.rest.zeci.dc68ae2e78f3e40aa302c3d4'                    |
|        | 08:54:42.254450 |          |        |                   |                                                                                  |
+--------+-----------------+----------+--------+-------------------+----------------------------------------------------------------------------------+
2019-04-23 10:54:42,281 - [1;37mINFO[0m - 2307:MainThread - zato.server.base.parallel:0 - First worker of `server1` is 2307
2019-04-23 10:54:42,288 - [1;37mINFO[0m - 2307:DummyThread-14 - zato.helpers.input-logger:0 - {'request.payload': 'Sample payload for a startup service (first worker)', 'channel': 'startup-service', 'cid': '8789a82648e417b0400c24d3', 'data_format': None, 'environ': {}, 'impl_name': 'zato.server.service.internal.helpers.InputLogger', 'invocation_time': datetime.datetime(2019, 4, 23, 8, 54, 42, 288292), 'job_type': None, 'name': 'zato.helpers.input-logger', 'slow_threshold': None, 'usage': 7, 'wsgi_environ': {'zato.request_ctx.async_msg': Bunch(action='101802', channel='startup-service', cid='8789a82648e417b0400c24d3', msg_type='0001', payload='Sample payload for a startup service (first worker)', service='zato.helpers.input-logger'), 'zato.request_ctx.in_reply_to': None, 'zato.request_ctx.fanout_cid': None, 'zato.request_ctx.parallel_exec_cid': None}}
2019-04-23 10:54:42,298 - [1;37mINFO[0m - 2307:MainThread - zato.server.connection.connector.subprocess_.ipc:0 - Starting SFTP connector for server `server1` on `34567`
2019-04-23 10:54:42,336 - [1;33mWARNING[0m - 2307:DummyThread-29 - zato.updates.check-updates:0 - Traceback (most recent call last):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4948ce5860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zato.io', port=443): Max retries exceeded with url: /support/updates/info-3.1.json?v=3.1pre1%2Brev.236b6758b-py3.6.7 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4948ce5860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/updates.py", line 90, in _serve_forerver
    self._check_notify(url_info, major, minor, _version)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/updates.py", line 187, in _check_notify
    data = self._get_current(_url_info, self_major, self_version)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/updates.py", line 142, in _get_current
    response = requests_get(_url_info.format(self_major), params={'v':self_version})
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/sessions.py", line 625, in send
    r = adapter.send(request, **kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zato.io', port=443): Max retries exceeded with url: /support/updates/info-3.1.json?v=3.1pre1%2Brev.236b6758b-py3.6.7 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4948ce5860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

2019-04-23 10:54:42,338 - [1;37mINFO[0m - 2307:DummyThread-30 - pub.zato.channel.web-socket.cleanup-wsx:0 - Cleaning up old WSX connections; now:`2019-04-23T08:54:42.338531`, md:`7200`, ma:`2019-04-23 06:54:42.338531`
2019-04-23 10:54:44,891 - [1;37mINFO[0m - 2307:DummyThread-31 - zato.helpers.input-logger:0 - {'request.payload': 'Sample payload for a startup service (first worker)', 'channel': 'startup-service', 'cid': '5a26412b7805de4a2f5008bc', 'data_format': None, 'environ': {}, 'impl_name': 'zato.server.service.internal.helpers.InputLogger', 'invocation_time': datetime.datetime(2019, 4, 23, 8, 54, 44, 890983), 'job_type': None, 'name': 'zato.helpers.input-logger', 'slow_threshold': None, 'usage': 8, 'wsgi_environ': {'zato.request_ctx.async_msg': Bunch(action='101802', channel='startup-service', cid='5a26412b7805de4a2f5008bc', msg_type='0001', payload='Sample payload for a startup service (first worker)', service='zato.helpers.input-logger'), 'zato.request_ctx.in_reply_to': None, 'zato.request_ctx.fanout_cid': None, 'zato.request_ctx.parallel_exec_cid': None}}
2019-04-23 10:54:44,901 - [1;33mWARNING[0m - 2307:DummyThread-33 - zato.updates.check-updates:0 - Traceback (most recent call last):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4937ea7320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/zato/zato/code/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zato.io', port=443): Max retries exceeded with url: /support/updates/info-3.1.json?v=3.1pre1%2Brev.236b6758b-py3.6.7 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4937ea7320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/updates.py", line 90, in _serve_forerver
    self._check_notify(url_info, major, minor, _version)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/updates.py", line 187, in _check_notify
    data = self._get_current(_url_info, self_major, self_version)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/internal/updates.py", line 142, in _get_current
    response = requests_get(_url_info.format(self_major), params={'v':self_version})
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/sessions.py", line 625, in send
    r = adapter.send(request, **kwargs)
  File "/opt/zato/zato/code/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zato.io', port=443): Max retries exceeded with url: /support/updates/info-3.1.json?v=3.1pre1%2Brev.236b6758b-py3.6.7 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4937ea7320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

2019-04-23 10:54:44,902 - [1;37mINFO[0m - 2307:DummyThread-34 - pub.zato.channel.web-socket.cleanup-wsx:0 - Cleaning up old WSX connections; now:`2019-04-23T08:54:44.902104`, md:`7200`, ma:`2019-04-23 06:54:44.902104`
2019-04-23 10:54:45,551 - [1;37mINFO[0m - 2307:DummyThread-35 - zato.common.ipc.subscriber.Subscriber:0 - Established sub/bind to ipc:///tmp/zato-ipc-quickstart_314729_server1_2307 (self.pid: 2307)
2019-04-23 10:54:45,751 - [1;37mINFO[0m - 2307:MainThread - zato.server.base.parallel:0 - Started `server1@quickstart-314729` (pid: 2307)
```

What about handling the situation so that these exceptions are not _thrown_ into the log files? Maybe catching them and adding messages to the log files such as "Not attempting to check for updates due to name resolution failure", "Not attempting to check for updates due to connection timeout", or similar.

**Comment by rtrind** [comment]
I believe this already happens in the current stable Zato 2 I have in production. In this case, I just disabled the check for updates in the zato server configuration files and the error does not appear anymore. Anyway it may be a good case for handling the exception in a better way instead of failing like it is now.

**Comment by dsuch** [comment]
Thanks you @jsabater and @rtrind - this is now silenced out.
