### ISSUE TITLE
Cannot access attributes from WritableKeyedTuple

### ISSUE THREAD

**Issue by jsabater** [zatosource/zato#954]
Hello there!

As of the current state of the GIT repo (main branch, commit 49b3dcc94a3fe9a3955aef73e7e850e66fa59549 from Sun May 5 17:48:41 2019 +0200 labelled "GH #790 - We never use file pointers in six."), I cannot seem to be able to access attributes of a WritableKeyedTuple just retrieved using SQLAlchemy.

```
2019-05-07 15:56:33,070 - ESC[1;37mINFOESC[0m - 850:DummyThread-36 - login.list:0 - Result is: [WritableKeyedTuple('Login'=<Login(id='1', username='jsabater', name='Jaume', surname='Sabater', email='jsabater@email.com')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='2', username='user1', name='Graham', surname='Kramer', email='non.nisi@parturient.ca')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='3', username='user2', name='Zeph', surname='Frederick', email='Morbi@tinciduntneque.ca')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='4', username='user3', name='Christopher', surname='Suarez', email='Vivamus.sit@quam.edu')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='5', username='user4', name='Jacob', surname='Booth', email='vitae.erat@cursus.ca')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='6', username='user5', name='Bertha', surname='Casey', email='vel@pede.net')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='7', username='user6', name='Kevin', surname='Joseph', email='consequat.nec@loremegetmollis.co.uk')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='8', username='user7', name='Florence', surname='Stewart', email='habitant@a.org')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='9', username='user8', name='Keegan', surname='Carter', email='id@facilisis.com')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='10', username='user9', name='Tanisha', surname='Wright', email='fringilla.est.Mauris@ac.ca')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='11', username='user10', name='Eliana', surname='Bass', email='erat@posuere.ca')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='12', username='user11', name='Aristotle', surname='Grimes', email='nunc.Quisque.ornare@Praesent.net')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='13', username='user12', name='Colette', surname='Gonzalez', email='eleifend.Cras@estarcu.edu')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='14', username='user13', name='Ezra', surname='Sanchez', email='interdum@pedePraesenteu.edu')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='15', username='user14', name='Chanda', surname='Henson', email='sed.dictum.eleifend@disparturientmontes.net')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='16', username='user15', name='Fredericka', surname='Sheppard', email='bibendum@elitpretiumet.org')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='17', username='user16', name='Dorian', surname='Mclean', email='Mauris@condimentumDonecat.co.uk')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='18', username='user17', name='Berk', surname='Zimmerman', email='purus@pharetra.ca')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='19', username='user18', name='Samuel', surname='Kim', email='cursus@egetmetus.com')>, 'count'=1001), WritableKeyedTuple('Login'=<Login(id='20', username='user19', name='Dexter', surname='Mccarthy', email='risus.at@etmagnisdis.co.uk')>, 'count'=1001)]

2019-05-07 15:56:33,072 - ESC[1;37mINFOESC[0m - 850:DummyThread-36 - login.list:0 - Result row type is <class 'zato.common.odb.api.WritableKeyedTuple'> and value is: WritableKeyedTuple('Login'=<Login(id='1', username='jsabater', name='Jaume', surname='Sabater', email='jsabater@email.com')>, 'count'=1001)

2019-05-07 15:56:33,077 - ESC[1;33mWARNINGESC[0m - 850:DummyThread-36 - zato.server.service:0 - Traceback (most recent call last):
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 571, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/zato/code/zato-server/src/zato/server/service/__init__.py", line 461, in _invoke
    service.handle()
  File "/opt/zato/env/qs-1/server1/work/hot-deploy/current/login.py", line 652, in handle
    self.logger.info('id of the row is: %s' % r.id)
  File "/opt/zato/zato/code/zato-common/src/zato/common/odb/api.py", line 88, in __getattr__
    return getattr(self._elem, key)
AttributeError: 'result' object has no attribute 'id'
```

The code being after executed after retrieving the listing from the database is the following:

```
            if result:
                self.logger.info('Result is: %s' % result)
                # Store the whole result set as well as each item in the cache.
                # Useful for paginated listings.

                # Build the list of dicts.
                lod = []

                # While doing so, store each item.
                for r in result:
                    # Items are WriteableKeyedTuples.
                    # Passwords have already been excluded.
                    # cache.set('id:%s' % r.id, r._asdict())
                    self.logger.info('Result row type is %s and value is: %s' % (type(r), r))
                    self.logger.info('id of the row is: %s' % r[id])
                    lod.append(r._asdict())

                # cache.set(cache_key, lod)
```

The commented lines are what used to be, the `self.logger.info()` lines have been added to help debug the issue.

P.S. How can I remove the default debug mode and turn into _normal_ mode? There's too much information for me right now :-)

**Comment by dsuch** [comment]
Hm, I am not sure what you mean by the debug mode?

**Comment by jsabater** [comment]
When there is an exception, a ton of very detailed information is dumped into the affected server log file (as in massive amounts of information). See attached an example.
[server.log](https://github.com/zatosource/zato/files/3153038/server.log)

**Comment by dsuch** [comment]
When you run servers in foreground (zato start server1 --fg), you can get a nicely formatted traceback, showing what happened, where and what local variables were. Does it not display for you as in the attached file?

**Comment by dsuch** [comment]
Apparently, I cannot upload images to this ticket because "something went wrong" according to GitHub.

**Comment by jsabater** [comment]
If I run the server in the foreground I get the same very verbose version of the exception you can see in the file I uploaded in my previous comment, although it's better formatted and nicely coloured :-)

I mean, it's veeeery long trace, not as they used to be in Zato 3.0. I used the term _debug mode_ as, to me, it seems like very detailed information, useful for debugging, but too extensive for a default mode.

Where in the configuration should I check for the logging levels?

**Comment by dsuch** [comment]
I believe this no longer applies.
