### ISSUE TITLE
Failing get_response_from_cache Zato 3.1 - Python 3.5.2

### ISSUE THREAD

**Issue by catdieng** [zatosource/zato#979]
After a new installation of zato, i tried to call a rest service returning json. I got this error: 

`{"zato_env": {"details": "Traceback (most recent call last):\n  File \"/opt/zato/3.1.0/code/src/zato-server/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 375, in dispatch\n    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)\n  File \"/opt/zato/3.1.0/code/src/zato-server/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 632, in handle\n    cache_key, response = self.get_response_from_cache(service, raw_request, channel_item, channel_params, wsgi_environ)\n  File \"/opt/zato/3.1.0/code/src/zato-server/code/zato-server/src/zato/server/connection/http_soap/channel.py\", line 584, in get_response_from_cache\n    hash_value = _sha256(data).hexdigest()\nTypeError: Unicode-objects must be encoded before hashing\n", "cid": "d71e7feff8fe7dfca011b031", "result": "ZATO_ERROR"}}`

I tried to disable the cache, i found no way in the zato config. The cache remains required on a service creation.

Is there a way to disable the cache requirement and the Encoding

**Comment by dsuch** [comment]
Hello @catdieng,

please share the source code of your service and information on how you invoke it.

Regards.

**Comment by catdieng** [comment]
Sorry, i make a new installtion. I have another matter. I am going to open another issue on github

**Comment by catdieng** [comment]
Again i have the same error again when i try to get an url defined by me in zato :


```
zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`ba4c05b9bb934f615c9f0ccd`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/src/zato-server/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 375, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/src/zato-server/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 632, in handle
    cache_key, response = self.get_response_from_cache(service, raw_request, channel_item, channel_params, wsgi_environ)
  File "/opt/zato/3.1.0/code/src/zato-server/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 584, in get_response_from_cache
    hash_value = _sha256(data).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by dsuch** [comment]
Hello @catdieng - I am thankful for your ticket but I need to say that I am sorry too because I am unable to assist you unless you follow the instructions that I send to you.

**Comment by aatishnn** [comment]
Hi @duch,

I have run into the same issue. So, I might be able to give you more information. The error is:

```
Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 612, in handle
    cache_key, response = self.get_response_from_cache(service, raw_request, channel_item, channel_params, wsgi_environ)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 564, in get_response_from_cache
    hash_value = _sha256(data).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```
I have a service that's attached to a REST channel. It works with curl if I disable the cache in the channel. The above error is thrown only if cache is enabled.

**Comment by dsuch** [comment]
Thanks @aatishnn - can you please install updates and try now?

**Comment by aatishnn** [comment]
@dsuch Thank you. The Unicode error is gone now. 

Sorry to be the bearer of bad news but I have run into a new error when cache is enabled:

```
Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 629, in handle
    self.set_response_in_cache(channel_item, cache_key, response)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 590, in set_response_in_cache
    'status_code': response.status_code.value if _py3 else response.status_code,
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 801, in set_in_cache
    return self.worker_store.cache_api.get_cache(cache_type, cache_name).set(key, value)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/cache.py", line 179, in set
    value = self.impl.set(key, value, expiry, details, meta_ref)
  File "src/zato/cy/cache.pyx", line 752, in src.zato.cy.cache.Cache.set
  File "src/zato/cy/cache.pyx", line 753, in src.zato.cy.cache.Cache.set
  File "src/zato/cy/cache.pyx", line 754, in src.zato.cy.cache.Cache.set
  File "src/zato/cy/cache.pyx", line 682, in src.zato.cy.cache.Cache._set
ValueError: Value too long 3884 > 1000
```

The length of output from the service is 3145 characters.

**Comment by dsuch** [comment]
By default, keys and values are limited to 1000 characters or bytes so you need to increase the limit in your channel's cache definition if you want to store keys and values of larger sizes.

**Comment by aatishnn** [comment]
@dsuch Thanks.

**Comment by dsuch** [comment]
Thanks @aatishnn - I increased this size to 10,000 to rule out any such misunderstandings in case one is just getting started with Zato.
