### ISSUE TITLE
Zato won't start after this message

### ISSUE THREAD

**Issue by catdieng** [zatosource/zato#980]
Hi i got this message on log after that zato refuses to start:

Stderr received from program `/opt/zato/3.1.0/code/bin/py -m zato.admin.main fg=FalseZATO_ZATO_ZATOsecret_key=ZATO_ZATO_ZATOsync_internal=False 1> /dev/null 2> /tmp/tmpcgyo_06f-zato-start-web-admin.txt` e:`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/main.py", line 59, in <module>
    main()
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/main.py", line 55, in main
    RepoManager(repo_dir).ensure_repo_consistency()
  File "/opt/zato/3.1.0/code/zato-common/src/zato/common/repo.py", line 121, in ensure_repo_consistency
    sh.git.commit('-m', 'Committing latest changes')
  File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 1427, in _call_
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 774, in _init_
    self.wait()
  File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/git commit -m Committing latest changes

  STDOUT:
Sur la branche main
rien à valider, la copie de travail est propre

  STDERR:

`, kw:`{'async': True}`

**Comment by dsuch** [comment]
Hello,

can you explain what local changes you made to /opt/zato and then translate this message into English?

Regards.

**Comment by catdieng** [comment]
Here you have the translated output:

```
Stderr received from program /opt/zato/3.1.0/code/bin/py -m zato.admin.main fg=FalseZATO_ZATO_ZATOsecret_key=ZATO_ZATO_ZATOsync_internal=False 1> /dev/null 2> /tmp/tmpcgyo_06f-zato-start-web-admin.txt e:`Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/main.py", line 59, in
main()
File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/main.py", line 55, in main
RepoManager(repo_dir).ensure_repo_consistency()
File "/opt/zato/3.1.0/code/zato-common/src/zato/common/repo.py", line 121, in ensure_repo_consistency
sh.git.commit('-m', 'Committing latest changes')
File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 1427, in call
return RunningCommand(cmd, call_args, stdin, stdout, stderr)
File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 774, in init
self.wait()
File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 792, in wait
self.handle_command_exit_code(exit_code)
File "/opt/zato/3.1.0/code/lib/python3.5/site-packages/sh.py", line 815, in handle_command_exit_code
raise exc
sh.ErrorReturnCode_1:

RAN: /usr/bin/git commit -m Committing latest changes

STDOUT:
On the hand branch nothing to validate, the working copy is clean

STDERR:

, kw:{'async': True}`
```
I didn't make a change in /opt/zato,  i am only making a change for some dependencies through pip

**Comment by dsuch** [comment]
Please send in:

* Information what OS it exactly is
* Output of these commands: cd /opt/zato; git status; git -v

**Comment by catdieng** [comment]
Here you have 

Os:  Ubuntu 16.04

i have no git in /opt/zato but in the folder /opt/zato/3.1.0/ i got this:


```
zato@Zato-2:~/3.1.0$ git branch
  anielkis-f-gh959-support_old_Git_versions
  dsuch-f-gh367-add-web-debugger
  dsuch-f-gh416-ini-files-web-admin
  dsuch-f-gh571-move-bst-to-core
  dsuch-f-gh681-caches
  dsuch-f-gh714-add-live-msg-browser
  dsuch-f-gh723-add-exe-agent
  dsuch-f-gh755-pubsub-wsx
  dsuch-f-gh755-wsx-auto-reconnect3
  dsuch-f-gh759-add-http-plugins
  dsuch-f-gh760-migrate-buildout-to-pip
  dsuch-f-gh790-gunicorn-fork
  dsuch-f-gh793-web-admin-auth
  dsuch-f-gh894-sio-refactor
  dsuch-f-gh915-totp-login
  dsuch-f-gh928-ca-lb-web-admin-scheduler
  dsuch-f-gh951-hot-deploy-order-class-hierarchies
  dsuch-f-gh958-amqp-tls
  dsuch-f-gh960-wsx-broadcast
  dsuch-web-admin-auth
  dw-f-gh827-osx
  energytechglobal-priority-queue
  main
  pre-support/3.0
  support/1.1
  support/2.0
  support/2.0-rhel6
  support/3.0
* support/3.1
  u/crs1
  u/foxway
  u/nus
  u/vedur
```

```
zato@Zato-2:~/3.1.0$ git status
On the support branch / 3.1
Your branch is up to date with 'origin / support / 3.1'.
nothing to validate, the working copy is clean

```
Zato version:

```
zato@Zato-2:~/3.1.0$ zato --version
Zato 3.1+rev.544100e-py3.5.2
```

**Comment by dsuch** [comment]
Can you also say what **git -v** returns?

**Comment by dsuch** [comment]
Actually, it should be **git --version**.

**Comment by orimani** [comment]
Hey there,

I'm having the same issue and found the system or session locale (fr_FR here) + zato-lb-agent.pid + .git are the root cause.

I've just tested on fresh install with locale en_US.UTF-8 and I can't reproduce it.

**How to reproduce:**

```
zato@ubuzato:~$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

zato@ubuzato:~$ ps -u zato x
  PID TTY      STAT   TIME COMMAND
  866 pts/0    S      0:00 -su
  882 pts/0    R+     0:00 ps -u zato x

zato@ubuzato:~$ pwd
/opt/zato

zato@ubuzato:~$ zato --version
Zato 3.1+rev.5edad2960-py3.6.8

zato@ubuzato:~$ git --version
git version 2.17.1

zato@ubuzato:~$ cat /proc/version
Linux version 4.15.0-66-generic (buildd@lgw01-amd64-044) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019

zato@ubuzato:~$ /opt/zato/env-dev/zato-qs-start.sh
Starting Zato cluster zato-dev
Checking configuration
[1/8] Redis connection OK
[2/8] SQL ODB connection OK
[3/8] Checking TCP ports availability
Error - found pidfile `/opt/zato/env-dev/load-balancer/zato-lb-agent.pid`
2019-10-25 08:57:40,842 - INFO - 981:MainThread - Start:87 - Error - found pidfile `/opt/zato/env-dev/load-balancer/zato-lb-agent.pid`

zato@ubuzato:~$ rm /opt/zato/env-dev/load-balancer/zato-lb-agent.pid

zato@ubuzato:~$ /opt/zato/env-dev/zato-qs-start.sh
Starting Zato cluster zato-dev
Checking configuration
[1/8] Redis connection OK
[2/8] SQL ODB connection OK
[3/8] Checking TCP ports availability
2019-10-25 08:29:23,115 - WARNING - 3876:MainThread - zato.common.util.proc:113 - Stderr received from program `/opt/zato/3.1.0/code/bin/py -m zato.agent.load_balancer.main /opt/zato/env-dev/load-balancer/config/repo fg=FalseZATO_ZATO_ZATOsync_internal=FalseZATO_ZATO_ZATOsecret_key= 1> /dev/null 2> /tmp/tmp65kn4rye-zato-start-load-balancer.txt` e:`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/zato/3.1.0/code/zato-agent/src/zato/agent/load_balancer/main.py", line 35, in <module>
    lba = lba_class(repo_dir)
  File "/opt/zato/3.1.0/code/zato-agent/src/zato/agent/load_balancer/server.py", line 486, in __init__
    self.init_config(repo_dir)
  File "/opt/zato/3.1.0/code/zato-agent/src/zato/agent/load_balancer/server.py", line 79, in init_config
    RepoManager(self.repo_dir).ensure_repo_consistency()
  File "/opt/zato/3.1.0/code/zato-common/src/zato/common/repo.py", line 121, in ensure_repo_consistency
    sh.git.commit('-m', 'Committing latest changes')
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/git commit -m Committing latest changes

  STDOUT:
Sur la branche main
rien à valider, la copie de travail est propre


  STDERR:

`, kw:`{'async': True}`

zato@ubuzato:~$ ps -u zato x
  PID TTY      STAT   TIME COMMAND
  866 pts/0    S      0:00 -su
 1611 pts/0    R+     0:00 ps -u zato x

 zato@ubuzato:~$ rm -fr /opt/zato/env-dev/load-balancer/config/repo/.git && \
> rm -fr /opt/zato/env-dev/load-balancer/zato-lb-agent.pid && \
> rm -fr /opt/zato/env-dev/server1/config/repo/.git && \
> rm -fr /opt/zato/env-dev/server2/config/repo/.git && \
> rm -fr /opt/zato/env-dev/scheduler/config/repo/.git && \
> rm -fr /opt/zato/env-dev/web-admin/config/repo/.git


zato@ubuzato:~$ /opt/zato/env-dev/zato-qs-start.sh
Starting Zato cluster zato-dev
Checking configuration
[1/8] Redis connection OK
[2/8] SQL ODB connection OK
[3/8] Checking TCP ports availability
[4/8] Load-balancer started
[5/8] server1 started
[6/8] server2 started
[7/8] Scheduler started
[8/8] Web admin started
Zato cluster zato-dev started
Visit https://zato.io/support for more information and support options

zato@ubuzato:~$ ps -u zato x
  PID TTY      STAT   TIME COMMAND
  866 pts/0    S      0:00 -su
 1694 pts/0    S      0:01 /opt/zato/3.1.0/code/bin/python -m zato.agent.load_balancer.main /opt/zato/env-dev/load-balancer/config/repo fg=FalseZATO_ZATO_ZA
 1732 ?        Ss     0:00 haproxy -D -f /opt/zato/env-dev/load-balancer/config/repo/zato.config -p /opt/zato/env-dev/load-balancer/pidfile
 1753 pts/0    Sl     0:02 gunicorn: master [gunicorn]
 1776 pts/0    Sl     0:03 gunicorn: worker [gunicorn]
 1795 pts/0    Sl     0:02 gunicorn: master [gunicorn]
 1822 pts/0    Sl     0:02 gunicorn: worker [gunicorn]
 1843 pts/0    Sl     0:01 /opt/zato/3.1.0/code/bin/python -m zato.scheduler.main fg=FalseZATO_ZATO_ZATOsync_internal=FalseZATO_ZATO_ZATOsecret_key=
 1845 pts/0    S      0:01 /opt/zato/3.1.0/code/bin/python -m zato.server.connection.connector.subprocess_.impl.sftp fg=FalseZATO_ZATO_ZATOdeployment_key=20
 1887 pts/0    S      0:01 /opt/zato/3.1.0/code/bin/python -m zato.admin.main fg=FalseZATO_ZATO_ZATOsync_internal=FalseZATO_ZATO_ZATOsecret_key=
 1890 pts/0    S      0:01 /opt/zato/3.1.0/code/bin/python -m zato.server.connection.connector.subprocess_.impl.sftp fg=FalseZATO_ZATO_ZATOdeployment_key=20
 1934 pts/0    R+     0:00 ps -u zato x

 zato@ubuzato:~$ /opt/zato/env-dev/zato-qs-stop.sh
Stopping Zato cluster zato-dev
Load-balancer's agent `/opt/zato/env-dev/load-balancer` shutting down
2019-10-25 09:11:29,131 - INFO - 1949:MainThread - Stop:50 - Load-balancer's agent `/opt/zato/env-dev/load-balancer` shutting down
Load-balancer `/opt/zato/env-dev/load-balancer` shutting down
2019-10-25 09:11:29,131 - INFO - 1949:MainThread - Stop:50 - Load-balancer `/opt/zato/env-dev/load-balancer` shutting down
[1/5] Load-balancer stopped
Server `/opt/zato/env-dev/server1` shutting down
2019-10-25 09:11:30,653 - INFO - 1968:MainThread - Stop:50 - Server `/opt/zato/env-dev/server1` shutting down
[2/5] server1 stopped
Server `/opt/zato/env-dev/server2` shutting down
2019-10-25 09:11:32,262 - INFO - 1987:MainThread - Stop:50 - Server `/opt/zato/env-dev/server2` shutting down
[3/5] server2 stopped
Web admin `/opt/zato/env-dev/web-admin` shutting down
2019-10-25 09:11:33,870 - INFO - 2007:MainThread - Stop:50 - Web admin `/opt/zato/env-dev/web-admin` shutting down
[4/5] Web admin stopped
Scheduler `/opt/zato/env-dev/scheduler` shutting down
2019-10-25 09:11:35,425 - INFO - 2027:MainThread - Stop:50 - Scheduler `/opt/zato/env-dev/scheduler` shutting down
[5/5] Scheduler stopped
Zato cluster zato-dev stopped

zato@ubuzato:~$ /opt/zato/env-dev/zato-qs-start.sh
Starting Zato cluster zato-dev
Checking configuration
[1/8] Redis connection OK
[2/8] SQL ODB connection OK
[3/8] Checking TCP ports availability
[4/8] Load-balancer started
[5/8] server1 started
[6/8] server2 started
[7/8] Scheduler started
[8/8] Web admin started
Zato cluster zato-dev started
Visit https://zato.io/support for more information and support options

zato@ubuzato:~$ ps -u zato x
  PID TTY      STAT   TIME COMMAND
  866 pts/0    S      0:00 -su
 2253 pts/0    Sl     0:01 /opt/zato/3.1.0/code/bin/python -m zato.scheduler.main fg=FalseZATO_ZATO_ZATOsync_int
 2318 pts/0    R+     0:00 ps -u zato x

zato@ubuzato:~$ /opt/zato/env-dev/zato-qs-stop.sh
Stopping Zato cluster zato-dev
ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
2019-10-25 09:12:48,015 - ERROR - 2326:MainThread - Stop:668 - ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
[1/5] Load-balancer stopped
ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
2019-10-25 09:12:49,514 - ERROR - 2345:MainThread - Stop:668 - ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
[2/5] server1 stopped
ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
2019-10-25 09:12:51,057 - ERROR - 2364:MainThread - Stop:668 - ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
[3/5] server2 stopped
ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
2019-10-25 09:12:52,574 - ERROR - 2383:MainThread - Stop:668 - ProcessLookupError: (3, 'No such process') (Hint: re-run with --verbose for full traceback)
[4/5] Web admin stopped
Scheduler `/opt/zato/env-dev/scheduler` shutting down
2019-10-25 09:12:54,124 - INFO - 2402:MainThread - Stop:50 - Scheduler `/opt/zato/env-dev/scheduler` shutting down
[5/5] Scheduler stopped
Zato cluster zato-dev stopped

zato@ubuzato:~$ /opt/zato/env-dev/zato-qs-start.sh
Starting Zato cluster zato-dev
Checking configuration
[1/8] Redis connection OK
[2/8] SQL ODB connection OK
[3/8] Checking TCP ports availability
Error - found pidfile `/opt/zato/env-dev/load-balancer/zato-lb-agent.pid`
2019-10-25 09:13:04,986 - INFO - 2476:MainThread - Start:87 - Error - found pidfile `/opt/zato/env-dev/load-balancer/zato-lb-agent.pid`
```

**Comment by dsuch** [comment]
Hello everyone,

I only use English locale so I am not sure how to reproduce it. Does it suffice to install Zato on a French locale-based Ubuntu? Or is there anything else needed?

If this is the only requirement, can you tell me where I can download such a system, preferably already preconfigured with fr_FR?

Thanks.

**Comment by orimani** [comment]
Hi Dariusz,

I don't think you need fr_FR, I'm pretty sure you can test cs_CZ for exemple.
Also, you don't need to grab a full iso, you jsut need to change your locale:

```
20191028-10:14:11 [root] ~ $ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

20191028-10:19:16 [root] ~ $ locale -a
C
C.UTF-8
[...]
en_US.utf8
POSIX

20191028-10:22:53 [root] ~ $ locale-gen fr_FR.UTF-8
Generating locales (this might take a while)...
  fr_FR.UTF-8... done
Generation complete.

20191028-10:22:58 [root] ~ $ locale -a
C
C.UTF-8
[...]
en_US.utf8
[...]
**fr_FR.utf8**
POSIX

20191028-10:23:02 [root] ~ $ update-locale LANG=fr_FR.UTF-8
*** update-locale: Warning: LANGUAGE ("en_US:en") is not compatible with LANG (fr_FR.UTF-8). Disabling it.

20191028-10:27:14 [root] ~ $ exit
logout

20191028-10:27:16 [mat] ~/cube-dev $ sudo su -

20191028-10:27:21 [root] ~ $ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**To go back to en_US:**

```
20191028-10:27:24 [root] ~ $ update-locale LANG=en_US.UTF-8

20191028-10:28:38 [root] ~ $ vi /etc/default/locale
```
**uncomment LANGUAGE="en_US:en"**

```
20191028-10:30:34 [root] ~ $ exit
logout

20191028-10:30:36 [mat] ~/cube-dev $ sudo su -

20191028-10:30:37 [root] ~ $ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by dsuch** [comment]
Thanks, I will try it out and let you know.

**Comment by angeljanne** [comment]
Hi everyone,

I have the same problem. 

Open /zato-common/src/zato/common/repo.py, locate row 117
update code
`has_changes = 'nothing to commit' not in sh.git.status()`

In different language, `sh.git.status()` returns different string. Change it!

**Comment by dsuch** [comment]
This is done, thanks for your input!
