### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode' when accessing Data Dictionary Web Admin

### ISSUE THREAD

**Issue by aatishnn** [zatosource/zato#981]
I am new to Zato. The documentation was flawless, and helped me to get started with Zato in no time. Thank you. 

After the quickstart cluster was up, I added a key-value pair in Data Dictionary from Zato's web admin interface. It saved correctly, and afterwards when I try to load the Data Dictionary page, I get the following error:

```
2019-08-10 09:44:20,937 - ERROR - 13880:DummyThread-45 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`a716182b468556aa2726042a`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 674, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 498, in set_response_data
    response = response.getvalue(serialize=kwargs['serialize'])
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 470, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 418, in _getvalue
    raise ZatoException(self.zato_cid, msg)
zato.common.ZatoException: <ZatoException at 0x7f1a7e307708 cid:`a716182b468556aa2726042a`, msg:`Expected elem:`id` not found in item:`{'id': '', 'system': '', 'key': '', 'value': ''}``>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 341, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 611, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 696, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 644, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/service.py", line 365, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 776, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 752, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 691, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 644, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/kvdb/data_dict/dictionary.py", line 33, in handle
    self.response.payload[:] = self.get_data()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 353, in __setitem__
    return self.__setslice__(key.start, key.stop, value)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 348, in __setslice__
    self.zato_output[i:j] = seq
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/kvdb/data_dict/__init__.py", line 48, in _get_dict_items
    system, key, value = item.decode('utf-8').split(KVDB.SEPARATOR)
AttributeError: 'str' object has no attribute 'decode'
```

System details:
```
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
Python : 3.6.8
PostgreSQL: 10
```

Zato version:
```
zato@ubuntu:~/current$ git status
On branch support/3.1
Your branch is up to date with 'origin/support/3.1'.

nothing to commit, working tree clean
```

Something related to Python 3?

**Comment by dsuch** [comment]
Hello @aatishnn,

thank you for the nice words and for opening the ticket. Yes, it looks related to Python 2 vs. Python 3 string encodings.

Can you just add the following details?

* Output from zato --version
* Information what the key and value were

Regards.

**Comment by aatishnn** [comment]
Hi @dsuch 

Here are the details:

```
$ zato --version
Zato 3.1+rev.5537e98-py3.6.8
```

Data Dictionary:
```
System: SYST1_DHIS
Key:  AA_BB_Case_Vaaaaaaaaaa_Some
Value: xjkGHf0aaS

**Comment by dsuch** [comment]
Thanks - can you install latest updates and try again?

https://zato.io/docs/admin/guide/install/update.html

**Comment by aatishnn** [comment]
Thank you. I can access the page again.
