### ISSUE TITLE
Cannot add new PubSub topic without defining Service on Web Interface

### ISSUE THREAD

**Issue by kkarolis** [zatosource/zato#985]
## Context

**zato-version**: `Zato 3.1+rev.50e2f7b-py2.7.15`
**browser-version**: `Firefox Developer Edition 68.0b9 (64-bit)`
**docker-image-tag**: `3.1-py27`  
**docker-image-checksum**: `cb4d5b9d924e`

## Steps to reproduce

1. Go to `http://localhost:8183/zato/pubsub/topic`
2. Push on Create a new Topic button and create a new topic without service defined
![create new topic](https://user-images.githubusercontent.com/7696589/64350093-c37f7b80-d000-11e9-8068-9dd22ca4fbac.png)
3. Press `OK`
4. Exception is raised
![traceback](https://user-images.githubusercontent.com/7696589/64350266-11947f00-d001-11e9-9875-1d2d6bb9f695.png)

Traceback:
```
Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 488, in __call__
    response = self.req.zato.client.invoke(self.service_name, self.input_dict)
  File "/opt/zato/3.1.0/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 6e7f20eeca8d850b4d29837b
Details: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 696, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
Exception: Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 644, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/meta.py", line 369, in handle_impl
    attrs.pre_opaque_attrs_hook(self, input, instance, attrs)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/topic.py", line 117, in pre_opaque_attrs_hook
    hook_service_name = self.server.service_store.get_service_name_by_id(input.hook_service_id)
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/store.py", line 451, in get_service_name_by_id
    return self.get_service_info_by_id(service_id)['name']
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/store.py", line 425, in get_service_info_by_id
    service_id = int(service_id)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by bip91** [comment]
This comes from line /opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/pubsub/topic.py, line 117 which does not handle the test correctly in Py2,  but works in Py3.

Not sure it is the best way to patch it, 
My workaround is to comment out line 117 and replace it by the second line :

> #if not input.get('hook_service_name'): 
> if not input.get('hook_service_name') and input.get('hook_service_name') is not None:

**Comment by dsuch** [comment]
Thank you both @kkarolis and @bip91 - this is corrected now though please note that the change was different than what @bip91 did. Regards.
