### ISSUE TITLE
NTLM Authentication not working in Zato 3.1 - py 3

### ISSUE THREAD

**Issue by gscholten** [zatosource/zato#988]
I'm trying Zato 3.1 (latest docker image) and can't get an outgoing Soap connection with NTLM Authentication to work:

**To reproduce:** 
Create a NTLM Definition
![image](https://user-images.githubusercontent.com/55585018/65326906-d1adca00-dbb2-11e9-9530-193d282e58ed.png)

Create a outgoing soap connection (with a server that needs NTLM Authentication)
![image](https://user-images.githubusercontent.com/55585018/65327143-6ca6a400-dbb3-11e9-9df5-305f6bd18794.png)

The following warning/error is produced:
```
2019-09-20 12:32:55,099 DEBG 'zato-server2' stdout output:
2019-09-20 12:32:55,098 - WARNING - 1338:DummyThread-133 - zato.server.connection.http_soap.outgoing:0 - Error while adding a SOAP client to `http://scl-vac-exact:8010/services/Exact.Metadata.EG?wsdl` (Suds SOAP) e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/outgoing.py", line 459, in add_client
    client = Client(self.address, autoblend=True, transport=transport)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/reader.py", line 74, in open
    d = self.download(url)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/reader.py", line 92, in download
    fp = self.options.transport.open(Request(url))
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/transport/https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/transport/http.py", line 67, in open
    return self.u2open(u2request)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/transport/http.py", line 128, in u2open
    url = self.u2opener()
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/transport/http.py", line 143, in u2opener
    return urllib.request.build_opener(*self.u2handlers())
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/suds/transport/https.py", line 94, in u2handlers
    from ntlm import HTTPNtlmAuthHandler
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/ntlm/HTTPNtlmAuthHandler.py", line 88
    except socket.error, err:
                       ^
SyntaxError: invalid syntax
```

The same NTLM Authentication works fine in our current setup (Zato 2.0.8)
**_note:_** I also tried using NTLM directly, using "zato-no-security" on the soap connection, and the adding NTLM when connecting to the client:

from suds.transport.https import WindowsHttpAuthenticated
ntlm = WindowsHttpAuthenticated(username='xx', password='xx')
client.set_options(transport=ntlm)
...
This produces the same error.

**Comment by dsuch** [comment]
This is done and pushed to branch "main". It will be released in the next version of Zato.
