### ISSUE TITLE
Scheduler job is not editable.

### ISSUE THREAD

**Issue by fenist19** [zatosource/zato#991]
Zato 3.1+rev.91e592017-py3.6.8
Run from docker:
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"

I create new scheduler job . Jub runs success.
But after edit job in  scheduler logs next error.
> 2019-10-11 13:20:09,575 - ERROR - 91:DummyThread-53 - zato_scheduler:139 - Caught exception `Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-scheduler/src/zato/scheduler/api.py", line 137, in create_edit
    handler(job_data, **kwargs)
  File "/opt/zato/3.1.0/code/zato-scheduler/src/zato/scheduler/api.py", line 230, in edit_cron_style
    self.create_edit_cron_style(job_data, False, **kwargs)
  File "/opt/zato/3.1.0/code/zato-scheduler/src/zato/scheduler/api.py", line 219, in create_edit_cron_style
    cron_definition=job_data.cron_definition, **kwargs)
  File "/opt/zato/3.1.0/code/zato-scheduler/src/zato/scheduler/api.py", line 161, in create_edit_job
    func(job, **kwargs)
  File "/opt/zato/3.1.0/code/zato-scheduler/src/zato/scheduler/backend.py", line 341, in edit
    self._unschedule_stop(job, '(src:edit)')
  File "/opt/zato/3.1.0/code/zato-scheduler/src/zato/scheduler/backend.py", line 366, in _unschedule_stop
    if self._unschedule(job):
  File "/opt/zato/3.1.0/code/zato-scheduler/src/zato/scheduler/backend.py", line 352, in _unschedule
    if name in self.jobs.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

In intarface job changed, but scheduler runs old job config.
For change job need delete job and create new.
This error on all types of jobs.

**Comment by dsuch** [comment]
Hello @fenist19 - this is done, please install latest updates and try again:

https://zato.io/docs/admin/guide/install/update.html

**Comment by fenist19** [comment]
problem solved. Thanks.
