### ISSUE TITLE
RabbitMQ 3.8.0 x-queue-type causes errors in Zato

### ISSUE THREAD

**Issue by michaljasionowski** [zatosource/zato#995]
After upgrading RabbitMQ to 3.8.0, Zato can no longer consume amqp messages. It seems it's due to new 'x-queue-type' queue argument introduced in 3.8.0.

```
2019-10-29 12:31:21,886 - ^[[1;37mINFO^[[0m - 11429:DummyThread-58 - zato.server.connection.amqp_:0 - Could not create an AMQP consumer for channel `EPWA azure` (35837 attempts so far), e:`Traceback (most recent call last):
  File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/amqp_.py", line 144, in _get_consumer
    self.config.consumer_tag_prefix, get_component_name('amqp-consumer')))
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/kombu/messaging.py", line 408, in revive
    self.declare()
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/kombu/messaging.py", line 421, in declare
    queue.declare()
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/kombu/entity.py", line 605, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/kombu/entity.py", line 614, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/kombu/entity.py", line 649, in queue_declare
    nowait=nowait,
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/channel.py", line 1149, in queue_declare
    spec.Queue.DeclareOk, returns_tuple=True,
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/opt/zato/3.1.0/code/lib/python3.6/site-packages/amqp/channel.py", line 277, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'to-zato' in vhost 'EPWA': received none but current is the value 'classic' of type 'longstr'
`
```

**Comment by dsuch** [comment]
Closing old tickets.
